Update detection of skipped/undeclared species
Cantera/cantera pull request #1027
Opened 2021-04-29 19:56 UTC by ischoegl

**Changes proposed in this pull request**

- Fix skipping of undeclared species with specific third body detection
- Streamline detection of undeclared species in other cases 
- Update formatting for `Reaction::validate`

**If applicable, fill in the issue number this pull request is fixing**

Fixes #1024

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2021-05-04 17:59 UTC, speth requested changes
The failures in the ionized flame tests aren't trivial. It looks like the logic here is causing all third body and falloff reactions containing "M" as the third body to be left out. The `ch4_ion` input file should create a phase with 110 reactions, but it only contains 96 with the changes in this PR.

I'm a little surprised that these are the only tests that catches this problem.

As far as the implementation here, I wonder if it would make sense to move more of this checking into the `Reaction` classes, rather than having different implementations of this decision tree in `Kinetics::addReaction` and `getReactions`. It could almost be part of `Reaction::validate`, with the wrinkle that `validate` doesn't currently take the `Kinetics` object as an argument.

2021-05-04 18:10 UTC, ischoegl commented
> The failures in the ionized flame tests aren't trivial. 

Huh?! ... I remember checking on the number of reactions earlier also, but must have overlooked something here. It's pretty surprising that none of the other CI tests failed, and I had issues with `IonFlame` before.

Regarding the implementation: I retained the *old* philosophy where `Reaction::validate` checks for syntax, whereas `Kinetics::addReaction` ensures that all species are present. I believe it makes sense to keep this separation ...

2021-05-04 21:14 UTC, speth commented
Given that the only place where `Reaction::validate` is called is in `Kinetics::addReaction`, I'm not sure the distinction of what kind of checks belong where is that important. I guess there is a distinction between whether a `Reaction` is generically valid, and whether it is fully defined for a specific `Kinetics` object, so maybe this doesn't belong in the `validate` function specifically.

But I think we could avoid having to add three new functions to the `Reaction` interface, and avoid the growth in complexity of both `Kinetics::addReaction` and `getReactions`, especially since the two implementations differ in ways that don't entirely make sense to me. For instance, the version in `Kinetics::addReaction` goes through the effort of explaining which species are undeclared, while the version in `getReactions` does not provide this information. Plus, that way it's only one implementation that has to be debugged to fix the current issue.

2021-05-05 02:23 UTC, ischoegl commented
> [...] I guess there is a distinction between whether a `Reaction` is generically valid, and whether it is fully defined for a specific `Kinetics` object, so maybe this doesn't belong in the `validate` function specifically.

This is pretty much my point, and `validate` should be imho called after the `Reaction` setup outside of `Kinetics` (e.g. it could be called by the factory methods `newReaction`). That way that separation would be much clearer - it's a little more of a change than what I had intended to do, but it would make sense.

I see your point of not wanting to add more methods to `Reaction` than necessary. A middle ground would be to create a new `Reaction::checkSpecies` method, that gets called by `Kinetics::addReaction`. Note that once #995 is fully implemented, there wouldn't be a need to overload, as the handling of third bodies will be more generic and everything can be handled by a single method. One advantage would be that the same logic can be used by `getReactions`, where I did improve output, but not to the same extent as what is done elsewhere.

2021-05-05 14:06 UTC, speth commented
> This is pretty much my point, and `validate` should be imho called after the `Reaction` setup outside of `Kinetics` (e.g. it could be called by the factory methods `newReaction`). That way that separation would be much clearer - it's a little more of a change than what I had intended to do, but it would make sense.

You could do the validation in `newReaction` for reactions created from YAML, but this validation also applies for reactions that are built up purely in code, in which case it's sort of hard to do it before you get to `addReaction`. And we wouldn't want to do the validation twice for the most common case where the reactions are generated from an input file.

> I see your point of not wanting to add more methods to `Reaction` than necessary. A middle ground would be to create a new `Reaction::checkSpecies` method, that gets called by `Kinetics::addReaction`. Note that once #995 is fully implemented, there wouldn't be a need to overload, as the handling of third bodies will be more generic and everything can be handled by a single method. One advantage would be that the same logic can be used by `getReactions`, where I did improve output, but not to the same extent as what is done elsewhere.

I'm 👍 on `Reaction::checkSpecies`, and if it doesn't require any overloads once we get through #995, that's even better.

2021-05-07 18:46 UTC, ischoegl commented
> You could do the validation in `newReaction` for reactions created from YAML, but this validation also applies for reactions that are built up purely in code, in which case it's sort of hard to do it before you get to `addReaction`. And we wouldn't want to do the validation twice for the most common case where the reactions are generated from an input file.

Fair point. For the new structure, I started to differentiate between validation of rate parameters and reaction equations, which would make that part easier, as each can be tied to calling specific functions with known behavior. From my perspective, it would still be worthwhile to run the check immediately (i.e. prior to `addReaction`), no matter whether a reaction is constructed from YAML or built in code. I believe I have an idea and will suggest that once I get back to updating this PR.

> [...] if it doesn't require any overloads once we get through #995, that's even better.

Unfortunately overloads will be necessary until CTI/XML support is removed as I do not anticipate porting the old loaders to the new reaction framework.

2021-05-08 13:21 UTC, ischoegl commented
@speth ... I fixed the logic, and moved the tests as discussed (I also moved the `checkReactionBalance` check so it will cover `getReactions`). I ended up not moving the `Reaction::validate` calls to avoid conflicts with other ongoing work.

2021-05-08 22:16 UTC, speth commented
For the case of `ch4_ion.yaml`, I'm still seeing one issue, which is that the reaction `H + O2 + AR <=> HO2 + AR` is still getting added, even though the phase doesn't define `AR` as a species. This results in a reaction where the `forward_rates_of_progress` entry is `nan`, as are the `net_production_rates` for `H', `O2` and `HO2`.

Interestingly, the same reaction is also added when creating a phase from `ch4_ion.cti`, but in that case the rate for this reaction is just zero, and the net production rates are fine. This is presumably why the ionized flame tests are working.

2021-05-09 08:54 UTC, ischoegl commented
@speth ... thanks for catching this: my earlier fix of the logic glitch broke something that had worked before ... turns out that the logic needed to work differently for reactions with specified collision partners. It should all be good now - I also switched the unit tests to `ch4_ion.yaml` to make sure.

2021-05-09 21:57 UTC, speth reviewed
Thanks, @ischoegl, this looks good. I have only a couple of incredibly minor comments below.

2021-05-09 21:57 UTC, speth commented on src/kinetics/Reaction.cpp
> +           }
❤️ the expanding use of `InputFileError`

2021-05-09 21:57 UTC, speth commented on src/kinetics/Reaction.cpp
> +    Composition balr, balp;
If you want the visual space here, I'd suggest
```suggestion
void Reaction::checkBalance(const Kinetics& kin) const
{
    Composition balr, balp;
```
Cantera's code isn't particularly consistent about this minor formatting detail, so I think it's fine with the brace in either place, but that might be a way of solving our opposite preferences about blank lines at the start of a block. The one case where I do think having the brace on a new line by itself is especially useful is when the function signature end up being split across multiple lines so you don't end up with a weird looking dedent.

2021-05-09 21:57 UTC, speth commented on src/kinetics/Reaction.cpp
> +    checkBalance(kin);
Rogue comment line

2021-05-10 06:18 UTC, ischoegl commented on src/kinetics/Reaction.cpp
> +           }
Of course ... it provides superior feedback.

2021-05-10 06:19 UTC, ischoegl commented on src/kinetics/Reaction.cpp
> +    Composition balr, balp;
Not a problem. I don't have hard preferences when it comes to coding style.

2021-05-10 12:50 UTC, speth approved these changes

2021-05-10 12:50 UTC, merged