[Kinetics] Fix issue 717, Add check for sticking coefficient more than 1
Cantera/cantera pull request #1038
Opened 2021-05-12 22:02 UTC by 12Chao

**Changes proposed in this pull request**

- This pull request fixes issue #717, which checks if the sticking coefficient gamma is more than 1.  The check is conducted at
6 different temperature points from 200K to 10000K for `InterfaceReaction` and `BlowersMaselInterfaceReaction`. Any temperature point with sticking coefficient more than 1 will be added into error message. 

**If applicable, fill in the issue number this pull request is fixing**

Closes #717 

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2021-05-13 05:49 UTC, ischoegl commented
While this looks pretty good, I believe that the validation should be implemented strictly within `InterfaceReaction::validate()` / `BlowersMaselInterfaceReaction::validate()` as this validation is specific to those types of reactions. It should be straight-forward to implement a 'helper' function within `Reaction.cpp` instead.

2021-05-13 05:50 UTC, ischoegl requested changes

2021-05-13 05:50 UTC, ischoegl commented on src/kinetics/Reaction.cpp
> +    if (is_sticking_coefficient != false) {
can be simplified.

2021-05-13 05:50 UTC, ischoegl commented on include/cantera/kinetics/RxnRates.h
> +    void validate(const std::string& equation);
I do not believe that this is the correct place to add this check, as for the vast majority of `Arrhenius` rates the sticking coefficient does not apply.

2021-05-13 05:50 UTC, ischoegl commented on src/kinetics/RxnRates.cpp
> +        throw CanteraError("Arrhenius::validate", to_string(err_reactions));
With the introduction of YAML, `InputFileError` provides a mechanism to point directly to the YAML section where the issue occurs (although the exception still works for CTI).

2021-07-01 13:56 UTC, bryanwweber commented
@12Chao Have you been able to update this PR in response to the review? Thanks!

2021-07-08 05:19 UTC, 12Chao commented
Sorry for the late response, I agree that there could be a better place for validate functions, but I cannot figure out where is more reasonable for these functions as an `Arrhenius` class is created before a `SurfaceArrhenius` class.

2021-07-08 19:08 UTC, speth commented
You can just evaluate the rate constant at the specified set of temperatures in `InterfaceReaction::validate` and `BlowersMaselInterfaceReaction::validate`, right? I think that would alleviate the concern about having a strange `Arrhenius::validate` method that would likely fail if you ran it for a non-sticking reaction.

2021-07-10 23:12 UTC, 12Chao commented
> You can just evaluate the rate constant at the specified set of temperatures in `InterfaceReaction::validate` and `BlowersMaselInterfaceReaction::validate`, right? I think that would alleviate the concern about having a strange `Arrhenius::validate` method that would likely fail if you ran it for a non-sticking reaction.

Yes, `Arrhenius::validate` function is only called by `InterfaceReaction::validate` and `BlowersMaselInterfaceReaction::validate`, but I think @ischoegl means that maybe the rate validate function could be placed at some less confused place with the new framework coming up? I agree that adding the validate function into `SurfaceArrhenius` and `BMSurfaceArrhenius` classes makes more sense, but I could not get it work because the `Arrhenius` and `BlowersMasel ` rate classes are created first when adding the surface reactions, so maybe the new framework could help on that?

2021-07-11 20:26 UTC, speth commented
> Yes, `Arrhenius::validate` and `BlowersMasel::validate` functions are only called by `InterfaceReaction::validate` and `BlowersMaselInterfaceReaction::validate` for sticking reactions, but I think @ischoegl means that maybe the rate validate function could be placed at some less confused place with the new framework coming up? 

I'm not sure there's that much reason to worry about future changes to use the new `ReactionRate` classes for interface reactions. If this feature is implemented purely on the `InterfaceReaction` and `BlowersMaselInterfaceReaction` classes, it will be easier to make the transition than if this validation is done in the `Arrhenius` class that doesn't (and shouldn't) know anything about sticking coefficients in the first place.

> I agree that adding the validate function into `SurfaceArrhenius` and `BMSurfaceArrhenius` classes makes more sense, but I could not get it work because the `Arrhenius` and `BlowersMasel ` rate classes are created first when adding the surface reactions, maybe this can be achieved with the new reaction framework?

I am not suggesting moving the validation to the `SurfaceArrhenius` or `BMSurfaceArrhenius` classes - I'm suggesting that the validation should happen entirely in the corresponding `Reaction` class's `validate` method, since this is where the check can be conditional based on the `is_sticking_coefficient` variable. You already have half of the logic placed there. For example, something like the following pseudo-code:
```c++
void InterfaceReaction::validate() {
    ElementaryReaction::validate();
    if (is_sticking_coefficient) {
        for (double T : temperatureList) {
            k = rate.updateRC(log(T), 1.0/T);
            if (k > 1) {
                throw InputFileError("InterfaceReaction::validate", input, "bad sticking factor");
            }
        }
    }
}
```

I think you'll need to do something a little more complex to validate this for Blowers-Masel reactions, given your parameter space now has two dimensions.

2021-07-13 14:53 UTC, 12Chao commented
@speth Thanks for the instruction, Could you please give me a hint about how to call the `ThermoPhase` object in `reaction.cpp` file so that I can use the delta enthalpy for Blowers-Masel reaction? I failed trying to use `m_thermo` and `thermo_t` objects to represent the `ThermoPhase` .

2021-07-13 16:53 UTC, speth commented
A `Reaction` object doesn't inherently have access to a `ThermoPhase` object to use for this purpose. Even if it did, I think it wouldn't be sufficient to validate using the enthalpy of reaction at the current state of the `ThermoPhase` (when the reaction is being added) - I think you'd need to consider the enthalpy of reaction at any temperature that's valid for the phase.

Doing that would complicate things a bit -- you'd probably need to pass the `Kinetics` object as an argument to the `Reaction::validate` method (from which you can get access to the `ThermoPhase` object(s), and that would require shuffling some things around to deprecate the current `validate` method as well.

2021-08-09 15:32 UTC, 12Chao commented
Thanks for all the help, I have addressed all the comments for this PR and would be appreciated if anyone could review the new changes

2021-08-11 20:16 UTC, ischoegl commented
@12Chao ... thanks for your work on this. But I do have a philosophical question - checking the sticking coefficient here goes in the direction of a mechanism check, which is historically not really done within Cantera but relegated to external tools (e.g. ChemCheck, see Cantera/enhancements#42). In another context, you'll see some warnings (e.g. thermo data with discontinuities), but that's about that. 

Throwing an error means that a (potentially inexperienced) user would have to fix the YAML file in order to proceed. If they just happened to convert a (buggy) CHEMKIN file from some web repository, this would mean that in most cases those users would be stuck and post on the user group, etc.. So the main question here (which goes beyond syntax) would be:
* Would it make sense to just limit the sticking coefficient to 1 by a simple `min` operation? (Just like rate-of-progress is automatically set to 0 when concentrations become negative).
* Could you run the check you implemented just once at the beginning to trigger the warning? Also, if a user won't ever run at temperatures high enough to be of concern, does there even have to be a warning?

Regarding changing the signature of `Reaction::validate()` to include `Kinetics` I do have some reservations ... current checks mostly involve simple syntax/formatting checks, and not more comprehensive kinetic validations. In general, there is a chicken-and-egg issue when defining reactions: you build `Kinetics` from `Reactions`, but at the same time need `Kinetics` to validate a reaction. Keep in mind that there is the possibility of building kinetics from 'scratch' (individual reactions), where a completely coherent approach would be to run the check you're envisioning when a reaction is added to `Kinetics` (instead of when it is originally created). One step in this direction would be to simply use a different name and call it later, while leaving the original `Reaction::validate()` as is - as it is really meant for a different kind of 'validation'.

2021-08-12 03:01 UTC, 12Chao commented
@ischoegl Thanks for the comments. Moving the check to ChemCheck is a easy task, and I can definately work on that in the future.
> * Would it make sense to just limit the sticking coefficient to 1 by a simple `min` operation? (Just like rate-of-progress is automatically set to 0 when concentrations become negative)

 I'm not sure how to deal with the problematic sticking coefficient except raising an error message is the best, but I think at least we need to warn the user if their sticking coefficient exceeds the limit.
 
> Regarding changing the signature of `Reaction::validate()` to include `Kinetics` I do have some reservations ... current checks mostly involve simple syntax/formatting checks, and not more comprehensive kinetic validations. In general, there is a chicken-and-egg issue when defining reactions: you build `Kinetics` from `Reactions`, but at the same time need `Kinetics` to validate a reaction. Keep in mind that there is the possibility of building kinetics from 'scratch' (individual reactions), where a completely coherent approach would be to run the check you're envisioning when a reaction is added to `Kinetics` (instead of when it is originally created). One step in this direction would be to simply use a different name and call it later, while leaving the original `Reaction::validate()` as is - as it is really meant for a different kind of 'validation'.

I'm a little confused about this comment. The `Kinetics`  input is not used for the validate of other types of reactions but only `BlowersMaselInterfaceReactions`. `Kinetics` is used because  `ThermoPhase` is needed in the sticking coefficient calculation for `BlowersMaselInterfaceReactions` , there is no reaction data involved. Even a new reaction is added, it has to go through the same validation as well, so there should be no problem of validating the new reaction right(because it only needs the species thermo data from the `ThermoPhase`, sorry if I was wrong)?



> * Could you run the check you implemented just once at the beginning to trigger the warning? Also, if a user won't ever run at temperatures high enough to be of concern, does there even have to be a warning?

This is a good point,  I am currently just doing the same check like the PLOG reaction validation, but I can try to move the validate functions to `KineticsFactory::addReactions` and only validate the current temperature point, in that way I don't have to add `Kinetics` input to all the validate functions  either.

2021-08-12 03:24 UTC, ischoegl commented
> I'm a little confused about this comment. [...]

It's a pretty subtle point. A lot of the `Reaction` derived objects use overloaded methods, so they can be called from the base without having to think about a specific implementation (meaning that all methods are called in the same way). @speth mentioned that the current (argument-less) `validate` method would have to be deprecated in favor of one that takes `Kinetics` as an argument to expose thermo data. Extrapolating, this would mean to add `Kinetics` everywhere even if this is ultimately only needed for a select few cases. 

My (admittedly personal) opinion here is to use arguments as frugally as possible (i.e. don't add them unless absolutely needed), which would favor the case against changing the current `validate` signature. The other subtle point here is that checking things as late as possible gets around the chicken-and-egg problem I previously mentioned. If your check were to be executed when the reaction is added to `Kinetics`, things flow naturally. As things stand now, `Reaction::validate` is called when the object is instantiated. All of this is admittedly subtle - so take it with a grain of salt.

2021-08-12 03:48 UTC, 12Chao commented
Thanks for the suggestion! I'll try to come up with a better way to avoid the changes to these `validate` functions.

2021-08-12 03:52 UTC, ischoegl commented
> Thanks for the suggestion! I'll try to come up with a better way to avoid the changes to these `validate` functions.

Sure. But wait for others to weigh in also - whatever you do, these subtle points shouldn't keep you from wrapping this work up. Passing `Kinetics` isn't a problem with the code as it stands, and my preference to run some of those checks as late as possible may not be universally shared. I am just hoping to convince everyone eventually ...

2021-08-17 20:36 UTC, speth commented
> My (admittedly personal) opinion here is to use arguments as frugally as possible (i.e. don't add them unless absolutely needed), which would favor the case against changing the current `validate` signature.

I agree in general, but I think that this isn't actually the only case where having the `Kinetics` (and by extension, `ThermoPhase`) object present for validating a reaction would be helpful. For instance, it could also be used to select the temperatures used for validating P-log rates based on the valid temperature range for the phase.

> If your check were to be executed when the reaction is added to `Kinetics`, things flow naturally. As things stand now, `Reaction::validate` is called when the object is instantiated. All of this is admittedly subtle - so take it with a grain of salt.

The point where validation is called isn't changed here, is it? Generally, it will be called at the point when a reaction is added to the `Kinetics` object. The only case where it happens when a `Reaction` is first created is when the `getReactions` function is called. Whether that makes sense or not seems orthogonal to this PR.

> But I do have a philosophical question - checking the sticking coefficient here goes in the direction of a mechanism check, which is historically not really done within Cantera but relegated to external tools (e.g. ChemCheck, see [Cantera/enhancements#42](https://github.com/Cantera/enhancements/issues/42)). In another context, you'll see some warnings (e.g. thermo data with discontinuities), but that's about that.
>
> Throwing an error means that a (potentially inexperienced) user would have to fix the YAML file in order to proceed. If they just happened to convert a (buggy) CHEMKIN file from some web repository, this would mean that in most cases those users would be stuck and post on the user group, etc..

I think it's possible to make a useful distinction between checking for issues in an input file and a tool for helping figure out what's actually wrong with the input file and how to fix it. I'd say the first part is something that is good to build directly into Cantera. Otherwise, people are going to just blithely use mechanisms with these problems and are not going to do the due diligence of running them through `ChemCheck`.

I do agree that automatically treating this as an error might be a bit extreme, and by analogy with how Cantera treats discontinuous thermo data, it might make sense to have the default behavior here be to just issue a warning. I'm sure we'll still get some posts to the Users' Group, though.

2021-08-17 22:03 UTC, ischoegl commented
> I think that this isn't actually the only case where having the`Kinetics` (and by extension, `ThermoPhase`) object present for validating a reaction would be helpful.

and 

> I think it's possible to make a useful distinction between checking for issues in an input file and a tool for helping figure out what's actually wrong with the input file and how to fix it.

:+1: I agree ... 

> The point where validation is called isn't changed here, is it? Generally, it will be called at the point when a reaction is added to the `Kinetics` object. 

This is technically true for the YAML route, but only as things happen in a direct sequence. As you mentioned, this is not universally true: `validate` is typically called from a `Reaction` constructor, which doesn't necessarily require an immediate addition to `Kinetics` for some other creation routes. 

My main point is that I hope to avoid an across-the-board `void validate(const Kinetics& kin)` signature ... I'd much prefer to have one set of checks that do not rely on `Kinetics` (i.e. these would trigger failures at the `Reaction` level), and a second set of checks that require more in-depth information from `Kinetics` (which would fail when those reactions are added to `Kinetics`). Much of this can be differentiated in separate PR's, as this goes well beyond of what was originally proposed here. Having separate `void validate()` and `void validate(const Kinetics& kin)` is all I am asking for at the moment. 

In other words, I am asking for
```C++
//! @deprecated To be removed after Cantera 2.6
virtual void validate();
```
to be reconsidered.

2021-08-17 22:12 UTC, 12Chao commented
I can keep the validation function as is, if we all agree on throw a warning instead of an error.

2021-08-25 15:04 UTC, 12Chao commented
Another way to raise the warning for problematic sticking coefficient at the current temperature is to add 
```
    for (size_t n = 0; n < m_stickingData.size(); n++) {
        const StickData& item = m_stickingData[n];
        if (kf[item.index] > 1) {
            double T = thermo(surfacePhaseIndex()).temperature();
            warn_user("InterfaceKinetics::applyStickingCorrection",
                      "\nSticking coefficient of reaction {} is bigger than 1 at {} K.",
                      m_reactions[item.index]->equation(), T);
        }
        if (item.use_motz_wise) {
            kf[item.index] /= 1 - 0.5 * kf[item.index];
        }
        kf[item.index] *= factors[n] * sqrt(T) * item.multiplier;
```
in `InterfaceKinetics::applyStickingCorrection`, it will check if a forward rate constant is more than 1 before applying the correction. Since `InterfaceKinetics::applyStickingCorrection` is called in `InterfaceKinetics::_update_rates_T`, so it will throw a warning if there is a problem with sticking coefficients every time the `forward_rate_constants` function is called. This way the code modification is the least, but it may affect the code efficiency as it does extra checks when `forward_rate_constants` is called. Any suggestion on which way I should go for would be appreciated! @rwest @bryanwweber @speth @ischoegl

2021-09-17 17:43 UTC, speth commented
> Having separate `void validate()` and `void validate(const Kinetics& kin)` is all I am asking for at the moment (it would help to have a more meaningful nomenclature _eventually_).

OK, that makes sense to me. Being able to catch issues that don't need the `Kinetics` object when the `Reaction` is first instantiated would have some benefits.

@12Chao, can you update to reflect this consensus? I hope you still have a branch with the version where you added the `void validate(const Kinetics& kin)` function?

2021-09-23 19:30 UTC, 12Chao commented
I have updated the code, but I didn't figure out how to write a test to catch the `CanteraWarning` .  I tried to catch is as a `CanteraError`, but it didn't work. Is there another way that I could try?

2021-09-23 20:11 UTC, ischoegl commented
@12Chao ... The way I've seen this done is to make Cantera warnings fatal (`Cantera::make_deprecation_warnings_fatal();` in C++, or `ct.make_deprecation_warnings_fatal()` in Python). If this flag is set, warnings are converted to errors and you can test for correct behavior.

2021-09-25 15:52 UTC, speth commented
Yeah, I don't think we currently have a way of testing warnings issued by the C++ `warn_user` command.

If you want to be able to test the warning message being generated here, I guess you could add a similar global flag like we use for deprecation warnings to temporarily make the warnings into errors and catch that exception -- see the implementation of `Application::warn_deprecated` and the functions related to the `Application::m_fatal_deprecation_warnings` variable as a kind of template.

This is related to https://github.com/Cantera/enhancements/discussions/112, where the feature described there would make it easier to make trap the warning in a Python test.

One short-term option is to just have a test that issues this warning and leave testing whether that is actually the case as a "TODO" item, and we can accept that the fact that the test coverage will show this bit of code being called as good enough for now.

2021-09-27 21:45 UTC, 12Chao commented
Thanks! I have made a new function to convert `CanteraWarning` into `CanteraError` and used in the test.

2021-10-06 01:10 UTC, speth requested changes
Thanks for the updates, @12Chao. I think we'll find being able to test warning messages handy in some other cases as well.

I have some suggested revisions that I think will help simplify the implementation of the new validation methods.

2021-10-06 01:10 UTC, speth commented on include/cantera/base/global.h
> +void make_cantera_warnings_fatal();
I think this function can just be named `make_warnings_fatal`. Likewise for the Python function.

2021-10-06 01:10 UTC, speth commented on include/cantera/kinetics/InterfaceKinetics.h
> +
This function needs a docstring. I'd also suggest `reactionEnthalpy` as a name that's more consistent with other function names in Cantera's C++ code.

2021-10-06 01:10 UTC, speth commented on include/cantera/kinetics/Kinetics.h
> +    };
I understand that this function only gets used for `InterfaceKinetics`, but is there a reason for it to be implemented only for that class? Would the implementation for `Kinetics` be any different? Having it return 0 here seems not ideal.

2021-10-06 01:10 UTC, speth commented on include/cantera/kinetics/Reaction.h
> +    virtual void validate(Kinetics& kin);
For the docstring, I'd suggest something along the lines of "Perform validation checks that need access to a complete `Kinetics` objects, for example to retrieve information about reactant / product species. Also, the existing docstring for the `validate()` method shouldn't be removed.

2021-10-06 01:10 UTC, speth commented on include/cantera/kinetics/Reaction.h
> +    virtual void validate(Kinetics& kin);
You should only add a docstring to the base class's declaration, unless there is something different about this class's implementation that needs to be noted.

2021-10-06 01:10 UTC, speth commented on interfaces/cython/cantera/utils.pyx
> +    Cxx_make_cantera_warnings_fatal()
If the call to `Cxx_make_cantera_warnings_fatal` does as it says, what is the effect of the two calls to `filterwarnings`?

2021-10-06 01:10 UTC, speth commented on src/kinetics/InterfaceKinetics.cpp
> +    }
A few suggestions here, which also apply to the loop below.
```suggestion
    for (const auto& product : products) {
        size_t k = kineticsSpeciesIndex(product.first);
        double stoich = product.second;
        rxn_deltaH += m_grt[k] * stoich;
    }
```

2021-10-06 01:10 UTC, speth commented on src/kinetics/Reaction.cpp
> +    if (!allow_nonreactant_orders) {
I don't think the `validate(Kinetics&)` functions should duplicate checks done by the `validate()` (no args) functions, since you are keeping the latter functions in place. Anywhere you call the former, you also call the latter, but not necessarily the other way around, which I think was the reason @ischoegl suggested keeping them separate.

2021-10-06 01:10 UTC, speth commented on src/kinetics/Reaction.cpp
> +        doublereal original_P = kin.thermo().pressure();
Please don't use `doublereal` in any new code -- just write `double`.

2021-10-06 01:10 UTC, speth commented on src/kinetics/RxnRates.cpp
> +
Please revert changes that are just changing whitespace unrelated to your actual updates (ideally, by doing a fixup commit so that there isn't a commit adding this blank line and then another removing it).

2021-10-06 01:10 UTC, speth commented on src/kinetics/RxnRates.cpp
> +#include <math.h>
Are these includes needed? especially the latter seems suspect in light of #1110.

2021-10-06 01:10 UTC, speth commented on interfaces/cython/cantera/test/test_kinetics.py
> +                self.assertIn(msg, err_msg_list)
Check some of the other code that uses the `with self.assertRaises` construct for a nicer way of doing this.

2021-10-06 01:10 UTC, speth commented on include/cantera/kinetics/RxnRates.h
> +
Please avoid the extraneous whitespace changes.

2021-10-29 00:17 UTC, ischoegl requested changes
@12Chao ... thanks! As far as I can tell, you addressed most of @speth's comments. I also appreciate that you left the original `validate` in place, and implemented the `make_warnings_fatal` capability (which I believe will be useful). I noticed one instance where you may be able to leverage existing code as commented on below.

2021-10-29 00:17 UTC, ischoegl commented on include/cantera/kinetics/Kinetics.h
> +    virtual double reactionEnthalpy(const Composition& reactants, const Composition& products);
I believe this needs a docstring (if this function is needed at all). You may also want to include an empty line below.

2021-10-29 00:17 UTC, ischoegl commented on include/cantera/kinetics/Reaction.h
>      virtual void validate();
Per @speth’s comment, please leave the old docstring in place.

2021-10-29 00:17 UTC, ischoegl commented on interfaces/cython/cantera/examples/kinetics/blowers_masel.py
> +plt.title(r"$E_a$ vs. $\Delta{H}$ For O+H2<=>H+OH", y=1.1)
While this fixes the failing tests, @speth mentioned that this will resolve itself eventually (per #1132), so no action is needed here.

2021-10-29 00:17 UTC, ischoegl commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
Is there a way to use https://github.com/Cantera/cantera/blob/4570f3e6b0c7e964181ffb4ac2486b223cf80cde/include/cantera/kinetics/Kinetics.h#L392-L407
here? I have recently used 
```c++
bulk.getPartialMolarEnthalpies(m_grt.data());
getReactionDelta(m_grt.data(), dH.data());
```
(this used just one phase, with `dH` being a vector with the length of the number of reactions); I *believe* this may extend to multiple phases as long as the partial molar enthalpies are in the correct order. You mainly need to pick out the correct reaction index (while this calculates things for all reactions, it does not require lookup; it's a tradeoff, but as it is called during validation speed may not be as critical).

2021-10-29 00:24 UTC, ischoegl commented on src/kinetics/Reaction.cpp
> +                format_to(err_reactions,
Please use `fmt_append` here as there are some recent deprecation warnings triggered by `format_to` (see #1122). Also, there are a `doublereal` and a stray comment left a couple of lines above.
(there is a second instance of `format_to` on line 776 further above)

2021-10-29 02:28 UTC, 12Chao commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
Thanks for the review, I think I have addressed all the comments except this one. I would rather not change this part if it is not going to significantly speed things up

2021-10-29 02:41 UTC, ischoegl commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
@12Chao … no problem. I’ll leave the final approval to @speth. From my perspective, what you have here may be redundant code that could be avoided, as the same may be achieved with 5 lines of code within your validation functions. Another option would be to make this a local function within `Reaction.cpp`, as it is not being used elsewhere and I do not think that it is a good fit for `Kinetics`.

2021-10-29 02:41 UTC, ischoegl commented on interfaces/cython/cantera/examples/kinetics/blowers_masel.py
> +plt.title(r"$E_a$ vs. $\Delta{H}$ For O+H2<=>H+OH", y=1.1)
Rather than undoing the edit, could you just drop the previous commit? (05ab00102089752ab4a728544805c620ce33de6f)

2021-10-29 02:44 UTC, speth commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
I thought that the reason for adding the `deltaEnthalpy` function was because you need to be able to evaluate it for a reaction that isn't already part of the `Kinetics` object. Correct?

2021-10-29 02:49 UTC, ischoegl commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
@speth … valid point: in this case `getReactionDelta` does not apply. It still doesn’t quite fit with `Kinetics` and I believe it would be better to have it as a helper function within `Reaction`. But it’s not a major sticking point for me.

2021-10-29 02:52 UTC, ischoegl submitted a review, later dismissed

2021-10-29 03:20 UTC, speth commented on src/kinetics/Kinetics.cpp
> +    return rxn_deltaH;
I agree, it does feel like an awkward addition to the Kinetics class. Given that it relies almost entirely on public member functions of `Kinetics` (and the one exception, the use of `m_start`, can be fixed), I can see it more naturally being a member of the `Reaction` class.

2021-12-17 03:57 UTC, speth approved these changes

2021-12-17 03:59 UTC, speth commented
Thanks, @12Chao. To fix some merge conflicts that arose as a result of #1101 (I think), I ended up having to squash most of the commits here down into one.

2021-12-17 03:59 UTC, merged