fixed issue 992
Cantera/cantera pull request #1065
Opened 2021-06-22 20:21 UTC by jongyoonbae

**Changes proposed in this pull request**

- Fixed matlab documentation error for `entropy_mole` in the interface: unit changed from J/kg to J/mol-K.

**If applicable, fill in the issue number this pull request is fixing**

Closes #992

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2021-06-22 21:12 UTC, ischoegl requested changes
Thanks for the proposed fix! The hyphen here is consistent with `J/kg-K` in `entropy_mass.m`. However, could you double-check whether this is `kmol` or `mol` in MATLAB? (at least in Python, the corresponding method outputs the former, with units given as `J/kmol/K`)

2021-06-22 22:20 UTC, decaluwe commented
@ischoegl is correct - this is my fault, as @jongyoonbae was simply following my comment in the issue.

@jongyoonbae - if you edit this to be `J/kmol-K` you just have to add, commit, and then push back to your origin remote.  The new change will automatically be folded into your pull request.

2021-06-22 23:06 UTC, bryanwweber commented
@jongyoonbae rather than making a new commit, please use the `--amend` that I showed earlier to amend the existing commit and force push 😊 Thanks!

2021-06-23 14:22 UTC, jongyoonbae commented
I just did. Thank you for reviewing and commenting!

2021-06-23 14:23 UTC, ischoegl approved these changes

2021-06-23 14:43 UTC, ischoegl commented
@jongyoonbae ... Thank you for the fix!

2021-06-23 14:43 UTC, merged