Expose reaction rate coefficient units to python
Cantera/cantera pull request #1076
Opened 2021-07-17 20:52 UTC by ischoegl

**Changes proposed in this pull request**

- Shorten `Units::str()` output
- Create `std::string Reaction::rateCoeffUnits()` 
- Implement Python API for `Reaction.rate_coeff_units`

**If applicable, provide an example illustrating new features this pull request is introducing**

The new feature can be used as follows:
```
In [1]: import cantera as ct
   ...: gas = ct.Solution("gri30.yaml")
   ...: gas.reaction(0)
   ...:
Out[1]: <ThreeBodyReaction: 2 O + M <=> O2 + M>

In [2]: gas.reaction(0).rate_coeff_units
Out[2]: 'Units(1.0 kmol^-2 * m^6 * s^-1)'
```
**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

**Other thoughts**

The current implementation is relatively rudimentary. An alternative would be to implement an interface for `Units` in the Python API, and expose `Reaction::rate_units` directly. 

Comments are explicitly welcome.

2021-09-02 19:28 UTC, speth reviewed
I think making information about the units of reaction rate coefficients and phase standard concentrations available is a valuable addition to the Python interface, and a light interface to the `Units` class seems to serve this purpose, though I think there are currently a few quirks.

While I understand that the string representation of `Units` objects draws from the existing implementation (with some cleanup), I think that this output is kind of confusing when the units aren't in Cantera's base system, e.g. in the case of
```python
>>> ct.Units("mol/cm^3")
<Units(999.9999999999999 kmol / m^3) at 7f6ee85c93f0>
```
it's not really clear anymore that what this is intended to mean is that 1000 is the conversion factor between mol/cm^3 and kmol/m^3, rather than representing a particular quantity of 1000 kmol/m^3. This distinction gets even muddier with newly-allowed expressions like `Units("4 atm")`.

Assuming the goal here is just to provide unit information for these special cases where the dimensions vary in different instances, rather than presenting a full unit conversion capability (which I don't think we really want or need) I'd suggest that maybe Python `Units` objects should only be constructible in the default unit system, and that they could be represented without the leading 1.0 factor, e.g.
```python
>>> ct.Units("J/kmol")
<Units(kg * m^2 / kmol / s^2) at 7f6ef085c030>
```
and noting that practically, there's really no purpose for a user-constructed `Units` object.

I'm not clear on what the benefit of exposing the `UnitSystem` class here is. Is the purpose just to make information about the (completely fixed) default unit system available?

2021-09-02 22:05 UTC, ischoegl commented
@speth ... thanks for your comments!

> I think making information about the units of reaction rate coefficients and phase standard concentrations available is a valuable addition to the Python interface,  and a light interface to the `Units` class seems to serve this purpose, though I think there are currently a few quirks. [...] 
> 
> This distinction gets even muddier with newly-allowed expressions like `Units("4 atm")`.

Interesting observation. I definitely didn't have that in mind when I created the constructor! While I did code this up to finally wrap my head around the internal unit conversions (it *did* help), my main concern was to display what's done internally. 

> I'm not clear on what the benefit of exposing the `UnitSystem` class here is. Is the purpose just to make information about the (completely fixed) default unit system available?

Displaying the unit system was certainly one of my main concerns here (it would clear up things once and for all). But at the same time, it would serve a purpose to have it as a stand-alone object that is passed to `YamlWriter` (see 5751633), where `Units`with conversion factors do make some sense.

I agree that making the `Units` constructor less *useful* makes sense. This should be a relatively easy tweak to this PR.

2021-09-03 16:31 UTC, ischoegl commented
@speth ... I reworked some of the interfaces to make things more intuitive. For unit output, the factor is suppressed:
```
In [1]: import cantera as ct
   ...:    ...: gas = ct.Solution("gri30.yaml")
   ...:    ...: gas.reaction(0)
   ...: 
Out[1]: <ThreeBodyReaction: 2 O + M <=> O2 + M>

In [2]: gas.reaction(0).rate_coeff_units
Out[2]: <Units(m^6 / kmol^2 / s) at 7fd73eb86f30>

In [3]: gas.standard_concentration_units
Out[3]: <Units(kmol / m^3) at 7fd73eb86c90>
```

The `UnitSystem` now displays units automatically, and has a more intuitive `units` property (instead of the internally used C++ `defaults`, which originates in the pre-existing `Units::setDefaults`):
```
In [4]: ct.UnitSystem({"quantity": "mol", "length": "cm"}) # alternate unit system (e.g. input to YamlWriter)
Out[4]: 
<UnitSystem at 7fd7071f7030> with
{'activation-energy': 'J/mol',
 'current': 'A',
 'energy': 'J',
 'length': 'cm',
 'mass': 'kg',
 'pressure': 'Pa',
 'quantity': 'mol',
 'temperature': 'K',
 'time': 's'}

In [5]: ct.UnitSystem().units # default unit system
Out[5]: 
{'activation-energy': 'J/kmol',
 'current': 'A',
 'energy': 'J',
 'length': 'm',
 'mass': 'kg',
 'pressure': 'Pa',
 'quantity': 'kmol',
 'temperature': 'K',
 'time': 's'}
```

Finally, unit conversions are no longer enabled for the Python API:
```
In [6]: ct.Units('Pa')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-1f5f80910e54> in <module>()
----> 1 ct.Units('Pa')

/src/interfaces/cython/cantera/units.pyx in cantera._cantera.Units.__cinit__()
     18     def __cinit__(self, init=True):
     19         if init:
---> 20             raise ValueError("A 'Units' object should not be instantiated by itself.")
     21 
     22     def __repr__(self):

ValueError: A 'Units' object should not be instantiated by itself.
```

2021-09-10 03:14 UTC, speth requested changes
Thanks for the updates, @ischoegl, I think this is fairly close.

2021-09-10 03:14 UTC, speth commented on interfaces/cython/cantera/units.pyx
> +        if abs(self.units.factor() - 1.) < np.nextafter(0, 1):
Is there any case where this is different from a precise equality check of `self.units.factor() == 1`? `np.nextafter(0, 1)` gives a value of 5e-324, and if the `factor` is near 1, the smallest non-zero value that `abs(self.units.factor() - 1.)` can take on is ~2e-16.

2021-09-10 03:14 UTC, speth commented on include/cantera/base/Units.h
> +    //! conversion factor
If we're willing to be a little flexible on the output of `Units::str`, I think it would be all-around simpler to just have the result of `str` include the factor if it's non-unity, and skip it otherwise.

2021-09-10 03:14 UTC, speth commented on interfaces/cython/cantera/_cantera.pxd
> +        void setUnitSystem(CxxUnitSystem) except +translate_exception
I'm not sure if it actually matters to Cython, but I think this should be 
```suggestion
        void setUnitSystem(CxxUnitSystem&) except +translate_exception
```

2021-09-10 03:14 UTC, speth commented on interfaces/cython/cantera/units.pyx
> +    applying a factor of the Avogadro number or the gas constant where needed.
I think this docstring needs to be updated given this class won't be providing a lot of the functionality of its C++ counterpart.

2021-09-10 03:14 UTC, speth commented on src/base/Units.cpp
> +    {"cm", Units(.01, 0, 1, 0)},
What's the reason for adding this (and cal/mol) explicitly? Both are already handled by the existing conversion and prefix parsing.

2021-09-10 03:14 UTC, speth commented on test/general/test_units.cpp
> +    EXPECT_EQ(Units(Units(1., .5)).str(), "1.0 kg^0.5");
For a class that doesn't have/require a manually-implemented copy constructor, I'm having trouble imagining how these tests could possibly fail, and I think testing the copy constructor is superfluous.

2021-09-10 03:14 UTC, speth commented on test/general/test_units.cpp
> +    EXPECT_EQ(Units("0.001 m^3").str(), "0.001 m^3");
If we're not allowing leading numerical values as input for the `Units` class in Python, I don't think we should do it here either. I guess this comes back to the initial string representation of the `Units` class being a bit misleading and making it look more like a "quantity" that included a value and corresponding units.

2021-09-10 03:14 UTC, speth commented on src/base/Units.cpp
> +    }
The implementation of `UnitSystem::defaults()` seems more complex than necessary to me. Is there a reason not to just start with the internal unit system and update it with entries from `m_defaults`, I suppose with a special case for activation energies?

2021-09-10 16:15 UTC, ischoegl commented on interfaces/cython/cantera/units.pyx
> +        if abs(self.units.factor() - 1.) < np.nextafter(0, 1):
Not sure - I am just quite hesitant to use an exact comparison between `double`. In any case, I moved that check to C++ by adding a flag to the `Units` constructor as:
```C++
    //! Create an object with the specified dimensions
    //! @param force_unity  ensure that conversion factor is equal to one
    explicit Units(const std::string& name, bool force_unity=false);
```

2021-09-10 16:16 UTC, ischoegl commented on include/cantera/base/Units.h
> +    //! conversion factor
:+1: ... we now have:
```C++
    //! Provide a string representation of these Units that includes the
    //! conversion factor
    //! @param skip_unity  do not print '1' if conversion factor is equal to one
    std::string str(bool skip_unity=true) const;
```

2021-09-10 18:33 UTC, ischoegl commented on src/base/Units.cpp
> +    {"cm", Units(.01, 0, 1, 0)},
Removed - was left over from some intermediate testing.

2021-09-10 18:34 UTC, ischoegl commented on test/general/test_units.cpp
> +    EXPECT_EQ(Units("0.001 m^3").str(), "0.001 m^3");
Removed - I was indeed just following precedent but skipping unity makes sense.

2021-09-10 19:04 UTC, ischoegl commented on src/base/Units.cpp
> +    }
Ok. Let me walk through this as there may be some simplification I am overlooking. The internal unit system is the starting point in the `std::map<> units` variable that holds the various factors. From a generic view point, there are three scenarios here:
1. There is no conversion - ouput a regular unit string (line 345)
2. The unit can be converted to a known unit (line 349)
3. The unit has been overridden by `setDefaults`, which stores the original content in `m_defaults`.
Scenario (3) will always take care of (2) for non-unity factors, as the current class always stores a value in `m_defaults` when a non-standard factor is assigned. From that viewpoint. However, some of the units used are not standard units (e.g. `energy` and `pressure`). Commenting out lines 346-351 would produce:
```python
{'activation-energy': 'kg * m^2 / s^2/kmol',
 'current': 'A',
 'energy': 'kg * m^2 / s^2',
 'length': 'm',
 'mass': 'kg',
 'pressure': 'kg / m / s^2',
 'quantity': 'kmol',
 'temperature': 'K',
 'time': 's'}
```
so I believe the somewhat complex implementation is needed. I added more comments in `UnitSystem::defaults` to clarify.

2021-09-10 21:42 UTC, ischoegl commented
@speth ... thank you for the additional comments, which should be taken care  of. Per suggestion, all the formatting flags are now implemented in C++ rather than just for Python. The unit tests were easily taken care of and the documentation is updated. Regarding `Unittest::default` the direction I am taking requires the steps, as I am starting from the factors and work my way from there.

2021-09-15 20:11 UTC, ischoegl commented
@speth ... let me know if there's anything else. From my side, I believe this is ready to be merged.

2021-09-15 23:58 UTC, speth commented on src/base/Units.cpp
> +    }
I went ahead and just implemented the alternative version of this that I had in mind in this commit: https://github.com/speth/cantera/commit/c92663253a179acc15a13341421fff6236bf49b1.

You're right that it does presume that `m_defaults` is consistent with the `m_whatever_factor` variables, but there are other features that rely on that correspondence -- namely, handling of nested `units` directives -- so this does get tested, at least implicitly.

Energy and pressure should be treated independent of the fact that they are composed of base units -- the behavior that Cantera implements is that just changing the units of mass, for example, does not automatically change the units of pressure or energy. However, the default for activation energy does depend on the energy and quantity units, and that does create a special case.

2021-09-16 02:24 UTC, ischoegl commented on src/base/Units.cpp
> +    }
:+1: adopted. Thanks for claryfing!

2021-09-16 02:26 UTC, ischoegl commented
@speth ... thanks for clarifying! I simply cherry-picked your suggestion as it's indeed simpler (I was apparently too focused on the numeric factors ...).

2021-09-16 14:40 UTC, speth approved these changes
Thanks, @ischoegl, I think that wraps this all up.

2021-09-16 14:40 UTC, merged