Small fixes and improvements
Cantera/cantera pull request #1088
Opened 2021-08-22 14:56 UTC by ischoegl

**Changes proposed in this pull request**

This PR contains several minor updates that fix small issues accumulated over several PR's (or addresses inconsistencies that were left over from the 2.5 code base). 

- Make `Plog` interface consistent: existing code mixed `std::vector<std::pair>` and `std::multimap` (deprecate `std::multimap` versions)
- Make `Chebyshev` interface consistent: existing code mixed `Array2D` and `vector_fp` (deprecate `vector_fp` versions)
- Update internal `Chebyshev` routines to consistently use column major arrays
- Fix warnings in compilation and test suite
- Clarify docstring for SCons `legacy_rate_constants`
- Allow for custom C++ `NotImplementedError` messages

**If applicable, provide an example illustrating new features this pull request is introducing**

N/A (changes are internal only)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2021-08-24 01:34 UTC, ischoegl commented
@speth ... as #1081 was starting to exceed 2k lines, I decided to push a portion that include relevant changes to the API first. In addition, there is some streamlining of code that arose in the context of #1051.

2021-09-03 21:22 UTC, speth requested changes
I like the addition of the option to use sparse matrices for the stoichiometric coefficients, but I think there are a few tweaks needed to get it to make full use of the sparsity.

The one change here that I don't really understand is to the data structure used to initialize `Plog` objects.

2021-09-03 21:22 UTC, speth commented on include/cantera/cython/wrappers.h
> +    int* rows, int* cols, double* data, size_t dim)
`dim` is kind of a confusing name for the length of the output arrays - maybe something along the lines of `length` or `out_len` would be more clear?

2021-09-03 21:22 UTC, speth commented on src/kinetics/RxnRates.cpp
> +    }
I don't understand the motivation for changing the input data for `Plog` rates from `multimap<double, Arrhenius>` to `vector<pair<double, Arrhenius>>`. What is the benefit?

At a minimum, the method for adding rates here relies on them being sorted from lowest pressure to highest pressure, which occurs automatically for `multimap`, but not with `vector<pair>`. If rates in an input file are provided in a different order, the rates will now be calculated incorrectly.

2021-09-03 21:22 UTC, speth commented on src/kinetics/RxnRates.cpp
> +    m_coeffs = Array2D(coeffs);
```suggestion
    m_coeffs = coeffs;
```

2021-09-03 21:22 UTC, speth commented on src/kinetics/RxnRates.cpp
> +    nT_ = coeffs.nRows();
At this point, I think the `nP_` and `nT_` variables could just be removed in favor of `m_coeffs.nColumns()` and `m_coeffs.nRows()`.

2021-09-03 21:22 UTC, speth commented on include/cantera/numerics/eigen_defs.h
> +#endif
If we continue to expand the use of Eigen through Cantera, I think it might be better to keep separate "wrapper" headers for `eigen_dense` and `eigen_sparse`, since there will probably be a lot more source files making use of the dense arrays than the sparse arrays, and including the sparse stuff unnecessarily will slow down compilation.

2021-09-03 21:22 UTC, speth commented on interfaces/cython/cantera/kinetics.pyx
> +
What's wrong with the existing name? We use the abbreviation `coeffs` an awful lot. And this still leaves the probably less common `stoich` abbreviation (not that I'd really suggest `reactant_stoichiometric_coefficients` as the name).

2021-09-03 21:22 UTC, speth commented on interfaces/cython/cantera/kinetics.pyx
> +    return data[:size], tuple([rows[:size], cols[:size]])
As used, I think this is losing much of the benefit of using sparse matrices -- this is allocating enough space for a fully dense array (times two, if `c_int` is a 32-bit type).

I think your alternative suggestion of using a few methods of `Eigen::SparseMatrix` in Cython would allow you to avoid this. I suspect it probably ends up being simpler than this structure paralleling the interface that we use for functions that "return" arrays via their input arguments, since you can just write a Cython function that returns a `scipy.sparse` matrix given an `Eigen::SparseMatrix`. Then the implementation of `reactant_stoich_coeffs` is just `return get_sparse(self.reactantStoichCoeffs())` without having to fiddle around with any macros.

2021-09-03 22:53 UTC, ischoegl commented
@speth ... thank you for the comments. I'll respond to some of your points right away, and should be able to get back to this before long.

2021-09-03 22:56 UTC, ischoegl commented on interfaces/cython/cantera/kinetics.pyx
> +    return data[:size], tuple([rows[:size], cols[:size]])
I actually spent some time trying to expose some `Eigen` classes within `_cantera.pxd`, but gave up (I had the C preprocessors already working). I'll give it another shot, but may require some input (specifically, the `Eigen::SparseMatrix<double>::InnerIterator` gave me endless grief).

2021-09-03 22:56 UTC, ischoegl commented on include/cantera/cython/wrappers.h
> +    int* rows, int* cols, double* data, size_t dim)
Would be moot if I can get the Cython route to work.

2021-09-03 22:59 UTC, ischoegl commented on src/kinetics/RxnRates.cpp
> +    }
The reason here was that my goal was to create symmetric `set/getParameters` argument types. Specifically, the import via `AnyMap` uses `vector`. I wasn't aware of the sorting aspect, and will certainly address.

2021-09-03 23:02 UTC, ischoegl commented on interfaces/cython/cantera/kinetics.pyx
> +
I switched from a method to a property, which I believe is more consistent with the Python API. The intent here was to reduce the churn by just renaming. Alternatives would be to use  `product_stoichiometric_coeffs`, the usual two-step deprecation, or to leave the method alone.

2021-09-03 23:10 UTC, ischoegl commented on src/kinetics/RxnRates.cpp
> +    m_coeffs = Array2D(coeffs);
The alternative to `Array2D` here would be to go to `Eigen::MatrixXd` ... thoughts? The two matrix classes are somewhat redundant, but interfacing `Eigen` with various language API's may be somewhat thorny.

2021-09-04 23:56 UTC, ischoegl commented on src/kinetics/RxnRates.cpp
> +    nT_ = coeffs.nRows();
There was actually quite a bit of clutter left - I ended up making everything even more consistent - `Tmin`/`Tmax` and `Pmin`/`Pmax` are replaced by `temperatureRange` and `pressureRange`, respectively. And new constructors use `std::pair<double,double>` to better reflect the `AnyMap` construction route.

2021-09-04 23:57 UTC, ischoegl commented on interfaces/cython/cantera/kinetics.pyx
> +    return data[:size], tuple([rows[:size], cols[:size]])
I was able to resolve this by keeping `sparseComponents` as a C++ function and only exposing the `Eigen::SparseMatrix<double>` ... that way allocations can be done with exact size information.

2021-09-05 01:05 UTC, ischoegl commented on interfaces/cython/cantera/kinetics.pyx
> +
I ended up doing the usual - name the new property `Kinetics.product_stoich_coeffs3` for transitional behavior.

2021-09-05 14:51 UTC, ischoegl commented on src/kinetics/RxnRates.cpp
> +    }
The lack of symmetry was actually for `Plog::setup` and `Plog::rates`, where the former uses `multimap` and the latter uses `vector<pair<>>`. I had opted for `vector` as it was more similar to the `AnyMap` route, but didn't realize that there was a benefit to using `multimap`.

I reversed the old change and instead implemented `Plog::setRates`/`Plog::getRates` that both use `multimap`, and deprecated the old `Plog::setup` and `Plog::rates` in favor of the more consistent setters/getters.

2021-09-05 15:07 UTC, ischoegl commented
@speth ... thanks again for the feedback (and I'm happy you liked the sparse coefficient interface, despite the naming squabbles).

I believe I took care of everything. The interface to `Eigen::SparseMatrix` no longer uses excessive memory and the `Plog`/`multimap` issue is taken care of. Regarding the Python coefficient getter, I opted for a transitional name, so the old names won't change long-term.

2021-09-13 17:30 UTC, ischoegl commented
:tada: ... finally found something that will help exposing sparse matrices without copying ... it does look like [scipy.sparse.csr_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) can be initialized from the data structure used by [_compressed_ sparse matrices in`Eigen`](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html) 
> csr_matrix((data, indices, indptr), [shape=(M, N)])
>
>    is the standard CSR representation where the column indices for row i are stored in `indices[indptr[i]:indptr[i+1]]` and their corresponding values are stored in `data[indptr[i]:indptr[i+1]]`. If the shape parameter is not supplied, the matrix dimensions are inferred from the index arrays.

2021-09-15 03:37 UTC, ischoegl commented
Switching to CSC (from COO) format in `scipy.sparse` leverages the internal `Eigen` storage order, and has some impact on performance:
```
In [2]: gas = ct.Solution("gri30.yaml")
   ...: dense = gas.reactant_stoich_coeffs3

In [3]: %timeit gas.reactant_stoich_coeffs3
10000 loops, best of 3: 64.3 us per loop

In [4]: ct.use_sparse()

In [5]: sparse = gas.reactant_stoich_coeffs3
   ...: sparse
Out[5]: 
<53x325 sparse matrix of type '<class 'numpy.float64'>'
	with 626 stored elements in Compressed Sparse Column format>

In [6]: (sparse == dense).all()
Out[6]: True

In [7]: %timeit gas.reactant_stoich_coeffs3
The slowest run took 4.78 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 48 us per loop

In [8]: %timeit gas.reactant_stoich_coeffs3_prev # previous implementation outputting COO matrix
The slowest run took 9.96 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 61.6 us per loop
```
These tests show a 20% speed improvement with CSC (*not* a major saving); CSC is, however, better suited for matrix-vector products, so the switch makes sense overall.

2021-09-16 04:42 UTC, speth requested changes
Thanks for the updates, @ischoegl. I'm glad to see the reasonably efficient interface for exposing Eigen's sparse matrices to Python. I think that bodes well for some of the other things that I expect are on the horizon like Jacobians.

The change from `Plog::setup` to `Plog::setRates` makes sense, although I think the new function name implies that you could call it again to replace the existing rates and the current implementation doesn't support that as it leaves the existing contents of `rates_` and `pressures_` in tact.

I don't really understand the motivation for packing Chebyshev rate Tmin/Tmax and Pmin/Pmax into `std::pair`. All the extra use of `std::make_pair` and `foo.first`/`foo.second` that's now required doesn't really seem like an improvement over the old interface. In Python, on the other hand, implicit tuple packing/unpacking is clean and idiomatic, so I think that's a reasonable API change.

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/StoichManager.h
> +        m_stoichCoeffs.setFromTriplets(m_coeffList.begin(), m_coeffList.end());
While reading some of the Eigen documentation while trying to understand how this works, I noticed that `setFromTriplets` says the existing contents are destroyed, so I think calling `setZero` is unnecessary. It also says the result is a compressed sparse matrix, so I think the following call to `makeCompressed` is also unnecessary.

2021-09-16 04:42 UTC, speth commented on include/cantera/cython/wrappers.h
> +    }
I think checking `IsRowMajor` is unnecessary here -- for the matrix to be row major, the type would have to be `Eigen::SparseMatrix<double,RowMajor>`.

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/StoichManager.h
> +    std::vector<Eigen::Triplet<double>> m_coeffList;
```suggestion
    SparseTriplets m_coeffList;
```
(or eliminate the typedef in `eigen_sparse.h` as it's otherwise unused)

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/Kinetics.h
> +    }
For these one liners, I think the following style is fine (and consistent with the rest of this file):
```suggestion
    Eigen::SparseMatrix<double> reactantStoichCoeffs() const {
        return m_reactantStoich.stoichCoeffs();
    }
```

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/RxnRates.h
>      }
I think there is enough of a semantic difference between "number of points in the pressure dimension" and "number of columns in the coefficient matrix" to keep this function (and `nTemperature`) as well.

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/RxnRates.h
> +    //! pressure dimensions corresponding to rows and columns, respecitively.
```suggestion
    //! pressure dimensions corresponding to rows and columns, respectively.
```

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/RxnRates.h
> +     */
Is the intention to remove `rates`, or change it to match the updated return type of `getRates`? I think just `rates` should be the preferred name for this getter (since it actually _returns_ the property in question), but I understand the need for a transitional name.

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/StoichManager.h
> +            m_coeffList.push_back(Eigen::Triplet<double>(k[n], rxn, stoich[n]));
This is a good place for `emplace_back`:
```suggestion
            m_coeffList.emplace_back(k[n], rxn, stoich[n]);
```

2021-09-16 04:42 UTC, speth commented on interfaces/cython/cantera/_cantera.pxd
> +        double* valuePtr()
I don't think these are actually used within any of the `.pyx` files.

2021-09-16 04:42 UTC, speth commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
I'm struggling a little with this function name. At least to me, it implies that further modification of the object is not possible, but that's not the case. I'd say that `initialize` is almost closer to the right term, and is one which we use in the reactor classes for somewhat similar purposes.

2021-09-16 19:22 UTC, ischoegl commented on include/cantera/kinetics/Kinetics.h
> +    }
:+1: ... I was under the impression that for methods the initial `{` should preferably be on its own line and hence started to apply this whenever touching code. I (personally) prefer what you proposed anyways and will adopt. 

So ... the initial `{` will only be put on its own line if the argument list doesn't fit on the first line?

2021-09-16 19:51 UTC, ischoegl commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
The reason here is that `Kinetics::init()` already exists - I picked `Kinetics::finalizeSetup()` to clearly differentiate. The two methods need to be run _before_ and _after_ adding reactions, respectively, and thus serve as bookends of the setup process.

2021-09-16 20:00 UTC, ischoegl commented on include/cantera/kinetics/RxnRates.h
> +     */
This is indeed the intent. I'll change the text of the deprecation warning.

2021-09-16 21:33 UTC, ischoegl commented
@speth ... thank you for your comments

> The change from `Plog::setup` to `Plog::setRates` makes sense, although I think the new function name implies that you could call it again to replace the existing rates and the current implementation doesn't support that as it leaves the existing contents of `rates_` and `pressures_` in tact.

Good catch! Some of the renaming here pre-empts #1051 (which is currently on hold), so it will be possible to change that eventually.

> I don't really understand the motivation for packing `Chebyshev` rate Tmin/Tmax and Pmin/Pmax into `std::pair`. All the extra use of `std::make_pair` and `foo.first`/`foo.second` that's now required doesn't really seem like an improvement over the old interface. In Python, on the other hand, implicit tuple packing/unpacking is clean and idiomatic, so I think that's a reasonable API change.

I partially reverted those changes to C++. I guess I *wanted* to make things as similar as possible for YAML / Python and C++, but for the latter I agree that the resulting API change wasn't great. The updated Python API remains of course.

Regarding `Kinetics::finalizeSetup()` I see your point, but there is indeed a need to call it at a different time than `Kinetics::init()` ... let me know if you can think of a better name, but `initialize` would be imho too confusing.

2021-09-17 00:44 UTC, speth commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
Sorry, I forgot about `Kinetics::init`. That would be confusing. Maybe `completeSetup`?

2021-09-17 01:47 UTC, ischoegl commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
I think complete still has the connotation of being completely done. How about `reset`?

2021-09-17 02:21 UTC, speth commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
`reset` sounds like it's going to remove something that's already there. Maybe by analogy with `resizeSpecies`, we could have `resizeReactions`, although the use case is slightly different?

2021-09-17 03:07 UTC, ischoegl commented on include/cantera/kinetics/Kinetics.h
> +    virtual void finalizeSetup();
:+1: I think `resizeReactions` is an adequate description. Thanks for the suggestion!

2021-09-17 03:21 UTC, ischoegl commented
@speth ... after settling on `Kinetics::resizeReactions` (and `StoichManagerN::resizeCoeffs`), I believe everything is taken care of and this should be ready to be merged. Thank for the review and the suggestions!

2021-09-17 15:33 UTC, speth approved these changes
Thanks, @ischoegl! This looks good to me.

2021-09-17 15:33 UTC, merged

2021-09-17 16:21 UTC, ischoegl commented
@speth ... thanks again for the review. Now that this is merged, I will post a new PR wrapping up `GasKinetics` (much of this is done, but I'll have to clean up some of the commit history). 

None of my other pending PR's are close to being merged, as most need to be rebased at this point.