Package rpm
Cantera/cantera pull request #1116
Opened 2021-10-09 12:42 UTC by mefuller

**Changes proposed in this pull request**

- Update `SConstruct` to find system installations of `sundials` and `eigen`
- Update `include/cantera/numerics/eigen_sparse.h` to reflect system file location
- Tests currently fail due to changes made in `SConstruct` for `sundials`

Closes #1115  (maybe - verification that these changes are appropriate on other OS required)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2021-10-10 22:04 UTC, bryanwweber commented on site_scons/buildutils.py
> +from collections.abc import Mapping
Now that you've confirmed the fix works, I think `from collections.abc import Mapping as MappingABC` would be more clear. Also need to confirm that this doesn't generate any warnings down to Python 3.6.

2021-10-11 21:32 UTC, speth reviewed
I think this solution works well for most cases where the Eigen headers have been installed by a system package manager, but I think it complicates things in cases where a user has downloaded the Eigen tarball and extracted it themselves to a different location, where the `Eigen` directory won't necessarily be a subdirectory of a directory named `eigen3`.

I'm also not sure whether placing the `eigen3` directory as a subdirectory of a system include directory (such as `/usr/include`) is universal or not. It seems to be the case for Ubuntu/Debian, Fedora/Redhat, and conda, but I don't know about other Linux distros or package managers.

What I would suggest is having SCons check for both `Eigen/Dense` and `eigen3/Eigen/Dense` and use that to set another variable in `config.h` so you can select between them.

2021-10-12 09:05 UTC, mefuller commented
thanks @speth - I'll work on implementing that check and variable in the coming week and hopefully have a ready PR soon

2021-10-14 08:03 UTC, mefuller commented
the implementation of the switch for the location of Eigen is not as clean as I would like, but I was having some difficulty getting the compiler directive formatted properly

2021-10-20 07:17 UTC, mefuller commented
@speth @bryanwweber  I'd like to solicit comments and suggestions on how I implemented my compiler switch. I'm not really happy with how it looks, but I believe it works.

2021-10-20 14:41 UTC, speth requested changes
Thanks, Mark. I think this does the job pretty well. I had one suggestion for simplifying it a bit, as mentioned below.

One small formatting request (channeling @bryanwweber) is that in all new or changed lines of Python code, you should use double quotes instead of single quotes.

2021-10-20 14:41 UTC, speth commented on SConstruct
> +        env['system_eigen3'] = False
I think you only need one new variable, since we're ultimately only going to include Eigen from one location. I might suggest slightly different names as well -- we're always using Eigen 3, so these are a bit confusing. Maybe just `env["system_eigen_prefixed"] = False` in this case, with `CT_SYSTEM_EIGEN_PREFIXED` as the corresponding preprocessor define.

Also, for efficiency, you might want to check for `eigen3/Eigen/Dense` before plain `Eigen/Dense`, since we seem to expect the former to be more common than the latter.

2021-10-20 14:41 UTC, speth commented on SConstruct
> +# eigen_include = '<Eigen/Core>' if env['system_eigen'] else '"../ext/eigen/Eigen/Core"'
Delete this line rather than commenting it out.

2021-10-20 14:57 UTC, mefuller commented on SConstruct
> +        env['system_eigen3'] = False
@speth so I'm clearly misunderstanding something because I can't understand why the compiler now looks in the wrong place during build
```
INFO: Generating build/src/config.h.build with the following settings:
    CANTERA_SHORT_VERSION               "2.6"
    CANTERA_VERSION                     "2.6.0a3"
    CT_LEGACY_RATE_CONSTANTS            1
    CT_SUNDIALS_USE_LAPACK              0
    CT_SUNDIALS_VERSION                 57
    CT_USE_DEMANGLE                     1
    CT_USE_SYSTEM_EIGEN                 1
    CT_USE_SYSTEM_EIGEN_PREFIXED        1
    CT_USE_SYSTEM_FMT                   1
    CT_USE_SYSTEM_YAMLCPP               1
    FTN_TRAILING_UNDERSCORE             1
    LAPACK_FTN_STRING_LEN_AT_END        1
    LAPACK_FTN_TRAILING_UNDERSCORE      1
    LAPACK_NAMES_LOWERCASE              1
    CT_USE_LAPACK                       *undefined*
    DARWIN                              *undefined*
    NEEDS_GENERIC_TEMPL_STATIC_DECL     *undefined*
    SOLARIS                             *undefined*
...
In file included from include/cantera/kinetics/StoichManager.h:11,
                 from include/cantera/kinetics/Kinetics.h:14,
                 from include/cantera/kinetics/KineticsFactory.h:11,
                 from src/fortran/fct.cpp:14:
include/cantera/numerics/eigen_sparse.h:12:10: fatal error: Eigen/Dense: No such file or directory
   12 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
compilation terminated.
scons: *** [build/src/fortran/fct.os] Error 1
scons: building terminated because of errors.
```

2021-10-20 16:10 UTC, speth commented on include/cantera/numerics/eigen_sparse.h
>  #endif
Once you get these multiply-nested preprocessor statements, I like to start indenting each level, e.g. as done in `src/numerics/CVodesIntegrator.cpp`.

2021-10-20 16:16 UTC, speth commented on SConstruct
> +        env['system_eigen3'] = False
You need to add a line to `include/cantera/base/config.h.in` for the new preprocessor variable.

2021-10-21 08:17 UTC, mefuller commented
@speth Thanks again for all your help.
This PR should now be all set

2021-10-21 11:09 UTC, bryanwweber commented on SConstruct
> +    if conf.CheckCXXHeader('eigen3/Eigen/Dense', '<>'):
As @speth mentioned, please use double quotes `"` in all Python code. SCons scripts count too 😊

2021-10-22 08:36 UTC, mefuller commented on SConstruct
> +    if conf.CheckCXXHeader('eigen3/Eigen/Dense', '<>'):
Done

2021-10-22 12:59 UTC, bryanwweber commented on SConstruct
> +    if conf.CheckCXXHeader('eigen3/Eigen/Dense', '<>'):
Hi @mefuller, I'm sorry I wasn't clear 😕 I only meant for the lines you were already changing, not everywhere in the file. Changes across so many lines end up causing lots of merge conflicts for other folks with changes in this file on their branches.

2021-10-22 14:40 UTC, mefuller commented on SConstruct
> +    if conf.CheckCXXHeader('eigen3/Eigen/Dense', '<>'):
@bryanwweber ok, I made the quote mark changes now only to the"eigen" components

2021-10-23 19:51 UTC, speth approved these changes
Looks good to me. Thanks, @mefuller!

2021-10-23 19:52 UTC, merged