Improve YAML formatting
Cantera/cantera pull request #1133
Opened 2021-10-26 03:13 UTC by ischoegl

Leverage `fmt::format` to appropriately round values.

**Changes proposed in this pull request**

- Update rounding rules for `double` emitter
- Implement multi-line strings

**If applicable, fill in the issue number this pull request is fixing**

Closes #1128 (together with improved formatting documentation introduced in #1112)

**If applicable, provide an example illustrating new features this pull request is introducing**

_(A) Rounding of floating point values_

Ensure that floating point values are properly rounded, e.g.
```
<       - {P: 10.0, A: 1.2866e+47, b: -9.0246, Ea: 2.00263761648836e+04}
<       - {P: 100.0, A: 5.9632e+56, b: -11.529, Ea: 2.64691461742217e+04}
---
>       - {P: 9.99999999999999, A: 1.2866e+47, b: -9.0246,
>       Ea: 2.00263761648836e+04}
>       - {P: 99.9999999999999, A: 5.9632e+56, b: -11.529,
>       Ea: 2.64691461742217e+04}
```

_(B) Serialization of lines spanning multiple lines (aka 'Literal' ~or folded strings~)_

Strings that contain `'\n'` are written as multiple lines, e.g. `"spam\nand\neggs"` becomes:
```yaml
literal-string: |
  spam
  and
  eggs
```
which leverages `YAML::Literal`. At the moment, there doesn't appear to be a way to skip the trailing `\n` in the equivalent string that is written (i.e. there is no `|-` rather than `|` in `yaml-cpp` for the first line as far as I can tell).

FWIW, here's a [demo](https://yaml-multiline.info/) illustrating different literal/folded multiline string versions in YAML. `yaml-cpp` appears to only support one version.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2021-11-18 03:21 UTC, speth requested changes
Thanks, @ischoegl. I think these changes to the output formatting generally look very good. However, I did notice that there were a few cases where the output is now outputting trailing zeros in some circumstances, and I don't think this is expected based on the comments in the `formatDouble` method. A couple of examples can be seen in the test suite. In `test/work/generated-ptcombust.yaml`, I see:
```yaml
    site-density: 1.629771953878800e+13
```
and in `test/work/generated-h2o2-from-xml.yaml`, we have:
```yaml
    rate-constant: {A: 3.57e+04, b: 2.4, Ea: -1061.79321568240}
```
I'm not sure exactly how this is happening, but perhaps it's worth a few tests that this formatter is actually generating the desired output (recognizing that the lack of tests for this method is an oversight on my fault to begin with 😬).

2021-11-18 03:21 UTC, speth commented on src/base/AnyMap.cpp
> +void emitString(YAML::Emitter& out, const string str0) {
```suggestion
void emitString(YAML::Emitter& out, const string& str0) {
```

2021-11-19 22:26 UTC, ischoegl commented
@speth ... thank you for the review!

Interesting find about the double trailing zeros. It is not entirely surprising as I was very careful to not round and inadvertently introduce error. I added the following explanation to `formatDouble`:
```C++
string formatDouble(double x, long int precision)
{
    // This function ensures that trailing zeros resulting from round-off error
    // are removed. Values are only rounded if at least three digits are removed,
    // or the displayed value has multiple trailing zeros.
```
This choice is partially aesthetic (e.g. long blocks of values), but also tries to stay on the safe side while catching compounded round-off error (not just trailing `001`'s and `999`'s).

I also added the requested unit test. It's somewhat tricky as the exact number representation may be impacted by the architecture, but I _believe_ what I implemented should have the desired output. One curious finding was that removing every trailing zero breaks the test suite (i.e. removing a single zero may change the actual value!). Removing double trailing zeros appears to be safe.

2021-11-20 01:59 UTC, speth approved these changes
Thank you, @ischoegl. This looks good to me.

2021-11-20 02:00 UTC, merged