Resolve Yaml paper cuts
Cantera/cantera pull request #1179
Opened 2022-01-19 17:45 UTC by ischoegl

**Changes proposed in this pull request**

This PR aims to address some remaining points raised in #1053

- Add `Species.from_dict` creation (in analogy to `Reaction.from_dict`)
- Add ability to pass YAML syntax to `anymap_from_dict`
- Address some YAML code formatting in Sphinx

**If applicable, fill in the issue number this pull request is fixing**

Closes #1053

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2022-01-27 18:53 UTC, ischoegl commented
Pre-emptively dropping commits that will clash with #1183.

2022-02-04 21:24 UTC, speth requested changes
I would prefer to drop the implicit YAML parsing that this introduces. Other than that, what's implemented here looks fine.

2022-02-04 21:24 UTC, speth commented on interfaces/cython/cantera/utils.pyx
> +            v = stringify(item)
How often would you really want to use the mixed syntax that this allows? Especially keeping in mind the existing support for specifying compositions as strings, which is probably the most common case. I don't think it's great that what I think must be the far more common case here ends up throwing an exception.

2022-02-04 23:12 UTC, ischoegl commented
> I would prefer to drop the implicit YAML parsing that this introduces. 

@speth ... no problem: dropped. Also made some of the unit test method names more pythonic (i.e. switched to snake_case), but nothing else changed.

2022-02-04 23:13 UTC, ischoegl commented on interfaces/cython/cantera/utils.pyx
> +            v = stringify(item)
True. As this is not an important feature, it's better to just drop it.

2022-02-04 23:26 UTC, speth approved these changes
Looks good to me. Thanks, @ischoegl!

2022-02-04 23:57 UTC, merged