Flame restart and initial guess examples and fix issue #1288
Cantera/cantera pull request #1293
Opened 2022-05-26 19:15 UTC by rwest

**Changes proposed in this pull request**

- Allow `set_initial_guess` to receive a Pandas DataFrame object, as documented.
- Provide an example file with lots of examples of ways to save and load flame solutions and initial guesses

**If applicable, fill in the issue number this pull request is fixing**

Closes #1288

**If applicable, provide an example illustrating new features this pull request is introducing**

Most of the pull request is providing examples (including one of the fixed bug).

**Checklist**

I'll work on this checklist next.... (probably need to rebase to tidy up my commit messages etc.)

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2022-05-26 22:03 UTC, ischoegl reviewed
@rwest ... thanks for looking into this! Restarts and improved file IO from `SolutionArray` (and `FlameBase`) were among the first things I implemented when I started contributing for 2.5.1 (I had used restarts from HDF extensively in the past). The `pandas` issue slipped through, which should have been secured by unit tests (which were never added). Fwiw, `pandas` itself was just a vehicle to write an earlier HDF version that never made it into a release, but it was kept around ...

While this PR may not be fully developed (some catch blocks look like this is still work in progress), I added a couple of comments. Also, several of your tests read like unit tests ... let me know if you have questions ...

2022-05-26 22:03 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +Requires: cantera >= 2.6.1
```suggestion
Requires: cantera >= 3.0
```
I hope we can avoid 2.6.1

2022-05-26 22:03 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +Keywords: combustion, 1D flow, flame speed, premixed flame
Keywords need to match a list kept in `example-keywords.txt` in the `doc` folder.

2022-05-26 22:03 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +assert np.allclose(f.X[f.gas.species_index('CH4')], f2.X[f2.gas.species_index('CH4')] )
This is rather repetitive - can this be done using a 
```python
def compare_flames(f1, f2):
   [...]
```
function?

2022-05-26 22:03 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +# and then pass the SolutionArray to the set_initial_guess method.
Should be removed - by the time this is merged, the comment will be outdated.

2022-05-26 22:03 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +    print("Wow, this works now? cool")
:joy: ... I guess I started to review this too early?

2022-05-31 13:15 UTC, rwest commented
Thanks for the comments @ischoegl. I think I've addressed them (and tidied some other things up on the rebase).

2022-06-01 15:10 UTC, ischoegl requested changes
@rwest ... thank you for updating. To follow up on my initial comments, I have a couple of more substantive suggestions.

I don't think that the example needs to check / demonstrate equivalence of restored solutions, as there are already unit tests for that purpose (I linked those that do exist - pandas is the main one that is missing). On the other hand, the pruning checks are very informative - I think it would be nice to just play around with tolerances, pruning, and refine criteria as these are not necessarily well understood by users, while giving ample opportunity to demonstrate file I/O.

Fwiw, there's another relevant example that is a little more advanced - see [diffusion_flame_batch.py](https://github.com/Cantera/cantera/blob/main/interfaces/cython/cantera/examples/onedim/diffusion_flame_batch.py). I think a simpler example like the one you are proposing here is a great addition.

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +print("mixture-averaged flame speed = {:7f} m/s\n".format(f.velocity[0]))
New examples should use f-strings instead
```suggestion
print(f"mixture-averaged flame speed = {f.velocity[0]:7f} m/s\n")
```

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +gas.TPX = Tin, p, reactants # must set the gas T back to the inlet before making new flame
Line exceeds 88 characters (see CONTRIBUTING.md). There are a couple of other lines that do also.

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +assert np.allclose(f.X.max(axis=1), f2.X.max(axis=1), rtol=0.2, atol=1e-20), "Max mole fractions not within 20%"
It may be better to just produce string output comparing original and new results for velocity and major species.

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +    compare_flames(f, f2)
I think there are two preferred options to kicking the can down the road:

1. fix the documentation and remove this example
2. implement the import

I'm in favor of (1), as there already is a dedicated loader for HDF.

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +    assert np.allclose(f1.X[f.gas.species_index("CH4")], f2.X[f2.gas.species_index("CH4")] ), "Methane profile is different"
This is in essence reproducing unit tests: see
https://github.com/Cantera/cantera/blob/8fbb4bcd9ff5f74f2c2f19eb241e27654e6a5c22/interfaces/cython/cantera/test/test_onedim.py#L666-L671
as well as
https://github.com/Cantera/cantera/blob/8fbb4bcd9ff5f74f2c2f19eb241e27654e6a5c22/interfaces/cython/cantera/test/test_onedim.py#L683-L693
and
https://github.com/Cantera/cantera/blob/8fbb4bcd9ff5f74f2c2f19eb241e27654e6a5c22/interfaces/cython/cantera/test/test_onedim.py#L537-L579

2022-06-01 15:10 UTC, ischoegl commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +    print("Couldn't load yaml solution, so starting from scratch")
Would it make more sense to always recreate the initial solution, and save that solution to YAML, CSV, and HDF immediately? That way the different output options are all used in one place, making things a lot more intuitive for the user.

2022-06-09 03:18 UTC, rwest commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +    compare_flames(f, f2)
I did (1) in https://github.com/Cantera/cantera/pull/1293/commits/07870630b4e26d5399380e69610d00a2b36399ca

2022-06-09 03:18 UTC, rwest commented on interfaces/cython/cantera/examples/onedim/flame_initial_guess.py
> +assert np.allclose(f.X.max(axis=1), f2.X.max(axis=1), rtol=0.2, atol=1e-20), "Max mole fractions not within 20%"
ok

2022-06-09 03:19 UTC, rwest commented
I think I have addressed all @ischoegl's comments and suggestions in the last 2 commits.

2022-06-09 13:19 UTC, ischoegl commented
@rwest ... thanks for the updates! I ended up looking into the HDF failure, which was much easier to fix than anticipated - there was a missing `subgroup` kwarg identifying the flame domain (a2f2fff319cb4015e0dd2d86c1389facf7ead8b4). Also, the HDF cases require `h5py`, which is an optional dependency that needs to be handled gracefully (1f002c1348572aa2a6a9dbef80b1a20c131fda40). I added both commits to a branch on my own repo, see: https://github.com/ischoegl/cantera/tree/flamestart - feel free to cherry-pick!

2022-06-09 13:44 UTC, rwest commented
Thanks. done.

2022-06-09 14:29 UTC, ischoegl commented
Thanks! ... but - ugh - `pandas` is optional also. I pushed the fix here directly.

2022-06-09 15:14 UTC, rwest commented
The pandas fix looks ok to me. Good catch. Thanks

2022-06-09 15:15 UTC, ischoegl approved these changes
@rwest - thanks for the fix and the example! It all looks good to me.

2022-06-09 15:23 UTC, merged