drop deprecated 'U' open option and fix formatting (Python 3.11 build errors)
Cantera/cantera pull request #1326
Opened 2022-06-07 19:55 UTC by mefuller

**Changes proposed in this pull request**

-
-
-

**If applicable, fill in the issue number this pull request is fixing**

Closes #

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2022-06-22 15:19 UTC, bryanwweber requested changes
Thanks Mark! Aside from the two comments here, can you move the purely formatting changes into a separate commit and add a [`.git-blame-ignore-revs`](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/) file to the root of the repo with that commit hash in it? Thanks!

2022-06-22 15:19 UTC, bryanwweber commented on site_scons/site_tools/subst.py
> +    # print 'CALLING SUBST_FILE'
Can you just delete this commented out code. Likewise below.

2022-06-22 15:19 UTC, bryanwweber commented on site_scons/site_tools/subst.py
> +    f = open(source, "r")
Rather than this whole bonkers thing which is a holdover from Python 2 days, let's just do

```
contents = Path(source).read_text()
```

2022-06-22 22:10 UTC, mefuller commented
@bryanwweber thanks for the review.
Is there a Python 3.11 build that can now be enabled for Cantera CI?

2022-06-23 18:16 UTC, bryanwweber commented
Thanks @mefuller! I pushed a small change to just delete the commented out `print` and `return` statements. As far as testing on 3.11 goes, I assume that this will fix the problem. We decided in #1287 not to bump the Python version in CI quite yet, as there are likely to be other spurious failures like this that we can either collect or resolve as we get PRs for them without worrying about the status of the CI suite.

Once CI passes, I think this is good to go.

2022-06-23 19:59 UTC, bryanwweber approved these changes

2022-06-23 20:00 UTC, merged