[Transport] Rename TransportBase.h to Transport.h
Cantera/cantera pull request #1327
Opened 2022-06-08 01:02 UTC by ischoegl

**Changes proposed in this pull request**

The header `TransportBase.h` does not match the naming convention used for other fundamental headers (see, e.g. includes in `core.h` introduced in #1238)

https://github.com/Cantera/cantera/blob/dceacdfba4519ee85d4e5f60e404fe25b8e5193b/include/cantera/core.h#L12-L15

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2022-06-08 01:26 UTC, ischoegl commented
@speth / @bryanwweber ... this is a trivial PR - not sure how to avoid the apparent 'churn' (which really isn't there) due to renaming + recreating a rudimentary file with the old name for deprecation purposes. I tried this in separate commits before, but it doesn't appear to make any difference ...

2022-07-02 23:28 UTC, speth requested changes
Thanks for fixing this annoying inconsistency, @ischoegl. I had just a few minor suggestions.

2022-07-02 23:28 UTC, speth commented on src/transport/Transport.cpp
> +#include "cantera/transport/Transport.h"
Above this, the Doxygen docstring needs to have `TransportBase.cpp` replaced with `Transport.cpp` (never mind that the rest of that docstring is erroneous copypasta).

2022-07-02 23:28 UTC, speth commented on include/cantera/transport/Transport.h
> +    }
If Git is going to see this as a "new" file, this would be a good opportunity to just replace all instances of `doublereal` in this file with `double`, since there's no way anyone could rebase a commit touching the old `TransportBase.h` header across this change without having to make manual updates anyway.

2022-07-02 23:28 UTC, speth commented on interfaces/cython/cantera/base.pyx
> +
I think this is unnecessary -- leaving `transport` as the empty string also results in creating a base `Transport` object here.

2022-07-03 08:19 UTC, ischoegl commented
@speth ... thanks for the review! Changes are taken care of.

2022-07-03 13:21 UTC, speth approved these changes

2022-07-03 13:21 UTC, merged