[Python] Fix typos in docstrings and extend documentation
Cantera/cantera pull request #1335
Opened 2022-07-13 03:51 UTC by g3bk47

**Changes proposed in this pull request**

Add equations to the equivalence_ratio and mixture_fraction functions in the python docstrings and fix some formatting typos

- [X] The pull request includes a clear description of this code change
- [X] Commit messages have short titles and reference relevant issues
- [X] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [X] The pull request is ready for review

2022-07-13 15:31 UTC, decaluwe requested changes
Many thanks for catching and tackling this, @g3bk47 ! I think most of these are straightforward.  I made one suggestion to make the notation used in the explanation of the mole fractions equation match that used in the equation (which you self-correct, in the mass-fraction version).

Other than that, this looks good to go.  Thanks again!

2022-07-13 15:31 UTC, decaluwe commented on interfaces/cython/cantera/thermo.pyx
> +        where :math:`Z_e` is the elemental mole fraction of element :math:`e`.
```suggestion
        where :math:`Z_{\mathrm{mole},e}` is the elemental mole fraction of element :math:`e`.
```

2022-07-13 21:51 UTC, g3bk47 commented
Thanks, @decaluwe! I commited your suggestion

2022-07-15 15:12 UTC, decaluwe commented
Thanks, @g3bk47 - this all LGTM.  I'm not sure why the CI/Coverage test is failing.  Once that clears up, I'll go ahead and merge.

Are you already added to `AUTHORS.md`? I am guessing you are, but thought I'd ask.

2022-07-15 15:12 UTC, decaluwe approved these changes, later dismissed

2022-07-15 17:26 UTC, ischoegl commented
@g3bk47 and @decaluwe ... I retriggered the failing tests and they now pass - so it was just some temporary GitHub issue. Thanks for the fix!

2022-07-15 18:23 UTC, g3bk47 commented
Yes, I am already listed in the authors file (https://github.com/Cantera/cantera/blob/main/AUTHORS#L63)

2022-07-15 18:58 UTC, ischoegl requested changes
On second look, I noticed that the docs are currently not building - could you please address? There are some warnings about block quotes, see https://github.com/Cantera/cantera/runs/7361821505?check_suite_focus=true

Other than that, a couple of lines go beyond our 88 character limit.

2022-07-15 18:58 UTC, ischoegl commented on interfaces/cython/cantera/thermo.pyx
> +        .. math:: \phi = \frac{Z_{\mathrm{mole},C} + Z_{\mathrm{mole},S} + \frac{1}{4}Z_{\mathrm{mole},H}} {\frac{1}{2}Z_{\mathrm{mole},O}}
Line exceeds 88 characters - could you shorten this and the other instances?

2022-07-16 00:16 UTC, g3bk47 commented
@ischoegl You are right, the comment strings need to be raw strings due to the latex syntax. I built the sphinx documentation locally and it seems to work now

2022-07-16 05:41 UTC, ischoegl reviewed
Was about to merge, but found one stray quotation mark

2022-07-16 05:41 UTC, ischoegl commented on interfaces/cython/cantera/thermo.pyx
> +            >>> gas.set_equivalence_ratio(1.2, "NH3':0.8,CO:0.2", 'O2:1', basis='mole')
```suggestion
            >>> gas.set_equivalence_ratio(1.2, 'NH3:0.8,CO:0.2', 'O2:1', basis='mole')
```

2022-07-16 05:45 UTC, g3bk47 commented
Good catch, thanks!

2022-07-16 05:46 UTC, ischoegl approved these changes

2022-07-16 06:16 UTC, merged