[Python] Disable warnings for extinct flame
Cantera/cantera pull request #1336
Opened 2022-07-14 02:41 UTC by g3bk47

**Changes proposed in this pull request**

Currently, each counterflow flame solution that is extinct will print a warning that the flame is too thick. Since the temperature-based checks for flame thickness and width do not make sense for an extinct flame, disable the warnings in that case.

**Checklist**

- [X] The pull request includes a clear description of this code change
- [X] Commit messages have short titles and reference relevant issues
- [X] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [X] The pull request is ready for review

2022-07-15 17:43 UTC, speth approved these changes
This makes sense to me, and it's a nice, simple change.

2022-07-15 17:43 UTC, merged

2022-07-15 18:27 UTC, ischoegl requested changes
@g3bk47 ... thank you for the PR! I believe the change makes sense. The only thing I'd ask is to replace the `print` statements by `warnings.warn`.

2022-07-15 18:27 UTC, ischoegl commented on interfaces/cython/cantera/onedim.py
> +                          'fuel inlet mass flux to the oxidizer inlet mass flux.')
```suggestion
                    warnings.warn("The flame temperature peak is close to the "
                          "fuel inlet. Consider increasing the ratio of the "
                          "fuel inlet mass flux to the oxidizer inlet mass flux.")
```
Could you replace the regular print statements by warnings here and in the other lines that are touched by this PR? (the default `UserWarning` is likely the best option). Also, in all new/modified code, single quotes should be replaced by double quotes.

2022-07-15 18:28 UTC, ischoegl commented on interfaces/cython/cantera/onedim.py
> +                          'fuel inlet mass flux to the oxidizer inlet mass flux.')
Ugh. Walked away for a minute. Nevermind ...

2022-07-21 07:38 UTC, ischoegl commented on interfaces/cython/cantera/onedim.py
> +                          'fuel inlet mass flux to the oxidizer inlet mass flux.')
see #1339