Update three body logic
Cantera/cantera pull request #1338
Opened 2022-07-18 08:25 UTC by ischoegl

**Changes proposed in this pull request**

- Fix cases where three-body detection logic introduced in #1333 fails

**If applicable, fill in the issue number this pull request is fixing**

**If applicable, provide an example illustrating new features this pull request is introducing**

```
In [2]: ct.Reaction(
   ...:     equation="CH2OCH + M <=> CH2CHO + M", rate={"A": 5.0e09, "b": 0.0, "Ea": 0.0}
   ...: )
Out[2]: CH2OCH + M <=> CH2CHO + M    <three-body-Arrhenius>
```

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2022-07-18 20:20 UTC, ischoegl commented
I believe this is ready for a review.

2022-07-18 22:36 UTC, bryanwweber reviewed
I have one very minor suggestion, which may not be an improvement. I also wonder if you can clarify, in the docstring and the error message, what "ambiguous" means in this context. What should the user do to correct this problem?

2022-07-18 22:36 UTC, bryanwweber commented on src/kinetics/Reaction.cpp
> +    }
Seems like this could be a little simpler as:

```suggestion
    bool count = false;
    for (const auto& reac : reactants) {
        if (products.count(reac.first)) {
            count = true;
            break;
        }
    }
```

2022-07-21 07:37 UTC, ischoegl commented
@bryanwweber ... thanks! I updated the comments and error messages. Let me know if this clarifies things sufficiently.

2022-07-21 08:05 UTC, ischoegl commented
PS: the only question I have is about another edge case. At the moment, the logic requires either three reactants or three products to detect a three-body reaction and thus misses the following
```
In [6]: ct.Reaction(
   ...:     equation="CH2OCH + O2 <=> CH2CHO + O2", rate={"A": 5.0e09, "b": 0.0, "Ea": 0.0}
   ...: )
Out[6]: CH2OCH + O2 <=> CH2CHO + O2    <Arrhenius>
```
... it is certainly perceivable that this should be a `three-body-Arrhenius` instead?

2022-07-22 05:34 UTC, ischoegl commented
I think this is finally ready. At this point I believe that unit tests cover everything I can think of - once this is merged, we should be good to bump the alpha version with #1337

2022-07-23 23:23 UTC, speth requested changes
Thanks for working on these refinements, @ischoegl.

Beside the suggestions below, I was thinking that we should probably limit the use of the `efficiencies` and `default-efficiency` fields to the case where third body is `M`, to avoid allowing the rather confusing example below:

```yaml
equation: H + O2 + N2 = HO2 + N2
rate-constant: {A: 1, b: 1, Ea: 200}
efficiencies: {N2: 10.0}
default-efficiency: 1
```

which is currently allowed and seems to be equivalent to writing the same reaction with `M` as the third body.

2022-07-23 23:23 UTC, speth commented on include/cantera/kinetics/Reaction.h
> +    bool m_explicit_3rd = false;
The comment here is incorrect, isn't it?

2022-07-23 23:23 UTC, speth commented on src/kinetics/Reaction.cpp
> +    // ensure safe serialization
This comment is kind of confusing -- what does "safe" serialization mean?

2022-07-23 23:23 UTC, speth commented on include/cantera/kinetics/Reaction.h
> +    void getParameters(AnyMap& node, bool explicit_3rd=false) const;
I think the second argument can be made mandatory -- this method is only called from one place, in `Reaction::getParameters`. Alternatively, would it make more sense to make `Reaction::m_explicit_3rd` a member of the `ThirdBody` class instead, eliminating the need to pass this in here?

2022-07-23 23:23 UTC, speth commented on test/kinetics/kineticsFromYaml.cpp
> +    AnyMap input = R->parameters();
I think these tests should be run with `false` passed to the `parameters()` method to suppress the keys that came directly from the input, and test that the method is actually recreating the structure.

2022-07-24 05:58 UTC, ischoegl commented on include/cantera/kinetics/Reaction.h
> +    bool m_explicit_3rd = false;
It's not necessarily incorrect, but also not clear. The flag indicates that a third body needs to be explicitly included for serialization.

2022-07-24 06:06 UTC, ischoegl commented on src/kinetics/Reaction.cpp
> +    // ensure safe serialization
clarified - it's really "correct" output.

2022-07-24 08:02 UTC, ischoegl commented
@speth ... thanks for the review! I adopted recommendations and tweaked the logic so that your example throws the following error:
```
*******************************************************************************
InputFileError thrown by Reaction::setParameters:
Error on line 2 of input string:
Invalid default efficiency for explicit collider N2; value needs to be zero
|  Line |
|     1 |
>     2 > equation: H + O2 + N2 = HO2 + N2
          ^
|     3 | rate-constant: {A: 1, b: 1, Ea: 200}
|     4 | efficiencies: {N2: 10.0}
|     5 | default-efficiency: 1
*******************************************************************************
```
(it does make sense that the default efficiency has to be zero in this case).

On the other hand, I'd like to keep the ability to change the efficiency for `N2`. Among others, specifying the efficiency does allow for the disambiguation of the following:
```yaml
equation: CH2 + O2 <=> CH2 + O2
rate-constant: {A: 5.0e+9, b: 0.0, Ea: 0.0}
efficiencies: {O2: 1.}
```
I.e. this is handled as a three-body reaction, where the user specifies which of the two participating species is treated as a third body. (As an aside: I realize that the reaction makes little sense, but I had originally blocked those but the feedback was that these reactions should be allowed.)

2022-07-24 22:45 UTC, speth approved these changes
Thanks, @ischoegl. This looks good to me.

2022-07-24 22:48 UTC, merged