Porous burner example
Cantera/cantera pull request #1443
Opened 2023-02-26 13:58 UTC by g3bk47

Hi all,
I really like the extensible reactor classes. However, I feel that they are more powerful than what the currently available examples show. Therefore, I would like to contribute another example which uses the extensible reactors to simulate reacting flows in porous media burners. The porous media burner in question has been experimentally investigated and the burner setup as well as the governing equations are described in a recent publication (https://doi.org/10.1016/j.combustflame.2023.112642).
Since the code in this example uses the real properties and submodels for the different burner sections, it is quite a bit longer than other examples available in Cantera. I already simplified the code a bit compared to the actual code available in the supplementary materials of the paper, but it is still quite involved. The example showcases:
 - how to add a temperature equation for a solid phase;
 - add submodels for heat transfer between gas and solid, radiation, solid heat conduction;
 - describe the burner with an arbitrary amount of reactors;
 - describe the burner with an arbitrary amount of sections filled with different porous materials;
 - create a reactor cascade without mass flow controllers or pressure valves by assuming steady-state conditions and constant pressure.

Let me know what you think of this example and if I should simplify/shorten it further.

![T](https://user-images.githubusercontent.com/22117927/221414814-c3e90ca4-d452-4d4f-aac8-9223614e7eaf.png)

**Checklist**

- [X] The pull request includes a clear description of this code change
- [X] Commit messages have short titles and reference relevant issues
- [X] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [X] The pull request is ready for review

2023-03-16 02:36 UTC, speth commented on data/YZA.yaml
> +  Properties for yttria-stabilzed zirconia alumina (YZA) used in
```suggestion
  Properties for yttria-stabilized zirconia alumina (YZA) used in
```

2023-03-16 03:36 UTC, speth requested changes
Thanks for providing this example, @g3bk47. I definitely agree that capabilities of the `ExtensibleReactor` classes are not fully explored in the existing examples. Your use case here isn't something I anticipated, but I'm glad to see that you were able to use it effectively.

While this is somewhat longer than other examples, I think that's completely fine, and this is a really nice example of building a "device scale" model on top of Cantera without being too complex.

2023-03-16 03:36 UTC, speth commented on data/YZA.yaml
> +  Properties for yttria-stabilzed zirconia alumina (YZA) used in
```suggestion
  Properties for yttria-stabilized zirconia alumina (YZA) used in
```

2023-03-16 03:36 UTC, speth commented on data/YZA.yaml
> +  porous media burners. Data compiled by Thorsten zirwes and used in
```suggestion
  porous media burners. Data compiled by Thorsten Zirwes and used in
```

2023-03-16 03:36 UTC, speth commented on data/YZA.yaml
> +- name: yttria_stabilzed_zirconia
Besides the spelling, we generally use dashes instead of underscores in the YAML format
```suggestion
- name: yttria-stabilized-zirconia
```

2023-03-16 03:36 UTC, speth commented on AUTHORS
> +Guillaume Vignat, Stanford University
If Guillaume has a GitHub account, can you (a) add their account name here like it is for others?

Also, please amend the commit message for the commit that adds the example to contain a line formatted like:
```
Co-authored-by: Guillaume Vignat <username@stanford.edu>

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +a general way to support an arbitrary number of reactors and an arbirary number of
```suggestion
a general way to support an arbitrary number of reactors and an arbitrary number of
```

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +def getInitalGas(gas):
```suggestion
def getInitialGas(gas):
```
And of course all places where this is called.

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +        self.solid = solid         # poperties of the solid porous medium
```suggestion
        self.solid = solid         # properties of the solid porous medium
```

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +            index = self.component_index(self.thermo.species_name(k))
Calling `component_index` and `species_name` so many times in this inner loop is inefficient. You can get a noticeable speedup by just calculating the species offset once in `after_initialize` as
```py
species_offset = self.component_index(self.thermo.species_name(0))
```
and calculating `index` as `k + species_offset` here.

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +            RHS[index] += wdot[k] * self.thermo.molecular_weights[k] / density
Accessing each element of the `molecular_weights` array like this causes it to be retrieved from C++ in every single loop iteration. Storing the `molecular_weights` array as a member of the `PMReactor` object during initialization will help quite a bit.

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +                (self.V * porosity * density) * (Y_in[k] - self.thermo.Y[k])
Same thing applies here for `self.thermo.Y`, though that of course needs to be evaluated within `replace_eval`.

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +Therefore, Cantera version 2.6.0a4 or higher is required.
```suggestion
Therefore, Cantera version 2.6.0 or higher is required.
```

2023-03-16 03:36 UTC, speth commented on samples/python/reactors/PorousMediaBurner.py
> +          radiation modeling, reactor cascade
The required version should just be "2.6.0". You should also list `matplotlib` as a dependency (we usually put ">= 2.0" as the version requirement).

For the keywords, please see the list in `doc/example-keywords.txt` and add any that seem relevant. "user-defined model" is the one that covers the use of `ExtensibleReactor`. If you want to add any beyond the existing ones, they should be ones where there's some likelihood of (eventually) having more examples that use the same keywords. I think I'd suggest:
```
Keywords: user-defined model, reactor network, combustion, porous media, heat transfer, radiative heat transfer
```

2023-03-20 18:45 UTC, g3bk47 commented
Hi Ray, thanks for the review! I think I incorporated all of your comments with the latest commit.

2023-03-20 18:49 UTC, ischoegl requested changes
Hi @g3bk47 ... thanks for contributing a nice example based on `ExtensibleReactor`.

I believe that details of the implementation are in good hands (@speth already commented). 

From my perspective, I wanted to make sure that the example description includes a disclaimer clearly stating limitations of the model. Porous burners are intrinsically 1D; while it is certainly legitimate to simplify for some applications (e.g. coarse approximations of temperatures or predictions of emissions), a reactor cascade has inherent limitations that will not capture the full range of behaviors. At the same time the example will capture excess enthalpy creating superadiabatic conditions that promote combustion beyond conventional flammability limits and/or at rates that are significantly higher than adiabatic flame speeds. 

The most interesting aspect of two-section burners is that they possess the ability to stabilize flames for a broad range of inlet mass fluxes due to internal heat recirculation across the interface: stabilization is accomplished by mismatched matrix properties, where the downstream section by itself promotes flash-back while the upstream section by itself promotes blow-off. The stabilization mechanism is based on solid conduction / radiation, where implementation details are extremely relevant if one wants to predict flashback or blow-off behavior. It is unrealistic to capture these physics with a coarsely refined 0D approach (or disabling reactions).

In a nutshell, the model is certainly ok for illustration purposes, but will not necessarily have predictive qualities when it comes to conditions that can be realized in experiments. Thus, it is prudent to clearly point out these limitations to avoid misleading conclusions by users

2023-03-20 18:49 UTC, ischoegl commented on samples/python/reactors/PorousMediaBurner.py
> +This code implements a reactor cascade model for the simulation of reactive
Please add a disclaimer stating limitations of the model, as is uses drastic simplifications in order to convert it from a 1D problem to a 0D cascade.

2023-03-20 18:49 UTC, ischoegl commented on samples/python/reactors/PorousMediaBurner.py
> +    return (1 - 0.84) * 1857.0 * Ts**(-0.5332)
please add comments explaining the choice of parameters.

2023-03-20 18:49 UTC, ischoegl commented on samples/python/reactors/PorousMediaBurner.py
> +            chemistry=False,
The description of the example should mention that the upstream section does not consider chemistry.

2023-03-20 19:59 UTC, g3bk47 commented
Hi @ischoegl,
Thanks for your comments! I added clarifications about the limitations of this simple model and included references for the heat conductivity of the solids.

2023-03-20 20:12 UTC, ischoegl submitted a review, later dismissed
@g3bk47 ... thanks for the prompt updates!

2023-03-20 22:29 UTC, speth approved these changes
Thanks for the updates, @g3bk47. I think this looks good. I just pushed an update to squash a couple of the typo-fix commits together. We can merge as soon as the CI finishes.

2023-03-20 23:30 UTC, merged

2023-11-04 20:38 UTC, HadiEbrahimiHaratameh commented
> Hi @g3bk47 ... thanks for contributing a nice example based on `ExtensibleReactor`.
> 
> I believe that details of the implementation are in good hands (@speth already commented).
> 
> From my perspective, I wanted to make sure that the example description includes a disclaimer clearly stating limitations of the model. Porous burners are intrinsically 1D; while it is certainly legitimate to simplify for some applications (e.g. coarse approximations of temperatures or predictions of emissions), a reactor cascade has inherent limitations that will not capture the full range of behaviors. At the same time the example will capture excess enthalpy creating superadiabatic conditions that promote combustion beyond conventional flammability limits and/or at rates that are significantly higher than adiabatic flame speeds.
> 
> The most interesting aspect of two-section burners is that they possess the ability to stabilize flames for a broad range of inlet mass fluxes due to internal heat recirculation across the interface: stabilization is accomplished by mismatched matrix properties, where the downstream section by itself promotes flash-back while the upstream section by itself promotes blow-off. The stabilization mechanism is based on solid conduction / radiation, where implementation details are extremely relevant if one wants to predict flashback or blow-off behavior. It is unrealistic to capture these physics with a coarsely refined 0D approach (or disabling reactions).
> 
> In a nutshell, the model is certainly ok for illustration purposes, but will not necessarily have predictive qualities when it comes to conditions that can be realized in experiments. Thus, it is prudent to clearly point out these limitations to avoid misleading conclusions by users

Hi,
I Thank @g3bk47 and @speth for the code and comments on it.
I think we should apply the Porous including adding the energy equation for the solid in 1D rather than 0D.
If the class ExtensibleReactor could be extended for 1D reactor model  (e.g. PFR), the network of the reactors such a way that a network of the PFR reactors are used, the results may be more realistic,
Thank you
Hadi