OneD domain factories
Cantera/cantera pull request #1445
Opened 2023-02-28 05:45 UTC by ischoegl

**Changes proposed in this pull request**

- 🚧 🏗️ 
-
-

**If applicable, fill in the issue number this pull request is fixing**

Closes #

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-02-28 22:37 UTC, ischoegl commented
@speth ... after running into #1447 (which likely involves tackling Cantera/enhancements#158) I am omitting factory constructors in `clib` for the moment.

2023-03-03 03:07 UTC, ischoegl commented
Converting back to draft, as this should be merged *after* #1448.

2023-03-07 04:09 UTC, ischoegl commented
Rebased after the merge of #1448; some experiments for the introduction of `SharedCabinet` and/or `newDomain` factory constructors indicate that updates to `clib/ctonedim` will have to be somewhat more extensive than anticipated, and are postponed for another time.

2023-03-13 14:47 UTC, ischoegl commented
@speth .... At this point, I verified that the traditional MATLAB toolbox runs correctly. There will be some trivial merge conflicts with #1455 (tests for model names), but this is otherwise ready for a review.

@ssun30 ... this PR should bring additional simplifications that are relevant to #1182.

2023-03-14 20:26 UTC, ischoegl commented
Rebased and updated after merging #1455 / ready for a review.

2023-03-17 14:34 UTC, ischoegl commented
Resolved a minor merge conflict introduced by #1426.

2023-03-18 15:01 UTC, speth requested changes
Thanks, @ischoegl. This looks very good, and I think having the 1D code start to use the factory infrastructure that we have for most other object types will simplify some future additions (say, `ExtensibleDomain`). I had only a handful of minor suggestions.

2023-03-18 15:01 UTC, speth commented on interfaces/cython/cantera/_onedim.pyx
> +    _domain_type = "None"
For consistency with #1455, I suppose this should be `"none"`.

2023-03-18 15:01 UTC, speth commented on interfaces/cython/cantera/onedim.py
> +        elif isinstance(dom, (FreeFlow, AxisymmetricFlow, IdealGasFlow, IonFlow)):
Can this be just
```suggestion
        elif isinstance(dom, _FlowBase):
```

2023-03-18 15:01 UTC, speth commented on interfaces/cython/cantera/onedim.py
> +            if self.flame.domain_type.startswith("axisymmetric"):
Would it be better to rely on `isFree` for this check?

2023-03-18 15:01 UTC, speth commented on src/clib/Cabinet.h
> +    static shared_ptr<T> as(size_t n) {
For all the cases where this is used, the existing `get` method could be used instead, right?

2023-03-18 15:01 UTC, speth commented on src/clib/ct.cpp
> +                TransportCabinet::index(*(soln->transport())));
The fact that this deletes the old `Transport` object is potentially a little surprising, and should probably be noted with the declaration of this function.

2023-03-18 15:01 UTC, speth commented on src/clib/ctmultiphase.cpp
>                                 int maxsteps, int maxiter, int loglevel)
The indentation on the following line is now ragged.

2023-03-18 15:01 UTC, speth commented on src/oneD/StFlow.cpp
>  }
This suggests that `fixed_mdot` could be deprecated in favor of `!isFree`.

2023-03-18 15:01 UTC, speth commented on test/clib/test_clib.cpp
> +    delete[] buf;
If you want to avoid needing to do a manual new/delete, you can write
```suggestion
    vector<char> buf(buflen);
    trans_transportModel(trans, buflen, buf.data());
    string trName(buf.data());
    ASSERT_EQ(trName, "mixture-averaged");
```

2023-03-18 18:20 UTC, ischoegl commented on src/clib/Cabinet.h
> +    static shared_ptr<T> as(size_t n) {
This is correct. I do, however, believe that passing pointers is in the end more flexible than what can be done with references. I view the `get` method as useful as drop-in replacement, while `as` may be preferable for future work.

2023-03-18 18:23 UTC, ischoegl commented on src/oneD/StFlow.cpp
>  }
Potentially, yes. At the same time, I am not 100% sure that `m_isFree` will be needed once all raw pointers are replaced, as a `dynamic_pointer_cast` does the job by itself.

2023-03-18 18:25 UTC, ischoegl commented on interfaces/cython/cantera/onedim.py
> +            if self.flame.domain_type.startswith("axisymmetric"):
I believe that it makes more sense to refactor `IonFlow` to be part of `AxisymmetricFlow`, and then test for the type (I don't want to introduce a new Python method just to deprecate/remove it one release later). At the moment, the `startswith` does the job.

2023-03-18 18:49 UTC, ischoegl commented on interfaces/cython/cantera/onedim.py
> +        elif isinstance(dom, (FreeFlow, AxisymmetricFlow, IdealGasFlow, IonFlow)):
After trying this, I remembered that Cython refuses to export class names starting with an underscore. There may be a trick to force export, but I'm not aware of it.

2023-03-18 18:52 UTC, ischoegl commented
@speth ... thanks for the review! I adopted some suggestions, and responded to others.

2023-03-18 20:48 UTC, speth approved these changes
Thanks for the updates, @ischoegl. This looks good to me.

2023-03-18 21:21 UTC, merged