Fix clash of names with upstream function
Cantera/cantera pull request #1471
Opened 2023-04-01 22:33 UTC by ischoegl

HighFive 2.7.0 introduces a new `create_enum_boolean` function, which clashes with an existing local function in `Storage.cpp`. The local function is renamed as a solution.

See https://github.com/BlueBrain/HighFive/issues/713

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-04-04 15:48 UTC, ischoegl commented
While this is ready for a review, I am leaving this in draft mode until HighFive 2.7.1 is released. The current CI failures are caused by a known issue with conda's `highfive` package 2.7.0 for MSVC 14.1 that are unrelated to Cantera.

2023-04-11 11:25 UTC, ischoegl commented
@speth ... as expected, HighFive 2.7.1 conda packages resolve the CI issues (other than #1473, which is separate).

2023-04-11 14:56 UTC, speth requested changes
Thanks for finding the solution to this, @ischoegl -- the CI error messages definitely did not make it clear what was going wrong. I had some suggestions that I think will simplify the configuration checks a bit.

2023-04-11 14:56 UTC, speth commented on SConstruct
> +    highfive_include = '"../ext/HighFive/include/highfive/H5Version.hpp"'
This should be done as part of a SCons action -- right now, it's being repeated every time `scons` is called.

Also, I think the whole procedure for generating `H5Version.hpp` should be moved to `ext/SConscript`, which is where similar things like generating `sundials_config.h` are handled.

2023-04-11 14:56 UTC, speth commented on SConstruct
> +    retcode, h5_lib_version = conf.TryRun(h5_lib_version, ".cpp")
I think this is essentially the same thing as the existing `get_expression_value` function, and could be replaced by just calling:
```py
h5_version_source = get_expression_value([highfive_include], "QUOTE(HIGHFIVE_VERSION)")
retcode, h5_lib_version = conf.TryRun(h5_version_source, ".cpp")
```

2023-04-11 14:56 UTC, speth commented on SConstruct
> +cdefine("HIGHFIVE_BOOLEAN", "highfive_boolean")
To avoid namespace pollution (especially if `HIGHFIVE_` is already the prefix used by HIGHFIVE), we should use a different name like `CT_USE_HIGHFIVE_BOOLEAN`.

2023-04-11 14:56 UTC, speth commented on src/base/Storage.cpp
> +#if HIGHFIVE_BOOLEAN
Shouldn't this be `#ifdef`?

2023-04-11 16:59 UTC, ischoegl commented on SConstruct
> +    highfive_include = '"../ext/HighFive/include/highfive/H5Version.hpp"'
@speth ... while it's clear why you are requesting this, the details get a little gnarly. The reason is that `ext/SConscript` is processed after the configuration step, but I need to create `H5Version.hpp` at an earlier point, as I read the version number from the related file (I found out the hard way that it's good to know what is being compiled when debugging for this PR).

As an alternative that does not rewrite `H5Version.hpp` every time `scons build` is called, I am deleting the file during `scons clean`, and write it only if the file does not exist.

2023-04-11 17:09 UTC, ischoegl commented
> Thanks for finding the solution to this, @ischoegl -- the CI error messages definitely did not make it clear what was going wrong. 

I guess I need to give a shoutout to folks over at the HighFive project, who were extremely helpful and responsive in the debugging effort.

Other than that, I rebased and addressed three of the four suggestions. For the last one, I no longer rewrite the file, but am not sure how to move things out of `SConstruct` without major overhauls of the interface.

2023-04-14 00:41 UTC, speth commented on SConstruct
> +    highfive_include = '"../ext/HighFive/include/highfive/H5Version.hpp"'
Ah, thanks for the explanation. I think I have a way around this complexity. Basically, we can simplify the logic to:
- if `system_highfive` is set to `y` or `default`, try to get the version from `H5Version.hpp` using `get_expression_value`.
- If that fails, parse the version from `CMakeLists.txt`.
- Then, use the version to determine the value of `CT_USE_HIGHFIVE_BOOLEAN`.

This way, there's no need to generate `H5Version.hpp` (which is never included elsewhere), and this also avoids leaving the `ext/HighFive` directory in a "dirty" state.

2023-04-14 12:51 UTC, ischoegl commented on SConstruct
> +    highfive_include = '"../ext/HighFive/include/highfive/H5Version.hpp"'
Ok - I guess I was too focused on getting everything done at once! I adopted your suggestion.

2023-04-14 13:19 UTC, ischoegl commented
@speth ... thanks for the suggestion. I believe that everything is taken care of at this point. 

I submitted a minor PR #1477 that could be adopted before the version bump, but it's not a major issue (it's mostly about updating annoying formatting for something that I've been working on).

2023-04-14 15:14 UTC, speth approved these changes, later dismissed
Thanks, @ischoegl, this looks good to me.

2023-04-14 15:14 UTC, speth commented on SConstruct
> +        remove_file(name.parent / name.stem)
This is no longer necessary if we aren't generating `H5Version.hpp`, right?

2023-04-14 16:18 UTC, ischoegl commented on SConstruct
> +        remove_file(name.parent / name.stem)
Good catch! I had deleted it, but apparently undid some of my changes before committing.

2023-04-14 17:02 UTC, ischoegl commented
@speth ... could you re-approve? (fixing the last item dismissed your approval)

2023-04-14 17:06 UTC, speth approved these changes

2023-04-14 17:06 UTC, merged