Remove unused configuration variables
Cantera/cantera pull request #1472
Opened 2023-04-05 03:44 UTC by ischoegl

**Changes proposed in this pull request**

-
-
-

**If applicable, fill in the issue number this pull request is fixing**

Closes #

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-04-08 19:58 UTC, speth requested changes
Thanks for the cleanup work on this, @ischoegl. Looks good to me besides the one comment below.

2023-04-08 19:58 UTC, speth commented on src/base/application.cpp
> -
I'm okay with eliminating this as a standard search location, but in that case there are a few docstrings that need to be updated, too (in `global.h` and `application.h`).

2023-04-08 22:34 UTC, ischoegl commented
Thanks! I removed the references as suggested.

2023-04-09 14:11 UTC, speth approved these changes

2023-04-09 14:11 UTC, merged