Replace Cabinet in clib / update zeroD factory constructors
Cantera/cantera pull request #1507
Opened 2023-06-19 15:39 UTC by ischoegl

**Changes proposed in this pull request**

- Make `zeroD` factory constructors return `shared_ptr<ReactorBase>`, etc.
- Replace `Cabinet` by `SharedCabinet` in `clib` interface

Exception: `Cabinet<Func1>` remains as required updates go beyond the scope of this PR.

**If applicable, fill in the issue number this pull request is fixing**

Addresses Cantera/enhancements#64

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-06-20 22:21 UTC, speth requested changes
Thanks, @ischoegl. I'm glad to see something that adds a bit of testing for `Func1`, even if that was somewhat incidental to what you were setting out to do. I had just one suggested change.

2023-06-20 22:21 UTC, speth commented on test/clib/test_ctfunc.cpp
> +    ASSERT_EQ(func_value(fcn, 0.5), sin(omega * 0.5));
I think the equality comparisons should be done using `EXPECT_DOUBLE_EQ`. Though I'll admit the difference here is fairly minor, it's more consistent with what we should be trying to maintain elsewhere. `ASSERT_` should only be used when we need to stop the test case immediately on a failure. And truly exact floating point results are always iffy -- this relaxes the tolerance to a few units in the last place.

2023-06-21 00:31 UTC, ischoegl commented
> Thanks, @ischoegl. I'm glad to see something that adds a bit of testing for `Func1`, even if that was somewhat incidental to what you were setting out to do. I had just one suggested change.

It was indeed incidental. I did some testing for replacement options for the remaining `Cabinet<Func1>`, where the tests were the quickest way to see whether things worked as expected. Alas, `Func1` does need some refactoring that I don't want to tackle at the moment.

2023-06-21 12:28 UTC, speth approved these changes
Thanks, @ischoegl. This looks good to me.

2023-06-21 12:28 UTC, merged