Enhance Python func1 Interface
Cantera/cantera pull request #1521
Opened 2023-06-30 03:54 UTC by ischoegl

**Changes proposed in this pull request**

- Provide access to C++ `Func1` objects from Python
- Remove unnecessary argument from advanced functor constructors (oversight in #1513)
- Replace Python callbacks returning constants with C++ functors

**If applicable, provide an example illustrating new features this pull request is introducing**

```Python
f1 = ct.Func1.create("sin")
f2 = ct.Func1.create("Gaussian", [0, 1, 2])
func = ct.Func1.create("sum", f1, f2)
```

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-06-30 13:35 UTC, speth commented
I'm not really clear on the use case for constructing `Func1` objects in Python, except for `Func1Py` which allows calling arbitrary Python functions. The latter makes it easy to define both simple functions as lambdas as well as arbitrarily complex functions including capturing outside variables, which the piecewise `Func1` construction can never replicate.

2023-06-30 14:22 UTC, ischoegl commented
@speth ... this is ready for a review. For the Python `Func1` API, I kept the access outside of the main constructor. On of my initial reasons is that it is possible to recreate the C++ type names dynamically (see [SO example](https://stackoverflow.com/questions/52748764/python-3-set-namespace-for-dynamic-classes)), but I'm not sure that it's worth the effort. Another reason is that I want to keep this an "advanced feature" with the current Python callback behavior remaining the go-to solution.

2023-06-30 14:27 UTC, ischoegl commented
> I'm not really clear on the use case for constructing `Func1` objects in Python, except for `Func1Py` which allows calling arbitrary Python functions. The latter makes it easy to define both simple functions as lambdas as well as arbitrarily complex functions including capturing outside variables, which the piecewise `Func1` construction can never replicate.

I am aware that the `Func1Py` approach is a *lot* more flexible. This PR (where most lines are actually a clean-up for #1513) mainly illustrates that it is extremely simple to add access. Python can serve as a test-bed for other API's that lack the generic callbacks (e.g. MATLAB). In theory, the C++ functors should be faster than Python callbacks, although I'm not sure how much this matters. Regardless, I replaced the constant lambda functions with the C++ equivalent.

2023-06-30 20:02 UTC, ischoegl commented
@speth ... I renamed the factory class method to `cxx_functor`; the factory recreates the underlying C++ classes dynamically, where type names are preserved.

2023-07-01 16:24 UTC, speth requested changes
Thanks, @ischoegl. I'm glad to see that this incorporates the simplification I had been trying to get at in #1513 to eliminate the unnecessary integer argument to the `Func1` constructors. Besides that, just a couple of very minor comments.

2023-07-01 16:24 UTC, speth commented on doc/sphinx/cython/zerodim.rst
> -.. autoclass:: TabulatedFunction
I thought `TabulatedFunction` was better than `Tabulated1` -- the use of `1` as a suffix to indicate this family of classes on the C++ side is pretty obscure.

2023-07-01 16:24 UTC, speth commented on include/cantera/numerics/Func1.h
> +    string type_name() const;
```suggestion
    string typeName() const;
```

2023-07-01 16:58 UTC, ischoegl commented on doc/sphinx/cython/zerodim.rst
> -.. autoclass:: TabulatedFunction
Yes, this was a last-minute change. The reason for this change was that:

```Python
>>> f1 = ct.TabulatedFunction([0, 1, 2], [0, 1, 0])
>>> f2 = ct.Func1.cxx_functor("tabulated-linear", [0, 1, 2, 0, 1, 0])
``` 
would end up having different types, despite being the exact same thing (the `TabulatedFunction` only adds a more user-friendly constructor).

2023-07-01 17:05 UTC, ischoegl commented
Thanks, @speth for the prompt review. I can retain the old name for `TabulatedFunction`, but explained why I opted to update. Let me know ...

2023-07-01 18:28 UTC, speth commented on doc/sphinx/cython/zerodim.rst
> -.. autoclass:: TabulatedFunction
Understood. I think what you've go here makes sense in that case.

2023-07-01 18:28 UTC, speth approved these changes
Thanks, @ischoegl, I think this is good to go.

2023-07-01 18:29 UTC, merged