Update doxygen Chemical Kinetics Documentation
Cantera/cantera pull request #1534
Opened 2023-07-07 17:32 UTC by ischoegl

**Changes proposed in this pull request**

Restructure/consolidate/correct doxygen documentation for Chemical Kinetics objects.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-07-08 01:26 UTC, ischoegl commented
@speth ... I am stopping here. I *think* that navigating the "C++ Modules" structure has become a bit easier and I also started to fill in some gaps. I have made no attempts to update sections on integrators, phases, oneD and zeroD, or some of the ungrouped Cantera capabilities.

The PR targets the structure and should help locating information based on a handful of topics. Revising of actual docstrings goes beyond the scope of the PR.

2023-07-15 22:40 UTC, speth requested changes
Thanks for working on this, @ischoegl. I think the new landing page is a much friendlier alternative to the essentially blank page that's there now. I have only a few minor suggestions.

2023-07-15 22:40 UTC, speth commented on include/cantera/equil/MultiPhase.h
> +//! @ingroup equil
Would it make sense to combine the `equil` and `equilfunctions` groups? I don't see a clear distinction between them.

2023-07-15 22:40 UTC, speth commented on include/cantera/kinetics/ReactionRateFactory.h
> + * @ingroup reactionGroup
I think "Interface Rate Parameterizations" is a better description for this group -- sticking rates don't have any dependence on the coverages.

2023-07-15 22:40 UTC, speth commented on include/cantera/base/global.h
> + * @ingroup exceptions
The hierarchy here seems a bit off to me -- logging isn't just about errors. Would the following make more sense?
- Errors & Diagnostics
  - Exceptions
  - Warnings
  - Logging

2023-07-15 22:40 UTC, speth commented on include/cantera/kinetics/KineticsFactory.h
>   * @param phases     Vector of phases containing species which participate in
For the sake of avoiding too much variety in the different ways of using Doxygen, you might consider the "autobrief" style that we use more frequently:
```cpp
//! Create a new kinetics manager, initialize it, and add reactions.
/*!
 * @param phases     Vector of phases containing species which participate in
```

2023-07-15 22:40 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
> +//! of the %Cantera website for a description of the governing equations for specific
```suggestion
//! See the [Reactor Science Section](https://cantera.org/science/reactors/reactors.html)
//! of the %Cantera website for a description of the governing equations for specific
```

2023-07-15 23:46 UTC, ischoegl commented
Thanks, @speth! I believe it's all addressed.

2023-07-16 15:44 UTC, speth approved these changes
Thanks, @ischoegl, this looks good to me.

2023-07-16 15:45 UTC, merged