Limit {fmt} versions
Cantera/cantera pull request #1538
Opened 2023-07-09 18:15 UTC by ischoegl

**Changes proposed in this pull request**

Frequent API changes in the {fmt} library have led to numerous workarounds in `fmt.h`. At the same time, the library is small (especially after [version 7.0](https://github.com/fmtlib/fmt/releases/tag/7.0.0)) and can be easily included from a git submodule.

- Limit support to {fmt} [version 7.1](https://github.com/fmtlib/fmt/releases/tag/7.1.0) and newer (coincides with a switch of floating-point formatting library), where SCons logic ignores older system libraries under the `default` setting.
- Remove *most* workarounds in `fmt.h`
- Test multiple {fmt} version in GH actions

**If applicable, fill in the issue number this pull request is fixing**

Closes #1537, closes #1526

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-07-10 13:09 UTC, speth commented
For Cantera 3.0, I would prefer to maintain compatibility with fmt 6.1.2, which is the version [available on Ubuntu 20.04 LTS](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=libfmt). While using the submodule is reasonably convenient for users compiling on their own systems, it is highly undesirable when building Debian packages.

2023-07-10 15:00 UTC, ischoegl commented
> For Cantera 3.0, I would prefer to maintain compatibility with fmt 6.1.2, which is the version [available on Ubuntu 20.04 LTS](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=libfmt). While using the submodule is reasonably convenient for users compiling on their own systems, it is highly undesirable when building Debian packages.

Alright. I currently don't have a machine to test 6.1.2 (Apple silicon conda refuses to install fmt < 7.1), but I believe the PR by itself is worthwhile even if it does not resolve #1526 (it does fix two other unrelated issues). I set the minimum fmt version to 6.1.2, and removed code that assumed fmt 7.1 capabilities. I'd appreciate if we could merge this before tackling #1526?

2023-07-10 17:11 UTC, speth requested changes
Thanks, @ischoegl. I think this makes sense. I had just a few small suggestions.

2023-07-10 17:11 UTC, speth commented on .github/workflows/main.yml
> +          fmt-ver: 10
I *think* that once you add the `include`, you can remove the `sundials-ver` list above.

I'd also suggest adding the fmt version to the job name above, e.g.
```
name: Sundials ${{ matrix.sundials-ver }} / fmt ${{ matrix.fmt-ver }}
```

2023-07-10 17:11 UTC, speth commented on include/cantera/base/fmt.h
> + #if CT_USE_SYSTEM_FMT
There's a bonus leading space introduced on these lines.

2023-07-10 17:11 UTC, speth commented on .github/workflows/main.yml
> +      run: mamba install -q yaml-cpp mkl highfive fmt=8.1
It would be helpful to mention that specifically, the version needs to match the windows-2022 runner that is selected to upload `cantera_shared.dll`.

2023-07-10 21:04 UTC, ischoegl commented
@speth ... thanks for your comments; everything should be taken care of.

2023-07-10 21:48 UTC, speth requested changes

2023-07-10 21:48 UTC, speth commented on .github/workflows/main.yml
> +          fmt-ver: 7.1
With this one, I think we still need a `python-version` list if we want it to run all the combinations of `python-version` and `vs-toolset`. In the latest CI run, this only ran (VS 14.1, Python 3.11, fmt 7.1) and (VS 14.3, Python 3.11, fmt 7.1).

2023-07-10 22:53 UTC, ischoegl commented
> With this one, I think we still need a `python-version` list if we want it to run all the combinations of `python-version` and `vs-toolset`. In the latest CI run, this only ran (VS 14.1, Python 3.11, fmt 7.1) and (VS 14.3, Python 3.11, fmt 7.1).

Fixed!

2023-07-11 01:06 UTC, speth approved these changes

2023-07-11 01:06 UTC, merged