Switch doxygen documentation theme
Cantera/cantera pull request #1546
Opened 2023-07-18 00:57 UTC by ischoegl

**Changes proposed in this pull request**

Use modern [doxygen-awesome-css](https://jothepro.github.io/doxygen-awesome-css/index.html#autotoc_md10) theme and put details on top via [customized xml layout](https://stackoverflow.com/questions/19831837/documenting-with-doxygen-put-details-on-top)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-07-18 16:18 UTC, ischoegl commented
I added a couple of tweaks that became possible with `DoxygenLayout.xml`, and fixed a couple of formatting glitches I stumbled across. I don't plan on adding anything else, i.e. this is ready for a review.

2023-07-19 14:58 UTC, speth requested changes
Thanks, @ischoegl! This is definitely an improvement over the default styling. While I suspect there are some additional tweaks we may want to make in time, there's just one issue that I think should make now, noted below.

2023-07-19 14:58 UTC, speth commented on doc/doxygen/Doxyfile
I think changing this setting makes the detailed member documentation much worse. For example:

<img width="662" alt="image" src="https://github.com/Cantera/cantera/assets/644977/f57fec19-78c8-4324-ad29-39cd3d352936">

2023-07-19 15:38 UTC, ischoegl commented on doc/doxygen/Doxyfile
Good catch! A lot of this can be fine-tuned by customizing the XML file.

2023-07-19 16:40 UTC, speth approved these changes

2023-07-19 16:41 UTC, merged