Use Doxygen \cite
Cantera/cantera pull request #1550
Opened 2023-07-22 15:43 UTC by ischoegl

**Changes proposed in this pull request**

Use Doxygen `\cite` command to create Bibliography.

**If applicable, provide an example illustrating new features this pull request is introducing**

<img width="1304" alt="image" src="https://github.com/Cantera/cantera/assets/12603999/0feff00f-98ab-4181-89f8-7ab1c7f7a2d2">

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2023-07-27 00:40 UTC, speth requested changes
Thanks, @ischoegl, I think is an improvement, and may encourage better habits for referencing the literature in the future. I had just a couple of comments.

2023-07-27 00:40 UTC, speth commented on src/base/application.h
> +    void use_legacy_rate_constants(bool legacy=false) {
I don't think this makes sense. Regardless of how the default has changed, calling `use_legacy_rate_constants()` should not _disable_ the legacy rate constant approach.

2023-07-27 00:40 UTC, speth commented on include/cantera/transport/IonGasTransport.h
> + * @cite han2015, @cite chiflikian1995, @cite viehland1975.
Here and in a couple other places, I would recommend we follow the style where the numbered references are not read as part of the sentence structure, e.g.
```suggestion
 * References for Stockmayer-(n,6,4) model: Selle and Riedel @cite selle1999, @cite selle2000; 
 * Han et al. @cite han2015; Chiflikian @cite chiflikian1995; and Viehland et al. @cite viehland1975.
```

2023-07-28 16:56 UTC, ischoegl commented
Thanks, @speth ... I believe this is taken care of.

2023-07-28 17:18 UTC, speth approved these changes

2023-07-28 18:06 UTC, merged