Fix issue #1593 in evaluating of lambda at boundary point.
Cantera/cantera pull request #1594
Opened 2023-08-18 04:46 UTC by yeanment

**Changes proposed in this pull request**

- right boundary condition for lambda in evalRightBoundary function

**If applicable, fill in the issue number this pull request is fixing**

Closes #1593

**If applicable, provide an example illustrating new features this pull request is introducing**

Fix the bug of non-uniform lambda for strained flow.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2023-08-18 11:44 UTC, ischoegl requested changes
@yeanment ... thanks for the fix! I had inadvertently added the zero gradient to the wrong branch in #1555. My suggestion won't change results, but shows the BC a little better.

2023-08-18 11:44 UTC, ischoegl commented on src/oneD/StFlow.cpp
> -        rsd[index(c_offset_L, j)] = lambda(x, j);
```suggestion
        rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```
zero gradient

2023-08-18 11:44 UTC, ischoegl commented on src/oneD/StFlow.cpp
> -        rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```suggestion
        rsd[index(c_offset_L, j)] = lambda(x, j);
```
zero (lambda is not used)

2023-08-18 11:44 UTC, ischoegl commented on src/oneD/StFlow.cpp
> +    rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```suggestion
```

2023-08-18 13:07 UTC, yeanment commented
I agree with you. This has minor influence on the solution.

2023-08-19 01:52 UTC, ischoegl commented
@yeanment ... to ensure that the test suite covers this issue, I have suggestions for minor unit test updates, see commit 7b2b855c595d90af8449f398861f7c3f16a43ad2 on https://github.com/ischoegl/cantera/tree/fix-1593 ... feel free to cherry-pick or copy. Also, you can add yourself to the `AUTHORS` list in the main folder (it's alphabetical).

This fix probably should go in before the release of Cantera 3.0. Thanks again for catching this issue as well as creating this PR!

2023-08-21 02:45 UTC, yeanment commented
@ischoegl Thank you for your prompt reply.  I have checked the commit 7b2b855, believe the unit test updates help cover the issue more comprehensively. 

Btw, I am not that familiar with the github workflow. If applicable, you may add me as Shumeng Xie from National University of Singapore. I'm glad I could contribute to this fascinating tool. Thanks again for your effort in maintenance and improvement on this code.

2023-08-21 19:34 UTC, ischoegl commented
> Btw, I am not that familiar with the github workflow. If applicable, you may add me as Shumeng Xie from National University of Singapore. I'm glad I could contribute to this fascinating tool. Thanks again for your effort in maintenance and improvement on this code.

No problem! Unfortunately, I'm unable to add to this PR as your `yeanment/main` branch appears to be protected. The easiest solution is to just accept this PR as is; I will add other changes separately. For future reference, it's best to create a new branch on your repository before creating a PR; that way, you won't run into merge conflicts etc.

2023-08-21 19:35 UTC, ischoegl approved these changes

2023-08-21 19:35 UTC, merged