Reactor net visualization
Cantera/cantera pull request #1624
Opened 2023-09-23 13:12 UTC by Naikless

**Changes proposed in this pull request**

This PR is based on the enhancement I suggested [here](https://github.com/Cantera/enhancements/issues/180). It includes functions and methods to directly visualize components and their connections in a `ReactorNet` or on their own using the `grahpviz` package. 

I wrote the functionality as a standalone module and included the functions as methods in the corresponding objects. If this is considered too intrusive, skipping https://github.com/Cantera/cantera/commit/2ad20c41228c0c531f16a67fc28ec1a87c5de8ae leaves them separated.

Other things I would be happy to receive feedback about:
- For the sake of simplicity, the new cython extension class attributes for the draw options are currently implemented as Python dicts. If this is a performance issue at some point, they could probably also be something more low-level like strings.
- For the "lazy"/optional import of `graphviz` I have copied the behavior found for the `Solution` methods that require `pandas`. I don't know if this is still best practice.
- I don't know if I have sufficiently adhered to the preferred import pattern in `__init__.py`.
- unit tests are missing yet. Should they just be part of the `TestReactor` class?

**If applicable, fill in the issue number this pull request is fixing**

Closes https://github.com/Cantera/enhancements/issues/180

**If applicable, provide an example illustrating new features this pull request is introducing**

- Adds functions and methods based on them that can draw `ReactorBase`, `WallBase` and `FlowDevice` objects
  ```python
  gas = ct.Solution('h2o2.yaml')
  r = ct.Reactor(gas)
  r.draw()
  ```
  ![image](https://github.com/Cantera/cantera/assets/44439108/43758699-710b-4244-b81c-89340c6a4c34)
  ```python
  r2 = ct.Reactor(gas)
  w = ct.Wall(r,r2,U=0.1)
  w.draw()
  ```
  ![image](https://github.com/Cantera/cantera/assets/44439108/ed297aa3-bac8-42bd-a132-2e6051f935e5)
 (not defining a phase for the reactors causes `Wall` to throw an Access Violation, as reported [here](https://github.com/Cantera/cantera/issues/1623))

- Reactors can be drawn plain or with their current state (T, P, composition) displayed 
   ```python
  r.draw()
  ```
  ![image](https://github.com/Cantera/cantera/assets/44439108/f411913e-8079-4927-9043-584ead3bbdf3)
   ```python
  r.draw(print_state=True, species='X')
  ```
  ![image](https://github.com/Cantera/cantera/assets/44439108/4f17dd1c-ee44-4abe-9c10-124e7293e544)
- Detects all connections between these objects and draws them as arrows. Corresponding mass and heat flows are added as labels. Connections between identical objects are summed up. Here is the visualization of the `ic_engine.py` sample:
![image](https://github.com/Cantera/cantera/assets/44439108/39cf5c73-e64e-42c5-9f7b-6a42a77a644d)
- The style of these elements can be fully customized using `graphviz` regular `node_attr` and `edge_attr` keywords. This can be done either generally when calling the `draw` function or individually for each object by setting corresponding attributes, in which case the latter takes precedence:
  ```python
  r.node_attr={"color":"red"}
  r.draw(node_attr={"color":"green", "shape":"square"})
  ```  
  ![image](https://github.com/Cantera/cantera/assets/44439108/a3ce02ab-199d-4ecc-a9d2-b75fcbb9844b)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) 
- [ ] unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2023-09-23 13:43 UTC, Naikless commented
Whoopsi, that's a lot of trailing whitespaces. Is it best practice to do a cleanup commit or should I try to rework them into the existing commits?

2023-09-23 16:09 UTC, bryanwweber commented
Thank you! This is very cool

> do a cleanup commit

A cleanup commit is fine 😁

2023-09-23 16:43 UTC, speth commented
I think the issue is mainly that `drawnetwork.py` has Windows (CRLF) line endings, which triggers that warning on every line. If you're comfortable fixing that as part of a rebase, I think it would make the history a bit cleaner.

2023-09-24 00:52 UTC, speth requested changes
Thanks, @Naikless, this is a really nice contribution, and addresses a feature request that I know has been made by many users.

To answer your questions:
- Using `dict`s for `Reactor.node_attr` and the like are a fine way of storing styling information. The only thing I might suggest changing is the name, since talking about "nodes" and "edges" really only makes sense if you understand that this is a graph in the mathematical sense. One alternative that comes to mind is `appearance`, which would work for both reactors and flow devices.
- The lazy import of `graphviz` looks good to me
- I think you can just omit the imports in `__init__.py`, leaving the member functions as the main API.
- I'd suggest adding the tests to `test_reactor.py`, but I'm guessing you'll want to configure some different reactor networks than the ones that it uses, so you probably want to create a separate `TestDrawNetwork` or similar class.

Some additional comments:
- A way of including `ReactorSurface` objects would be useful
- Is there a way to indicate wall motion? I guess at some level, this is a transfer of volume from one reactor to another, though it might look a little funny.
- It would be good add some example usage. I was going to suggest adding this to some of the existing examples, but most of them have almost trivial network structures. I guess `mix1.py` at least has a reactor with two inlets and one outlet. `ic_engine.py` has two inlets as well, but it's less clear what the right thing to show would be, given the transients that it's simulating.
- The fact that `ReactorNet.draw()` plays nicely with Jupyter is great.
- I think you need to add a couple of entries in `zerodim.rst` so the standalone functions will be included in the API docs.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/__init__.py
>  import cantera.interrupts  # Helps with standalone packaging (PyInstaller etc.)
I think these functions will get pulled in automatically by the above `from ._cantera import *`, since they are also imported in `reactor.pyx`.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        raise ImportError("This requires the graphviz package.")
I struggled with this a bit since the relevant Conda package is `python-graphviz`. It might be worth noting the relevant package name for pip and conda.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +    The node is added to an existing ``dot`` graph if provided.
For Cantera type and methods, these should be single-backticks, so they will be linked to the corresponding documentation.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +                              graph_attr=kwargs.get("graph_attr"))
The f-string for `r.name` is unnecessary

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +                         label="{"+ T_label +"|"+ P_label +"}"+"|"+ s_label,
It's probably worth using an f-string here, even though you have to double the `{` and `}` to escape them.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +            X = r.thermo.mole_fraction_dict()
If you're cropping the displaced concentrations to 0.01% (which seems reasonable), you might want to call this with a threshold of 1e-4.

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        node_attr = {k:v for k,v in node_attr.items() if k != "shape"}
More simply:
```suggestion
        node_attr.pop("shape", None)
```

2023-09-24 00:52 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +            itself have priority.
For the more "public" API (here and for `ReactorNet.draw`), I think it would be better to add all of these arguments explicitly to the function signature. You're welcome to specify that they are keyword-only if you like.

Also, on at least one of these functions (perhaps `ReactorNet.draw`), it would help to provide some examples that use a few common attributes, and to link to more detailed documentation of all the supported attributes in the `graphviz` documentation. Then, you can reference that method from the others as something to "see also".

2023-09-24 13:42 UTC, Naikless commented
Thanks for the encouragement and the review. I'll try get to it in the next days. 

Just before I get started and not to over engineer this, but this is my first code review process: 
Is it preferable to address the requested changes as commits or as part of a rebase? 
Intuitively, I would try to incorporate trivial fixes like trailing whitespace into the original commits while creating new commits for stuff that might warrant a discussion/documentation.

And also to already address one of your suggestions @speth: 
I initially had the `..._attr` dicts name `..._style` out of a similar desire to make it more obvious what they are for. But then I considered it advantageous to name them exactly as their internal graphviz counterparts to stress that they are a 1:1 representation and make it easy for people to look up existing keywords in the graphviz docs.

2023-09-24 15:37 UTC, speth commented
> Just before I get started and not to over engineer this, but this is my first code review process: Is it preferable to address the requested changes as commits or as part of a rebase? Intuitively, I would try to incorporate trivial fixes like trailing whitespace into the original commits while creating new commits for stuff that might warrant a discussion/documentation.

We don't have a hard-and-fast rule on this. I tend to prefer squashing certain changes if it makes the history cleaner, and `git commit --fixup=...` makes this pretty easy most of the time. But if you find yourself having to resolve merge conflicts during a rebase, it might not be worth it.

> 
> And also to already address one of your suggestions @speth: I initially had the `..._attr` dicts name `..._style` out of a similar desire to make it more obvious what they are for. But then I considered it advantageous to name them exactly as their internal graphviz counterparts to stress that they are a 1:1 representation and make it easy for people to look up existing keywords in the graphviz docs.

It's definitely worth mentioning the corresponding `graphviz` names for these in the docstrings. Though if I understand this correctly, for the Cantera user, the API of the Python `graphviz` package isn't all that relevant. All they need to know is the options allowed by the underlying Graphviz "language", as defined by https://graphviz.org/doc/info/attrs.html. Is that correct?

2023-09-29 01:15 UTC, Naikless commented on interfaces/cython/cantera/__init__.py
>  import cantera.interrupts  # Helps with standalone packaging (PyInstaller etc.)
Alright, removed these imports

2023-09-29 01:15 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +    The node is added to an existing ``dot`` graph if provided.
Adjusted formatting in original commits.

2023-09-29 01:16 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +                              graph_attr=kwargs.get("graph_attr"))
Fixed.

2023-10-07 13:26 UTC, Naikless commented
Any hints on how to get code coverage data reported from my fork? 

The CI workflow exits with:
```
[2023-10-06T02:56:32.833Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
[2023-10-06T02:56:32.834Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
    at main (/snapshot/repo/dist/src/index.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-10-06T02:56:32.834Z] ['verbose'] End of uploader: 1903 milliseconds
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```

My local machine is a Windows so I can't really get these information here either.

2023-10-07 14:58 UTC, speth commented
It is supposed to work without a token, but Codecov seems to have occasional hiccups that require re-running the job. I just triggered a new run, which will hopefully work.

2023-10-07 15:35 UTC, Naikless commented
Thanks. My workaround using an additional branch on my fork worked as well. The PR ist still WIP, I just wanted to check which spots I missed in my unit tests.

How do I have to invoke pytest to test the python modules locally? Simply calling `pytest` will either produce coverage of the test files themselves when run from cantera root dir or won't find any test when run from the local build.

2023-10-07 16:58 UTC, speth commented
The recommended way to run the tests is through SCons, e.g. `scons test-python` if you just want to run the Python tests. If you want to run pytest directly, e.g. `pytest test/python` from the root directory, you need to make sure `PYTHONPATH` is set to the built copy of the module. If you're running with coverage enabled, I think this will inevitably count the test code itself. For Codecov, we just exclude it in the upload step (see the "coverage" job in `.github/workflows/main.yml`).

I find getting coverage reports to be finicky enough that I usually just rely on the GitHub Actions / Codecov build.

2023-10-08 20:56 UTC, Naikless commented
> It's definitely worth mentioning the corresponding `graphviz` names for these in the docstrings. Though if I understand this correctly, for the Cantera user, the API of the Python `graphviz` package isn't all that relevant. All they need to know is the options allowed by the underlying Graphviz "language", as defined by https://graphviz.org/doc/info/attrs.html. Is that correct?

That is correct. However, I thought about this once more: If each function only had a single Dict for these options, I would agree that naming it `appearance` or `draw_style` would be better suited. But all of them distinguish between `node_attr`, `graph_attr` and `edge_attr` dictionaries which flow into the graphviz API at different places and can contain the same keys with different values such as `color`. So the differentiation between "nodes" (reactors, reservoirs, most likely also reactor surfaces) and "edges" (mass flow controllers, walls) must be made regardless of the fact that the graphviz API is not accessed directly. In light of this, I believe sticking with the graphviz names for these dictionaries is the most straightforward choice.

2023-10-12 01:46 UTC, Naikless commented
Sorry, I didn't mean to close here but something went weird with the branch at my fork and I couldn't solve it without deleting it and pushing it again.
Is it possible to restore the connection here or do I have to open a new PR?

2023-10-12 11:09 UTC, bryanwweber commented
I think you just have to make a new PR, GitHub doesn't allow reconnecting to closed PRs once the branch is deleted as far as I know.

2023-10-13 23:48 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +        raise ImportError("This requires the graphviz package.")
I included more detailed installation instructions in the raised `ImportError`.

2023-10-13 23:48 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +                         label="{"+ T_label +"|"+ P_label +"}"+"|"+ s_label,
done.

2023-10-13 23:48 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +            X = r.thermo.mole_fraction_dict()
done.

2023-10-13 23:49 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +        node_attr = {k:v for k,v in node_attr.items() if k != "shape"}
done.

2023-10-16 15:42 UTC, Naikless commented on interfaces/cython/cantera/reactor.pyx
> +            itself have priority.
I made the various keyword arguments explicit in the class methods and in the exported functions.
I haven't added any usage examples yet, I figured this would come at the last step when everything else is agreed upon.

2023-10-16 16:50 UTC, Naikless commented
Alright, I believe I have added all the functionality now that would make sense in my eyes. 
I also included `ReactorSurface` objects and wall movement. 

The representation of the latter currently looks like this:

```python
import cantera as ct
gas = ct.Solution('h2o2.yaml')
r = ct.Reactor(gas)
surf = ct.Interface('methane_pox_on_pt.yaml', 'Pt_surf')
s = ct.ReactorSurface(kin=surf, r=r)
s.draw()
```
![image](https://github.com/Cantera/cantera/assets/44439108/2bdb318c-4648-4d46-aa8d-0d5f966e6d1e)

```python
r2 = ct.Reactor(gas)

w = ct.Wall(r, r2, velocity=1)
w.draw()
```
![graph0](https://github.com/Cantera/cantera/assets/44439108/9ed8c289-68dd-4726-baef-cd48de5217d3)

(Although it seems the little arrow at the wall sometimes isn't rendered.)

I also added the possibility to group reactors using a `groupname` attribute:

```python
r3 = ct.Reactor(gas, groupname='group 1')

r.groupname = 'group 1'

net = ct.ReactorNet((r, r2, r3))
net.draw()
```

![image](https://github.com/Cantera/cantera/assets/44439108/d56ebd75-ab69-4c13-a435-ffa827788939)

(Note that automatic reactor names increase regardless of the fact that reactors are repeatedly created)

Because a reactor's name defines its identity in the graphviz output, I had to ensure that each reactor is drawn with a unique name. However, until now there was nothing preventing people from giving the same name to multiple reactors and enforcing this now would be a potential breaking change. 
This added some additional complexity to how the functions interact with each other and the necessity to create a dictionary that saves all reactor names during an "external" function call. But I believe the solution works quite well.


So, from my point of view, the code is ready for another review.

What I haven't adressed yet:

- examples. I consider this to be the last step once everything else is sorted out.
- additional doc entries for the standalone functions. Since I would agree that access through the class methods is the main use case, I am not sure if adding redundantly documented standalone functions with the same functionality would be confusing.

2023-10-18 18:40 UTC, speth requested changes
Thanks for these updates, @Naikless. I think this PR is looking pretty good. I'm looking forward to an update that includes at least one example. Besides the specific inline comments, I had a couple of other observations:
- I would be fine requiring that all Reactors in a network have unique names, at least for the purpose of using `ReactorNet.draw` (that is, you can just check for duplicates at the start of this method). In this case, it wouldn't be a breaking change since it only affects this new method. As it is, I think it's pretty uncommon for anyone to assign a name to a Reactor, since it isn't currently used for anything, which means that the default names will be unique. This should simplify things a bit and remove the need for some of the wrapper methods.
- I don't quite understand what the intended formatting for showing the wall velocity is supposed to be. It looks a little funky in all cases I tried, with the label always overlapping the symbol. I think there should be a line connecting the two reactors, since the wall velocity affects both of them, not just the one that is expanding. One thing that might help with this formatting is if we don't draw the heat transfer arrow in the case where Q = 0 and the wall's only role is in terms of the velocity.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        reactor connections. ``edge_attr`` defined in the connection objects
In several locations:
```suggestion
        (subclasses of `FlowDevice` or walls) themselves have priority.
```

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +    kwargs = locals()
I think it's worth keeping things a little bit simpler, if slightly more verbose, and explicitly passing the relevant parameters to `_draw_reactor` and `_draw_surface`.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        except AttributeError:
I think it would be more clear to just keep separate lists of flow device connections and wall connections. Or perhaps even to just build the `connected_reactors` structure directly in `draw_reactor_net`.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +            break
I think you can do just:
```suggestion
    while connections:
        c = connections.pop()
```

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +                - sum(getattr(c, rate_attr) for c in inv_duplicates))
The fact that `c` means three different things in this statement is somewhat confusing.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +                            **(kwargs.get("wall_edge_attr") or {})})
I think as written, it's impossible for anything in `wall_edge_attr` to override any of the pre-defined style variables. Also, I think `wall_edge_attr` is missing from both `draw_reactor_net` and `ReactorNet.draw`.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +            r_in, r_out = getattr(c, inflow), getattr(c, outflow)
I would suggest avoiding the `try`/`except` logic here and throughout this method, as it obscures the reason for the two branches -- it's more clear if the branch is determined with something like `isinstance(c, FlowDevice)`.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        If not provided, a new ``DiGraph`` is created. Defaults to ``None``.
I'd suggest `graph` as a less obscure variable name than `dot` almost universally.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +        """
Please add
```python
        .. versionadded:: 3.1
```
to all the new, public functions/properties added.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +            self.groupname = ""
This can be simplified by just having the default value for `groupname` be `""`, right?

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +        """
There are a couple of indentation errors here that cause some strange formatting in the Sphinx documentation (with certain sections being rendered as block quotes). I believe this is the cause of the failure in the doc builds.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pxd
> +    cdef public dict node_attr
To document these public member variables in the Sphinx docs, you can add a docstring starting on the line immediately after the declaration here, e.g.
```cython
    cdef public dict node_attr
    """
    A dictionary containing...
    """
```

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pxd
> +    cdef public str groupname
This should probably be `group_name`.

2023-10-18 18:40 UTC, speth commented on interfaces/cython/setup.cfg.in
> +graphviz = python-graphviz
I'm unclear on how this gets used/interpreted. The PyPI package is just named `graphviz`, while the Conda package is named `python-graphviz` (at least, in the `conda-forge` channel; I'm not sure it's available via the `defaults` channel). Maybe @bryanwweber can help here?

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +            Group reactors of the same ``groupname`` when drawn using graphviz.
Likewise here, `group_name` (or perhaps just `group`).

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +            self.node_attr = {'shape': 'underline'}
```suggestion
        self.node_attr = node_attr or {'shape': 'underline'}
```

2023-10-18 18:40 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +    reactors.difference_update(drawn_reactors)
I'd recommend the operator notation here (and a couple other places):
```suggestion
    reactors -= drawn_reactors
```

2023-10-19 22:25 UTC, Naikless commented
Thanks again for the review! I'll see to the suggested changes as soon as I can. 

Quick question to potentially speed up my development: 
Is it possible to only run specific python tests using the scons command? Because some of them take a moment and in most cases I am working on it would suffice to just run the `test-reactor` module.

2023-10-19 22:35 UTC, speth commented
> Is it possible to only run specific python tests using the scons command?

Yes, you can run just the reactor tests with `scons test-python-reactor`.

It is also possible to run tests outside of SCons by running pytest directly, in which case you can filter tests using its `-k` option. However, this likely requires fiddling around with the `PYTHONPATH` and `LD_LIBRARY_PATH` (on Linux) environment variables.

2023-10-25 23:32 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +    kwargs = locals()
done.

2023-11-19 23:04 UTC, Naikless commented on interfaces/cython/cantera/drawnetwork.py
> +        reactor connections. ``edge_attr`` defined in the connection objects
Sorry, is this just about the missing "s" from "themselves" or were you suggesting additional changes here?

2023-11-20 04:06 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +        reactor connections. ``edge_attr`` defined in the connection objects
Yes, I think that's all I was commenting on. Sorry for any confusion.

2023-11-22 00:31 UTC, Naikless commented on interfaces/cython/cantera/reactor.pyx
> +            self.node_attr = {'shape': 'underline'}
There are quite a view occasions of the above if-else logic throughout reactor.pyx. Although your suggestion is more elegant, is there a problem here in terms of consistency? Or should the other occasions be similarly adapted in time?

2023-11-22 00:54 UTC, Naikless commented on interfaces/cython/setup.cfg.in
> +graphviz = python-graphviz
You are right. As far as I understand, setup.py and setup.cfg.in are only relevant for creating a pip package and have nothing to do with conda. If that is indeed the case, it should be only `graphviz`.

2023-11-22 00:59 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +            self.node_attr = {'shape': 'underline'}
Up to you -- I'm not too worried about it either way.

2023-12-14 09:35 UTC, Naikless commented
Thank you for your patience, implementing the changes again took me much longer than anticipated. Or I am just very bad at anticipating.

You can have another look if you like. Replacing the logic for renaming the objects if they share the same name with a simple assertion as well as splitting the branches for walls and flow controllers into their own functions hopefully made things a bit more concise.

I still get some error when compiling the docs. Is it still the formatting?

2024-01-05 22:46 UTC, speth approved these changes
Thanks for the updates, @Naikless. I made a few fixes to the formatting of the documentation, so I think this is good to go assuming the CI completes without error.

2024-01-06 01:28 UTC, merged

2024-01-06 10:38 UTC, Naikless commented
Thanks a lot for merging this! Although I realize that the 3.0 release was quite recently, is there already a rough time frame for the next (pre-) release?