Extensible jacobian and network jacobian interfaces
Cantera/cantera pull request #1634
Opened 2023-10-17 17:41 UTC by anthony-walker

**Changes proposed in this pull request**

In this pull request I have setup basic structure for adding contributions to the jacobian from flow devices and walls.
I have also added an extensible jacobian interface to the `ExtensibleReactor` system and modified the existing jacobian system to pass a vector of triplets as is needed in lieu of creating a large number of separate sparse matrices. 

@speth @ischoegl some additional tests are needed for the wall and flow contributions but I wanted to get the content officially into a PR.

- Jacobian contributions from walls and flow devices
- Extensible jacobian interface
- Enhancements to existing jacobian backend

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2023-10-24 17:35 UTC, anthony-walker commented
@speth @ischoegl I am not entirely sure why the `.NET` tests are failing but it doesn't seem to be with this PR, is this a known issue?

Otherwise I believe this code is ready for review.

2023-10-24 20:36 UTC, ischoegl reviewed
While I don't have enough experience in extensible things for a complete review, I noticed that a lot of test are failing with:
```
*******************************************************************************
NotImplementedError thrown by MassFlowController::buildReactorJacobian:
Not implemented.
*******************************************************************************
```
which doesn't appear to be .NET related.

2023-10-24 22:21 UTC, anthony-walker commented
@ischoegl these failures are from my latest bug fixes there is a separate commit which addresses the `.NET` failure issue.

2023-12-22 17:17 UTC, speth commented
Before you get any further, I just wanted to suggest undoing the merge commit and rebasing onto the current `main` branch instead.

2024-03-10 03:00 UTC, speth requested changes
Thanks for putting this together, @anthony-walker. I think it helps in laying out the necessary pieces for handling the cross-reactor terms in the Jacobian -- in particular, the mechanics surrounding `Wall::buildNetworkJacobian` seem like a good basis to keep building on.

I think there is some room for simplification of this structure, which I've left specific comments on. However, I think there is a significant issue with sorting out exactly which derivatives need to be computed and what the right formulas are for the different cases. The challenge I see us needing to resolve to generalize this across the different reactor types is that what derivative is needed for a single interaction (for example, wall heat transfer) depends on *both* reactor types and what variables they use to represent each term, and we need a way of selecting the correct formula for each Jacobian element based on that pair of reactor types.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/FlowDevice.h
> +    //! @since New in %Cantera 3.0.
Here and elsewhere:
```suggestion
    //! @since New in %Cantera 3.1.
```

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
> +    }
I find the name for this function fairly confusing -- Nothing in the name indicates that this is the derivative of the temperature. For consistency with how we named the derivative methods in `Kinetics`, I'd recommend `temperature_ddni`.

Regarding the docstring, nothing in this method is specific to the "heat transfer equation".

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
> +    }
I don't think this method should be necessary. You can compute $d(T^4)/dn_i$ using the chain rule as $4T^3 dT/dn_i$.

2024-03-10 03:00 UTC, speth commented on src/zeroD/IdealGasMoleReactor.cpp
> +    return dTdni;
This is a lot of repeated memory allocations and repeated calculations when all you really want is the total number of moles. The simpler way to calculate this is just
`n_total = m_mass / m_thermo->meanMolecularWeight()`.

2024-03-10 03:00 UTC, speth commented on src/zeroD/IdealGasMoleReactor.cpp
> +    buildFlowJacobian(jacVector);
The comments here add nothing

2024-03-10 03:00 UTC, speth commented on src/zeroD/IdealGasConstPressureMoleReactor.cpp
> +    return dTdni;
Likewise here, the calculation of the total number of moles can be done more efficiently.

2024-03-10 03:00 UTC, speth commented on test/python/conftest.py
> +        return
What does this do? How is this used? If this is adding new ways of selectively running tests, I think it should be documented in the developer docs (a page under `doc/sphinx/develop`)

2024-03-10 03:00 UTC, speth commented on src/zeroD/Reactor.cpp
> +    }
Minor, but the line wrapping here is unnecessary.

As a broader question, though, why would you want to skip these Jacobian elements? Is there a case-dependent performance implication?

2024-03-10 03:00 UTC, speth commented on src/zeroD/Reactor.cpp
> +void Reactor:: buildWallJacobian(vector<Eigen::Triplet<double>>& jacVector)
Minor formatting error:
```suggestion
void Reactor::buildWallJacobian(vector<Eigen::Triplet<double>>& jacVector)
```

2024-03-10 03:00 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +            }
Rather than having to toggle this flag on every wall and flow device each time the Jacobian is evaluated, I think it would make more sense to have the `ReactorNet` store a set of `Wall*` and `FlowDevice*` as part of `initialize()`, where the `set` will automatically take care of deduplication.

2024-03-10 03:00 UTC, speth commented on src/zeroD/ReactorNet.cpp
>      }
The inefficiency of having to copy the Jacobian elements here is a bit unfortunate. The best alternative I can think of is that the preconditioner should to provide access to its triplet vector, so you can pass that into `buildJacobian` directly rather than needing the temporary `jacVector` here.

2024-03-10 03:00 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    if (! m_init) {
```suggestion
    if (!m_init) {
```

2024-03-10 03:00 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    vector<Eigen::Triplet<double>> jac_trips;
Comment seems incorrect.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +    double scalar = (r == m_left) ? 1.0 : -1.0;
I think `direction` would be a better name -- this is more like a unit vector than a scalar.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +        jacVector.emplace_back(eidx, i, dQdni);
The Jacobian element is equal to $dQ/dn_i$ only if $U$ or $H$ is the state variable for the energy equation. However, for both `IdealGasMoleReactor` and `IdealGasConstPressureMoleReactor`, the energy equation is in terms of temperature.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +    size_t r_net = m_right->network().globalStartIndex((Reactor* ) m_right);
To avoid the need for the cast here, I think we should modify `ReactorNet::globaStartIndex` to take a `ReactorBase*`. It will raise an exception if a `Reservoir` is provided as the input here, which is fine.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +    if (((Reactor* ) m_right)->energyEnabled()) {
To avoid the need for this cast, let's move `energyEnabled` up to the `ReactorBase` class as a virtual method.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +            jacVector.emplace_back(r_eidx + r_net, i + l_net, dQdni);
Again, this derivative is not correct for the reactors that use T as the state variable.

2024-03-10 03:00 UTC, speth commented on src/zeroD/Wall.cpp
> +            jacVector.emplace_back(l_eidx + l_net, i + r_net, dQdni);
Besides the energy equation, `Wall` objects can also affect the volume equation for the reactor, if an expansion coefficient has been set, and those terms also need to be added to the Jacobian.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    //! @param jacVector a vector of triplets to be added to the jacobian for the
"Jacobian" should always be capitalized.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    //! or removed without notice.
The line wrapping here is kind of odd. Please fix it here and in the other instances of the same.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    }
Please wrap lines longer than 88 characters, here and elsewhere.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    //! will be adjusted to the networks indexing system outside of the reactor.
This is incorrect, isn't it? The determination of the global component indices is done in this method. Only `buildReactorJacobian` uses local component indices. Also, I think it needs to be more clear that this method is only computing the cross-reactor terms.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    //! reactor
What reactor?

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Wall.h
> +
You don't need to specify `virtual` on methods that are marked as `override`.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +    }
The body of this method is too much for a header file, and should be moved to the `.cpp` file.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +    virtual void buildFlowJacobian(vector<Eigen::Triplet<double>>& jacVector);
Given the need for `Wall::buildNetworkJacobian` and `FlowDevice::buildNetworkJacobian` to handle cross-reactor terms, I'm wondering if these methods have much value. At the reactor network level, you already have to (effectively) loop over each `Wall` and `FlowDevice` to get their contributions, so you might as well compute the "local" terms there as well.

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/FlowDevice.h
> +    }
Is there currently no implementation of this method for any flow device?

2024-03-10 03:00 UTC, speth commented on include/cantera/zeroD/ReactorNet.h
> +        return npos;
The `return` statement after `throw` is unnecessary.

This method is too long to for the header file -- basically anything that isn't a one-liner should be in the `.cpp` file.

2024-03-10 03:00 UTC, speth commented on interfaces/cython/cantera/_utils.pyx
> +    return dereference(trip_ptr)
This looks like a serious memory leak -- every call allocates a new `trip_ptr` that will never be deleted.

2024-03-10 03:00 UTC, speth commented on interfaces/cython/cantera/delegator.pyx
>          cxx_name = stringify(options[0])
Blank line here shouldn't have been deleted.

2024-03-10 03:00 UTC, speth commented on src/zeroD/IdealGasMoleReactor.cpp
> +    double dTdni = pressure() * m_vol / GasConstant / std::accumulate(moles.begin(), moles.end(), 0.0);
I think there's a significant conceptual problem here: This is calculating the derivative of $T$ with respect to $n_i$ assuming that $p$ is held constant. However, for this reactor type, $T$ is one of the independent variables -- a change in $n_i$ will not change $T$, but will instead result in a change in $p$.

2024-03-10 03:00 UTC, speth commented on src/zeroD/IdealGasConstPressureMoleReactor.cpp
> +    double dTdni = pressure() * m_vol / GasConstant / std::accumulate(moles.begin(), moles.end(), 0.0);
Like in `IdealGasMoleReactor`, $T$ is an independent variable. Here, a change in $n_i$ will change the volume, not the temperature.

2024-03-10 03:00 UTC, speth commented on test/python/test_reactor.py
> +                assert np.isclose(jac[r1.n_vars, i + 1 + r1.n_vars], - U * A * gas2.T, rtol=1e-2)
I think you should check against the finite difference Jacobian. This test is just checking against the same incorrect formulas in Python as what's in the C++ implementation.

2024-03-10 03:00 UTC, speth commented on test/python/test_reactor.py
> +        r2.chemistry_enabled = False
The analytical Jacobian doesn't currently respect the `chemistry_enabled` flag, so there are a lot of non-zero elements here that should be zero based on the setting of this flag.

2024-03-10 03:00 UTC, speth commented on test/zeroD/test_zeroD.cpp
> +            EXPECT_DOUBLE_EQ(it.value(), 6000.0);
What are "appropriate" values? Why should these elements equal 6000?

2024-03-10 03:00 UTC, speth commented on test/zeroD/test_zeroD.cpp
> +TEST(JacobianTests, test_flow_jacobian_build)
I think this needs to be more clear that the flow device Jacobian elements are currently not implemented.

2024-03-10 20:52 UTC, speth commented
For an example of where the current derivatives are clearly not correct, consider the following example, adapted from one of your new tests:
```py
import cantera as ct
import numpy as np

# create first reactor
gas1 = ct.Solution("h2o2.yaml", "ohmech")
gas1.TPX = 600, ct.one_atm, "O2:1.0"
r1 = ct.IdealGasMoleReactor(gas1)
r1.name = 'R1'
gas1.set_multiplier(0.0)

# create second reactor
gas2 = ct.Solution("h2o2.yaml", "ohmech")
gas2.TPX = 300, ct.one_atm, "O2:1.0"
gas2.set_multiplier(0.0)
r2 = ct.IdealGasMoleReactor(gas2)
r2.name = 'R2'

# create wall
U = 500.0
A = 3.0
w = ct.Wall(r1, r2, U=U, A=A)
net = ct.ReactorNet([r1, r2])

def print_jac(J):
    for i,j in zip(*np.nonzero(J)):
        name_i = net.component_name(i).replace('temperature', 'T')
        name_j = net.component_name(j).replace('temperature', 'T')
        net.component_name(i).replace('temperature', 'T')
        #print(f"J[{i: 3d}, {j: 3d}] = {J[i,j]:.3e}")
        print(f"J[{name_i:8s}, {name_j:8s}] = {J[i,j]:.3e}")

print('Semi-analytical Jacobian:')
print_jac(net.jacobian)
print('\nFinite difference Jacobian:')
print_jac(net.finite_difference_jacobian)
```
which outputs:
```
Semi-analytical Jacobian:
J[R1: T   , R1: T   ] = -2.727e+00
J[R1: T   , R1: H2  ] = 9.000e+05
J[R1: T   , R1: H   ] = 9.000e+05
J[R1: T   , R1: O   ] = 9.000e+05
J[R1: T   , R1: O2  ] = 9.000e+05
J[R1: T   , R1: OH  ] = 9.000e+05
J[R1: T   , R1: H2O ] = 9.000e+05
J[R1: T   , R1: HO2 ] = 9.000e+05
J[R1: T   , R1: H2O2] = 9.000e+05
J[R1: T   , R1: AR  ] = 9.000e+05
J[R1: T   , R1: N2  ] = 9.000e+05
J[R1: T   , R2: H2  ] = -4.500e+05
J[R1: T   , R2: H   ] = -4.500e+05
J[R1: T   , R2: O   ] = -4.500e+05
J[R1: T   , R2: O2  ] = -4.500e+05
J[R1: T   , R2: OH  ] = -4.500e+05
J[R1: T   , R2: H2O ] = -4.500e+05
J[R1: T   , R2: HO2 ] = -4.500e+05
J[R1: T   , R2: H2O2] = -4.500e+05
J[R1: T   , R2: AR  ] = -4.500e+05
J[R1: T   , R2: N2  ] = -4.500e+05
J[R2: T   , R1: H2  ] = 9.000e+05
J[R2: T   , R1: H   ] = 9.000e+05
J[R2: T   , R1: O   ] = 9.000e+05
J[R2: T   , R1: O2  ] = 9.000e+05
J[R2: T   , R1: OH  ] = 9.000e+05
J[R2: T   , R1: H2O ] = 9.000e+05
J[R2: T   , R1: HO2 ] = 9.000e+05
J[R2: T   , R1: H2O2] = 9.000e+05
J[R2: T   , R1: AR  ] = 9.000e+05
J[R2: T   , R1: N2  ] = 9.000e+05
J[R2: T   , R2: T   ] = -1.887e+00
J[R2: T   , R2: H2  ] = -4.500e+05
J[R2: T   , R2: H   ] = -4.500e+05
J[R2: T   , R2: O   ] = -4.500e+05
J[R2: T   , R2: O2  ] = -4.500e+05
J[R2: T   , R2: OH  ] = -4.500e+05
J[R2: T   , R2: H2O ] = -4.500e+05
J[R2: T   , R2: HO2 ] = -4.500e+05
J[R2: T   , R2: H2O2] = -4.500e+05
J[R2: T   , R2: AR  ] = -4.500e+05
J[R2: T   , R2: N2  ] = -4.500e+05

Finite difference Jacobian:
J[R1: T   , R1: T   ] = -2.727e+00
J[R1: T   , R1: O2  ] = 4.589e+04
J[R1: T   , R2: T   ] = 3.107e+00
J[R2: T   , R1: T   ] = 1.752e+00
J[R2: T   , R2: T   ] = -1.887e+00
J[R2: T   , R2: O2  ] = -1.294e+04
```

2024-04-07 13:39 UTC, anthony-walker commented on test/python/conftest.py
> +        return
This is to isolate python tests. I will add to docs.

2024-04-07 14:22 UTC, anthony-walker commented on src/zeroD/Wall.cpp
> +    if (((Reactor* ) m_right)->energyEnabled()) {
@speth I think it would make sense to move chemistryEnabled in the same way for consistency.

2024-06-03 18:08 UTC, anthony-walker commented
@speth apologies for the delay, I have made some updates but still need to do some of the larger changes. It is still on my radar.

2024-07-05 16:06 UTC, anthony-walker commented on src/zeroD/Reactor.cpp
> +    }
That is a good question, I believe depending on the flow device there could be performance implications.

2024-07-05 19:44 UTC, anthony-walker commented on include/cantera/zeroD/Reactor.h
> +    virtual void buildFlowJacobian(vector<Eigen::Triplet<double>>& jacVector);
My thought was when an individual wants to access a reactor only Jacobian.

2024-07-05 19:44 UTC, anthony-walker commented on include/cantera/zeroD/FlowDevice.h
> +    }
There is not one currently.

2024-07-05 20:31 UTC, anthony-walker commented
@speth pushed up some more changes, I will have to put a bit of thought into some of the other changes.

2026-05-08 22:19 UTC, ischoegl commented
Superseded by #2113.

2026-05-08 22:19 UTC, closed without merging