add __call__ method to with_units
Cantera/cantera pull request #1650
Opened 2023-12-07 19:09 UTC by mefuller

**Changes proposed in this pull request**

add `__call__` to `cantera.with_units` solutions (closes #1649)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

2023-12-11 03:21 UTC, bryanwweber requested changes
Thanks @mefuller! Can you back out the formatting-only changes here? We intentionally don't follow black's formatting.

2023-12-11 04:05 UTC, mefuller commented
@bryanwweber oops - forgot that was turned on at work - meant to get back to this anyway at home, so here is the corrected commit

Looks like this doesn't actually fix the problem and I'm not sure why (I did a `scons build/test/install` and I still get the same bug - any ideas as to what I did wrong (I definitely don't understand 100% what's going on here in any case)

2023-12-11 14:20 UTC, bryanwweber commented
@mefuller can you open up the generated `solution.py` in the build folder? That'll show you the actual code being run. I also edited my comment above with a suggestion for the implementation

2023-12-12 13:55 UTC, bryanwweber commented on site_scons/site_tools/UnitsInterfaceBuilder.py
> +            return self._phase.report(bool(show_thermo), threshold)
Since this is also just a passthrough, you can use *args and **kwargs like __call__

2023-12-12 14:58 UTC, mefuller commented on site_scons/site_tools/UnitsInterfaceBuilder.py
> +            return self._phase.report(bool(show_thermo), threshold)
thanks @bryanwweber - I always really appreciate your assistance and time

2023-12-13 16:57 UTC, mefuller commented
@bryanwweber looks like the CI / .NET failures are due to a 404 pulling down dependencies - is there an easy way to re-trigger these?

2023-12-13 23:49 UTC, bryanwweber commented
@mefuller I just restarted them

2023-12-14 04:15 UTC, speth commented
I think the failure of the .NET on ubuntu-22.04 run is because we're missing a `sudo apt update` before the `sudo apt install ...` command in that workflow (though I don't really understand the circumstances under which older package versions are removed from the Ubuntu repositories).

The other errors with the .NET interface are already fixed in the main branch (see commit aee309220), and can be resolved by rebasing.

2023-12-14 20:48 UTC, mefuller commented
@bryanwweber the failures in CI seem to all be on .NET (with which I am not at all familiar) - any idea what might be the cause?

2023-12-14 22:20 UTC, bryanwweber commented
I'm not sure, I think some foxes are on `main` if you haven't rebased in a bit. Maybe @speth can help 😟

2023-12-14 22:26 UTC, speth commented
Repeating what I wrote previously: The other errors with the .NET interface are already fixed in the `main` branch (see commit [aee3092](https://github.com/Cantera/cantera/commit/aee30922054556730e188aba9b0f1b819ef2e7bd)), and can be resolved by rebasing.

2023-12-15 01:02 UTC, mefuller commented
Sorry7 about glossing over that @speth - rebased and rerunning

2023-12-18 00:52 UTC, bryanwweber commented
Thanks @mefuller , the code looks good, I just haven't had a chance to pull it down and try it out. I'll try to do that soon!

2023-12-24 21:23 UTC, bryanwweber approved these changes

2023-12-24 21:24 UTC, merged

2023-12-24 21:24 UTC, bryanwweber commented
Thanks @mefuller!