yaml2ck: Check if third body is in species list
Cantera/cantera pull request #1696
Opened 2024-05-16 17:40 UTC by corykinney

**Changes proposed in this pull request**

This pull request adds a check in `yaml2ck` for third body efficiencies for species that might not be present in the `ct.Solution` object due to the `skip-undeclared-third-bodies: true` flag.

Closes #1683 

Using the provided example from the issue referenced:

```yaml
phases:
- name: test
  thermo: ideal-gas
  elements: [O, H, C, Ar]
  species:
  - gri30.yaml/species: all
  kinetics: gas
  skip-undeclared-elements: true
  skip-undeclared-third-bodies: true
  reactions:
  - gri30.yaml/reactions: declared-species
  transport: mixture-averaged
  state: {T: 300.0, P: 1 atm}
```

The outputted Chemkin file from `python -m cantera.yaml2ck test.yaml --overwrite` before the change:

```
H + O2 + M <=> HO2 + M           2.8000000000000005e+18 -0.86 0.0
AR/0.000E+00/ C2H6/1.500E+00/ CO/7.500E-01/ CO2/1.500E+00/ H2O/0.000E+00/ N2/0.000E+00/ O2/0.000E+00/
```

versus after the change:

```
H + O2 + M <=> HO2 + M           2.8000000000000005e+18 -0.86 0.0
AR/0.000E+00/ C2H6/1.500E+00/ CO/7.500E-01/ CO2/1.500E+00/ H2O/0.000E+00/ O2/0.000E+00/
```

The `N2` efficiency is omitted from the list as desired. 

**Feedback**

An example file still needs to be added with a corresponding test case, but before doing so, I wanted to solicit feedback on potential edge cases. What behavior would be expected if no explicit third body species are present in the mechanism? Are there any other possible cases that need to be accounted for proactively? 

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2024-06-01 22:44 UTC, speth requested changes
Thanks, @corykinney. I think this looks like a clean fix. Could you please add a test to `test_convert.py` verifying that this works as intended?

2024-06-01 22:44 UTC, speth commented on interfaces/cython/cantera/yaml2ck.py
> +    species_names = [spec.name for spec in species]
Building this as a set will make the subsequent `in` checks more efficient.
```suggestion
    species_names = {spec.name for spec in species}
```

2024-06-01 22:44 UTC, speth commented on interfaces/cython/cantera/yaml2ck.py
> +def build_reactions_text(reactions: Iterable[ct.Reaction], species: Iterable[ct.Species]):
The `species` argument needs to be described in the docstring.

2024-06-01 22:48 UTC, speth commented
> What behavior would be expected if no explicit third body species are present in the mechanism?

I didn't try it, but I think your patch would add a blank line to the output. I don't see a problem with that.

2024-06-03 20:14 UTC, corykinney commented
@speth I implemented your suggestions and added the necessary test case. It should be good to go, but let me know if I missed anything in the test.

2024-06-03 21:34 UTC, speth approved these changes
Thanks, @corykinney! This looks good to me.

2024-06-03 21:34 UTC, merged