Tweak MATLAB Func1 operators
Cantera/cantera pull request #1758
Opened 2024-08-04 20:19 UTC by ischoegl

**Changes proposed in this pull request**

- Use specialized functions for `Func1` operators
- Add google tests

Follow-up to #1741

**If applicable, provide an example illustrating new features this pull request is introducing**

```
>> out = Func1('sin') / 2
 
out = 
 
   0.5\sin(x)
 
>> out.type()

ans =

    'times-constant'
```

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2024-08-05 03:08 UTC, ischoegl commented
For the sake of consistency, I ended up making Python and MATLAB `Func1` API's more symmetric. While there are no callbacks in MATLAB, Python now allows for MATLAB-like construction of functors.

2024-08-06 18:30 UTC, ischoegl commented
I ended up adding a section to our `custom_reaction.py` benchmark that uses C++ functors. Here are results:
```
% python custom_reactions.py
Average time of 100 simulation runs for 'gri30.yaml' (CH4)
- New framework (YAML): 18.84 μs/step (T_final=2780.21)
- Two Custom reactions (Python): 19.35 μs/step (T_final=2780.21) ...+2.75%
- Two Custom reactions (C++ Func1): 18.92 μs/step (T_final=2780.21) ...+0.43%
- Two Extensible reactions: 19.83 μs/step (T_final=2780.21) ...+5.28%
```
i.e. unsurprisingly the C++ `Func1` performs more or less the same as the original mechanism (on some runs, it was actually _faster_, so it is within the accuracy of this poor man's benchmark).

While I don't believe that C++ functors are all that important to the Python API, I believe that having an interface equivalent to MATLAB is overall beneficial.

2024-08-06 22:33 UTC, ischoegl commented
#1763 should be merged before, so `custom_reaction.py` can be updated once this is rebased.

2024-08-07 01:29 UTC, ischoegl commented
Rebased and incorporated #1763.

2024-08-07 12:38 UTC, ischoegl reviewed
Note to self. Not pushing updates to prevent further churn.

2024-08-07 12:38 UTC, ischoegl commented on test/general/test_numerics.cpp
> +    EXPECT_DOUBLE_EQ(functor->eval(.5), 2 * sin(.5));
Should 
```suggestion
    double x = .5;
    EXPECT_DOUBLE_EQ(functor->eval(x), 2 * sin(x));
```
Should use variable for clarity (here and on most other additions in this file).

2024-08-07 14:30 UTC, ischoegl commented
Rebased once more and took care of a couple of paper cuts; PR should be ready for a review.

2024-08-09 03:18 UTC, speth requested changes
Thanks, @ischoegl, this generally makes sense to me, and I appreciate the comprehensive unit tests. I had a handful of small suggestions.

2024-08-09 03:18 UTC, speth commented on include/cantera/numerics/Func1.h
> +    }
I guess the idea here is not necessarily to provide a perfect implementation of `isIdentical`, in that it's most important not to return `true` unless the functions really are identical, while a few false negatives is just a minor issue that prevents some simplifications? If that understanding is correct, it would be worth noting in the base class docstring.

2024-08-09 03:18 UTC, speth commented on interfaces/cython/cantera/func1.pyx
> +    For implemented C++ functor types, see the Cantera C++ ``Func1`` documentation.
You can generate a link here with ``` :ct:`Func1` ```.

2024-08-09 03:18 UTC, speth commented on interfaces/cython/cantera/func1.pyx
> +            other = Func1(other)
The class docstring should describe the operator overloading behavior implemented and give an example or two (and presumably noted as new in 3.1).

2024-08-09 03:18 UTC, speth commented on samples/python/kinetics/custom_reactions.py
> +# extensible versions
```suggestion
# construct reactions based on ExtensibleRate: replace two reactions with equivalent
# extensible versions
```

2024-08-09 03:18 UTC, speth commented on interfaces/cython/cantera/func1.pyx
> +        8.0
It would be good to show another example where the coefficient isn't necessarily a scalar. The `__init__` signature of `(self, c, *args, init=True)` initially made me think that you would use something like `Func1("Arrhenius", 1000, 2.0, 100)`, but that isn't the case.

2024-08-09 03:18 UTC, speth commented on samples/python/kinetics/custom_reactions.py
> +print(f'- New framework (YAML): {sim0:.2f} μs/step (T_final={gas0.T:.2f})')
At this point, it would be more accurate to just describe this as "Built-in rate parameterizations".

2024-08-09 03:18 UTC, speth commented on src/numerics/Func1.cpp
> +            return std::make_pair(true, 1.);
I think in the current C++ standard, you should be able to just `return {true, 1.0}`.

2024-08-09 03:18 UTC, speth commented on src/numerics/Func1.cpp
> +        double c = prop.second;
You can use a structured binding to make this a little bit nicer:
```suggestion
    auto [prop, c] = isProportional(f1, f2);
    if (prop) {
```

2024-08-09 03:18 UTC, speth commented on test/general/test_numerics.cpp
> +    ASSERT_TRUE(functor->isIdentical(*functor));
All these dereferences for calls to `isIdentical` make me wonder if we should change it to take `shared_ptr<Func1>&` instead (though the deprecation logic might require a bit of thinking to get right).

2024-08-09 12:33 UTC, ischoegl commented on test/general/test_numerics.cpp
> +    ASSERT_TRUE(functor->isIdentical(*functor));
This really is the last left-over in this class that doesn't use `shared_ptr<Func1>` as an argument ... it's probably worth changing.

2024-08-09 16:20 UTC, ischoegl commented
@speth ... I updated the Python docstring as follows:
```none
     [...]
     Note that `Func1` objects also allow for direct access to functor objects
     implemented in C++ based on associated type specifiers::

         >>> f5 = Func1("exp", 3.)  # C++ 'Exp1' functor
         >>> f5.cxx_type
         'Cantera::Exp1'
         >>> f5.write()
         '\\exp(3x)'
         >>> f5(2.)
         403.4287934927351
         >>> f6 = Func1("Arrhenius", [9630.0, 2.0, 2012.878])  # C++ 'Arrhenius1' functor
         >>> f6(1500)
         5662665826.195515

     For implemented C++ functor types, see the Cantera C++ :ct:`Func1` documentation.

     `Func1` objects support operator overloading which facilitates the construction of
     compound functions, where some standard simplifications are implemented::

         >>> f7 = 2 * f5 + 3
         >>> f7.write()
         '2\\exp(3x) + 3'
         >>> f7(2.)
         809.8575869854702
         >>> f8 = f5 * f5
         >>> f8.write()
         '\\exp(6x)'
         >>> f8(2.)
         162754.79141900392
```

which also illustrates `Func1.write` (added in 3.0) and a `Func1.cxx_type` that I added in an update to this PR.

2024-08-09 21:01 UTC, speth approved these changes
Thanks, @ischoegl. This looks good to me.

2024-08-09 21:01 UTC, merged