Some sourcegen/dotnet updates
Cantera/cantera pull request #1773
Opened 2024-08-14 15:15 UTC by ischoegl

**Changes proposed in this pull request**

This PR introduces combines some simple CLib updates with required fixes/updates in `sourcegen` and `dotnet`.

- Eliminate `thermo_newFromFile` from CLib and .NET
- Switch `thermo_equilibrate` solver specification from magic number to string (consistent with Python and Fortran APIs)

The PR cherry-picks some commits from #1761, #1765 and #1770.

**If applicable, fill in the issue number this pull request is fixing**

Closes #450
Partially addresses Cantera/enhancements#199 (.NET side)

**If applicable, provide an example illustrating new features this pull request is introducing**

N/A

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2024-08-14 19:15 UTC, ischoegl commented
:tada: ... figuring out .NET and sourcegen took a while, but this is now ready for a review.

2024-08-18 18:16 UTC, speth requested changes
This looks good to me. Just a couple of minor comments/questions. Also, can you rebase now that #1761 has been merged?

2024-08-18 18:16 UTC, speth commented on interfaces/matlab_experimental/Base/ThermoPhase.m
> +            %     (VCS algorithm). For the default 'auto' setting, the fast solver
This comment appears to end mid-sentence.

2024-08-18 18:16 UTC, speth commented on interfaces/sourcegen/sourcegen/_helpers.py
> +    return "\n".join([_.rstrip() for _ in ret.split("\n")])
`_` is usually only used for a variable that's explicitly being ignored. Here, I'd suggest just calling it `line`.

2024-08-18 18:16 UTC, speth commented on interfaces/dotnet/Cantera/src/Application.cs
> +        new ThermoPhase(filename, phaseName, transModel);
Until the .NET interface handles transport, I think it would be preferable to just initialize the `Solution` with a transport model of `none`. The idea of having the `ThermoPhase` constructor take a transport model argument is a bit confusing.

2024-08-18 18:16 UTC, speth commented on interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py
> +            {hanging_text(self._config.preamble, 12)}
Was `normalize_indent` failing somewhere? I looked at several of the `.g.cs` files and didn't spot any indentation changes as a result of changing this. Not having to specify the indent level was kind of nice.

2024-08-18 20:08 UTC, ischoegl commented on interfaces/dotnet/Cantera/src/Application.cs
> +        new ThermoPhase(filename, phaseName, transModel);
Good point. I just did minimal replumbing here - I don't know enough about .NET to set up proper inheritance so we can instantiate a new `Solution` class that properly exposes all `ThermoPhase` methods (i.e. `Solution` needs to use multiple inheritance eventually, similar to what is done in Python and MATLAB).

2024-08-18 20:13 UTC, ischoegl commented on interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py
> +            {hanging_text(self._config.preamble, 12)}
It was messing up formatting - while working on this, I experimented with adding an actual `Solution` object (by creating a `Solution.g.cs` file, and it messed up `Interop.Handles.g.cs`. It's probably temporary anyways, as using a templating library like Jinja (per your suggestion in Cantera/enhancements#39) is likely a better option long term anyways. At least that's what I'm anticipating for the CLib work I started based on #1777.

2024-08-18 20:48 UTC, ischoegl commented
@speth … thanks for your review! I rebased and addressed your comments, so it should be ready.

2024-08-18 23:56 UTC, speth approved these changes
Thanks, @ischoegl, this looks good to me.

2024-08-18 23:56 UTC, merged