Use Jinja templates in csharp sourcegen
Cantera/cantera pull request #1785
Opened 2024-08-21 17:34 UTC by ischoegl

**Changes proposed in this pull request**

This PR is a preamble to a potential solution for Cantera/enhancements#39, which replaces f-string based code blocks used for the .NET interface by corresponding Jinja templates. In addition, it adds some service methods to data classes.

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2024-08-22 03:03 UTC, ischoegl commented
Aborting attempts to pull git commit and cantera version out of CLib to get better annotations. Using SCons once this is integrated into the build system is likely preferable anyways.

2024-08-25 04:56 UTC, ischoegl commented
While this PR is not essential for 3.1, it is nevertheless ready for a review.

2024-11-01 16:51 UTC, speth requested changes
Thanks, @ischoegl. I think this is a useful evolution of the `sourcegen` infrastructure as we look toward using it for additional interfaces. The implementation looks quite clean. I just had a few minor suggestions below.

2024-11-01 16:51 UTC, speth commented on interfaces/sourcegen/sourcegen/csharp/_dataclasses.py
> +        return any(p.p_type.endswith("*") for p in self.arglist)
A docstring here would be helpful.

2024-11-01 16:51 UTC, speth commented on interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py
> +        return text
As a small simplification, you could just `return template.render(...` above, since there's no longer this common step of calling `normalize_indent` on every branch.

2024-11-01 16:51 UTC, speth commented on interfaces/sourcegen/sourcegen/_dataclasses.py
> +
I'd suggest something like `arg` instead of `_` for the loop variable. I think `_` should only be the name for an unused value.

2024-11-01 16:51 UTC, speth commented on interfaces/sourcegen/sourcegen/_dataclasses.py
> +        name = re.findall(re.compile(r'.*?(?=\(|$)'), func)[0]
I don't think there's any benefit from explicitly calling `re.compile` here. Also, a comment on what this pattern is doing would be helpful.

2024-11-01 16:51 UTC, speth commented on interfaces/sourcegen/sourcegen/_orchestrate.py
> +    templates = read_config(root.joinpath("templates.yaml"))
You could consider using the overloaded `/` here:
```suggestion
    config = read_config(root / "config.yaml")
    templates = read_config(root / "templates.yaml")
```

2024-11-02 03:40 UTC, ischoegl commented
Thanks, @speth! I took care of all your suggestions.

2024-11-02 16:41 UTC, speth approved these changes
Thanks, @ischoegl!

2024-11-02 16:41 UTC, merged