Non-empty Reactor and Connector Objects for 3.1
Cantera/cantera pull request #1788
Opened 2024-08-23 03:57 UTC by ischoegl

**Changes proposed in this pull request**

- 🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧 
-
-

**If applicable, fill in the issue number this pull request is fixing**

Closes Cantera/enhancements#213

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

2024-08-25 04:51 UTC, ischoegl commented
@speth ... while there are likely more paper cuts, I don't necessarily want to go beyond 2k lines. 

Among the things that _could_ be tackled are lowercase/hyphenated type names to be consistent with what we do with `ThermoPhase` and `Kinetics`, providing a name to `ReactorNet`, as well as merging `Reactor.thermo`/`Reactor.kinetics` into `Reactor.contents` in the Python API. Those are relatively minor additions that could be done in a follow-up PR (if so desired). At the same time, there will be further updates in 3.2, although I'd like to keep those mostly _under the hood_.

2024-08-27 02:52 UTC, ischoegl commented
I just realized that there are some connections to Cantera/enhancements#201 and Cantera/enhancements#202. While this PR doesn't address either directly, it does ensure that a resolution will become easier.

Without trying to pre-empt any eventual resolution, my personal take would be:
- Have each `Reactor` 'own' a copy of a`Solution` object exclusively to address Cantera/enhancements#201, which would likely require the implementation of a copy constructor for `Solution`. We then could attach `Solution` methods directly to the reactor, which would eliminate the need to access a `thermo` or `kinetics` member variable.
- Decouple `ReactorSurface` from bulk reactors to address Cantera/enhancements#202. While this PR de facto declares `ReactorSurface` to be its own "node" already, I have not implemented an "edge" that ties a surface reactor to a bulk phase reactor. I was toying with the idea to replace `ReactorSurface.install` /  `ReactorBase::addSurface` by new `Connector` specialization but ultimately decided against it. At the same time, it would be a logical next step.

2024-09-10 18:19 UTC, speth requested changes
I think the changes to have `Reactor` objects always contain a valid `Solution` object make sense, and I agree that this will help with Cantera/enhancements#201. I also like the idea of always providing the `Reactor` objects to the constructor for the connector objects and bringing that feature of the Python API to all the interfaces.

However, it's not quite clear to me what the benefit is of making all `Reactor` and connector objects into mandatory `shared_ptr`s. Currently, the ownership model is simple: none of the `Reactor`/`ReactorNet`/`FlowDevice`/etc. objects take ownership of anything they are connected to; the lifetimes of all these objects are managed by the caller. Within this set of objects, we need connections in all directions. Avoiding reference cycles will require the use of `weak_ptr` for many of the connections, with the associated overhead of "upgrading" those to `shared_ptr` where they are used. And you will still be left with the situation where it's possible to hold on to some element of the network but not be able to use it because the rest of the network has been deleted, though at least that would be checked and generate an exception rather than undefined behavior. My apologies for not thinking this through earlier and discussing it on Cantera/enhancements#213 before you put the time into implementing it.

Regarding the extension of the graph idiom, I think there's a simplification that may be worth considering. Instead of seeing just `Reactor` and `ReactorSurface` objects as nodes in the graph, you could also see valves and flow devices as nodes, with the edges of the graph just being the abstract connections among all of the entities that make up the reactor network. This way, there's only the need for one new base class, and no need for anything to sit between a `Reactor` and a `ReactorSurface`. This also gets closer to the original intent of Cantera/enhancements#212, and may work better as the amount of information you might want to display about a connector increases, given some of the limitations of how Graphviz handles (or doesn't) text associated with edges. That said, I do like the `Connector` class as a generalization combining walls and flow devices, and there's probably some further room to adjust this idea.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ReactorNet.h
> +//! [Reactor Science](https://cantera.org/science/reactors/reactors.html)
This link is to the legacy website. To create a link that will stay within the correct section (stable or dev) of the website, this should be a relative link:
```suggestion
//! @details See the
//! [Reactor Science](../reference/reactors/index.html)
```
This is a bit tricky, but it is described at https://cantera.org/dev/develop/doc-formatting.html#useful-doxygen-syntax

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ReactorFactory.h
>  shared_ptr<ReactorBase> newReactor(const string& model);
I think this is creating an interface that will be difficult to use without a lot of `dynamic_pointer_cast`s, which should generally be avoided. Objects of type `ReactorNode` define a very limited interface that isn't very useful on it's own.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +
Adding this function for every derived class is a lot of boilerplate -- I think if someone wants to create a reactor object with a specific type, they can just use `Reactor::create`, and we can leave `newReactor` as the sole polymorphic factory method.

Or, if you prefer the `newConstPressureReactor` etc. functions, you could make these functions friends of the corresponding classes and do away with the `create` method.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
> +    virtual void addSurface(shared_ptr<ReactorNode> surf);
```suggestion
    //! Add a ReactorSurface to a bulk reactor.
    //! @since New in %Cantera 3.1. Replaces version using raw pointer.
    virtual void addSurface(shared_ptr<ReactorNode> surf);
```

2024-09-10 18:19 UTC, speth commented on samples/cxx/combustor/combustor.cpp
> +    auto m2 = newMassFlowController(air_in, combustor);
```suggestion
    // species. Downstream and upstream species are matched by name.
    auto m2 = newMassFlowController(air_in, combustor);
```

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ConnectorFactory.h
> +//!     shared_ptr<Connector> mfc = newConnector("Valve", r0, r1, "my_valve");
```suggestion
//!     shared_ptr<Connector> valve = newConnector("Valve", r0, r1, "my_valve");
```
And again in the group description below.

2024-09-10 18:19 UTC, speth commented on samples/cxx/combustor/combustor.cpp
Don't you want to use the `shared_ptr` version of `addReactor` here?

2024-09-10 18:19 UTC, speth commented on samples/cxx/kinetics1/kinetics1.cpp
> +    sim.addReactor(*r);
Likewise here.

2024-09-10 18:19 UTC, speth commented on src/zeroD/Connector.cpp
> +    }
With the logic around incrementing `counts` brought into this method, the return value for this method (and its companions in other classes) is unnecessary.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ConnectorFactory.h
> +shared_ptr<FlowDevice> newFlowDevice(const string& model, const string& name="(none)");
The `newFlowDevice` method was already marked as deprecated in the 3.0 release (noted as "To be changed after Cantera 3.0; for new behavior, see newFlowDevice3()."), so I think we could just remove it now. This applies to a few of the other factory methods as well.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ConnectorFactory.h
> +shared_ptr<WallBase> newWall3(const string& model);
Given that there is also a deprecated version of `newWall`, this deprecation should specify the signature of the new overload.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ConnectorFactory.h
> +shared_ptr<WallBase> newWall(const string& model, const string& name="(none)");
Given the limited direct usefulness of a `Connector` object, I think we should direct users to the more specific method `newWall` that takes the two adjacent reactors as arguments.

2024-09-10 18:19 UTC, speth commented on src/zeroD/ReactorSurface.cpp
>      }
Better still, `m_thermo` could be set based on `m_solution` rather than needing to extract the phase from the `Kinetics` object. Or you could start by requiring an `Interface` object rather than just a `Solution`.

2024-09-10 18:19 UTC, speth commented on src/zeroD/Reactor.cpp
>          return;
Might be worth marking with a `@todo` to indicate that this check can be removed after Cantera 3.1.

2024-09-10 18:19 UTC, speth commented on src/zeroD/Reservoir.cpp
> +}
It's probably better to just put this single one-liner in the header file rather than introducing another translation unit to compile.

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/Wall.h
> +    }
`Wall` needs to hold onto a copy of the `shared_ptr` -- otherwise, if the caller isn't also holding onto one, the wall will be left with a dangling pointer. Likewise for the velocity function, and the `Func1` usage in `FlowDevice`.

2024-09-10 18:19 UTC, speth commented on interfaces/cython/cantera/drawnetwork.py
> +                   **{"label": f"{w.name}\\nq̇ = {rate:.2g} W",
:heart:

2024-09-10 18:19 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +        further integration.
```suggestion
        Set the state of the Reactor to match that of the associated `ThermoPhase`
        object. After calling `sync_state()`, call `ReactorNet.reinitialize()` before
        further integration.
```

2024-09-10 18:19 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
>      void setSolution(shared_ptr<Solution> sol);
Now that I think about this more, my preferred resolution to Cantera/enhancements#201 will require allowing `ReactorNet` to replace `Solution` objects in `Reactors`.

2024-09-10 18:19 UTC, speth commented on test/python/test_reactor.py
> +        assert not set(graph.body) - expected
This makes the graph a bit misleading, if we're labeling an edge as corresponding to a specific MFC, but then displaying the mass flow through two distinct MFCs. This may be an argument for the alternative view of the network, where the connectors are also nodes in the graph.

2024-09-10 18:19 UTC, speth commented on src/clib/ctreactor.cpp
> +            return ReactorCabinet::as<ReactorBase>(i)->mass();
The fact that almost all usage of `ReactorNode` objects requires downcasting to `ReactorBase`, `ReactorSurface`, or `Reactor` suggests to me that we shouldn't be defining our interface in terms of `ReactorNode` objects (which is not to say that the base class isn't useful for implementing some features like the automatic name generation).

2024-09-10 18:19 UTC, speth commented on samples/python/reactors/mix1.py
> +    print(f"Unable to show network structure:\n{err}")
The behavior of causing tabs to open in my browser when building the docs from the command line is not my favorite. This also makes the diagram show up in a separate browser window when using the Jupyter notebook version of the example, rather than the inline view.

2024-09-10 21:55 UTC, ischoegl commented on include/cantera/zeroD/ReactorBase.h
>      void setSolution(shared_ptr<Solution> sol);
Could you expand? My thinking was a strict hierarchy where the `ReactorNet` is responsible for `Reactor`, which themselves are responsible for `Solution`. I am not sure that I see why we should give `ReactorNet` the ability to muddle with reactor contents?

2024-09-12 14:22 UTC, ischoegl commented on samples/python/reactors/mix1.py
> +    print(f"Unable to show network structure:\n{err}")
I added this as when things are run in IPython or Python from the command line (my preferred avenue), nothing is shown. Still, removing the line based on feedback.

2024-09-12 14:25 UTC, ischoegl commented on test/python/test_reactor.py
> +        assert not set(graph.body) - expected
This is a pre-existing condition that was not previously evident. Without major re-implementation, the explanation provided here is all we can do? I personally do not follow the rationale to use two MFC's in parallel between the same reservoir. Closing here as I am moving this to a separate PR (#1792)

2024-09-12 16:57 UTC, ischoegl commented
@speth ... I took care of the easy bits, but wanted to see whether we could discuss some of the more difficult parts before going into more details. I am ultimately not sure what the direction should be - just take out mandatory `shared_ptr`? Also, regarding `ReactorNode` I do see an alternative of deriving `ReactorSurface` from `ReactorBase` - I had seen the latter as something that contains a bulk phase, but I do see that simplifications may make sense. I do not think that Connectors should be combined with a more generic nodes, as they are very different from reactors.

2024-09-13 17:07 UTC, speth commented on include/cantera/zeroD/ReactorBase.h
>      void setSolution(shared_ptr<Solution> sol);
See https://github.com/Cantera/enhancements/issues/201#issuecomment-2349477048

2024-09-14 15:55 UTC, ischoegl commented
Based on feedback above, I suggest to shelve this PR for the time being as it may be a distraction that keeps us from releasing 3.1 sooner rather than later.

2024-09-14 16:30 UTC, ischoegl commented on src/zeroD/ReactorSurface.cpp
>      }
This is an example for what needs to change eventually. This PR was an attempt to update the API first and tackle the underpinnings in follow-up work. Based on the feedback received, I do believe that a more comprehensive/strategic approach is warranted.

2024-09-15 12:33 UTC, ischoegl commented on src/zeroD/Reservoir.cpp
> +}
I created this as otherwise we'd end up with duplicate symbols.

2024-09-15 15:50 UTC, ischoegl commented on include/cantera/zeroD/ConnectorFactory.h
> +shared_ptr<WallBase> newWall3(const string& model);
Now replaced by `Wall::create`.

2024-09-15 15:52 UTC, ischoegl commented on include/cantera/zeroD/Reactor.h
> +
Based on this feedback, I removed all `new*Reactor` functions, and move to various `Reactor::create` variants. The sole polymorphic factory method is now `newReactorNode`.

2024-09-15 15:53 UTC, ischoegl commented on include/cantera/zeroD/ReactorFactory.h
>  shared_ptr<ReactorBase> newReactor(const string& model);
Removed.

2024-09-15 15:58 UTC, ischoegl commented on include/cantera/zeroD/ReactorBase.h
>      void setSolution(shared_ptr<Solution> sol);
I responded in https://github.com/Cantera/enhancements/issues/201#issuecomment-2351041080. Irrespective of the logic we go with eventually, the detection of previously used `Solution` objects should be handled by `ReactorNode` and not `ReactorNet`.

2024-09-15 15:59 UTC, ischoegl commented on src/clib/ctreactor.cpp
> +            return ReactorCabinet::as<ReactorBase>(i)->mass();
Once the API is fixed, `ReactorBase` methods should be either shifted to `ReactorNode` or `Reactor`, with `ReactorBase` eventually being removed. From that perspective, this is transitional behavior.

2024-09-15 17:13 UTC, ischoegl commented
@speth ... thank you again for your feedback. After further consideration, I decided to move ahead with revisions on this PR after all, as some of the API changes are necessary to tackle updates envisioned by various enhancement requests. 

I adopted most of your suggestions, specifically:
- Reduce boilerplate, and use `XYZ::create` methods directly rather than `newXYZ` convenience functions.
- Remove functions previously marked as deprecated.
- Leave default constructors public.

Beyond, I tried to clarify future plans that motivated API changes, see various comments in the contexts of  Cantera/enhancements#201, Cantera/enhancements#202 and Cantera/enhancements#213.

2024-10-13 14:16 UTC, speth commented
> Once the API is fixed, `ReactorBase` methods should be either shifted to `ReactorNode` or `Reactor`, with `ReactorBase` eventually being removed. From that perspective, this is transitional behavior.
> 
> Adding the following to `ReactorBase.h`:
> 
> ```
>  * @todo After completion of the %Cantera 3.1 deprecation cycle, all methods should be
>  *      either moved to ReactorNode or Reactor, with ReactorBase entering its own
>  *      deprecation cycle in %Cantera 3.2.
> ```

*(moving out of a specific line-by-line comment to prevent GitHub from hiding this higher-level discussion)*

I think this gets to my main concern with the API changes that this PR creates. Right now, there's a bit too much importance being placed on the idea of the reactor network as a graph -- most users don't care about this, but it now becomes the most important thing about a reactor and represents almost the only set of directly accessible functionality when using `newReactorNode` over the now-deprecated `newReactor` method.

I'd like to explore whether we can directly skip over creating the `ReactorNode` class and make `ReactorBase` serve this purpose immediately. The main difference that has with the current structure is that it would make `ReactorSurface` into a `ReactorBase`, but I think that's a step in the right direction anyway, given the other discussion we've had about the future of handling surfaces and edges in Cantera/enhancements#202. There aren't that many functions of `ReactorBase` that aren't applicable to a `ReactorSurface` and we can make those virtual functions and override them as needed.

I'd rather do this than leave users with an unnecessarily difficult-to-use interface for a full Cantera version.

2024-10-13 16:36 UTC, ischoegl commented
Thanks for your response, @speth.

> I think this gets to my main concern with the API changes that this PR creates. Right now, there's a bit too much importance being placed on the idea of the reactor network as a graph -- most users don't care about this, but it now becomes the most important thing about a reactor and represents almost the only set of directly accessible functionality when using `newReactorNode` over the now-deprecated `newReactor` method.

Interesting thought - my attempt to simplify was definitely influenced by viewing 'reactor networks as a graph', although my objective was to simplify/generalize rather than making things more complicated.

> I'd like to explore whether we can directly skip over creating the `ReactorNode` class and make `ReactorBase` serve this purpose immediately. The main difference that has with the current structure is that it would make `ReactorSurface` into a `ReactorBase`, but I think that's a step in the right direction anyway, given the other discussion we've had about the future of handling surfaces and edges in [Cantera/enhancements#202](https://github.com/Cantera/enhancements/issues/202). There aren't that many functions of `ReactorBase` that aren't applicable to a `ReactorSurface` and we can make those virtual functions and override them as needed.

I agree that we have one superfluous layer, which needs to be addressed. I was thinking along the lines of differentiating between bulk and surface reactors. I still think that _nodes_ and _edges_ make sense overall, so my introduction of a new base class was a move to phase out `ReactorBase` while providing a little more flexibility.

> I'd rather do this than leave users with an unnecessarily difficult-to-use interface for a full Cantera version.

I think at this point it makes sense to defer to 3.2. I will change the project planner accordingly.

2025-02-04 03:58 UTC, ischoegl commented
@speth ... I pulled out the less controversial commits to #1848; I also added some comments to Cantera/enhancements#213.

2025-02-04 03:59 UTC, closed without merging