[matlab/doc] Update importPhase to Solution for matlab input-tutorial
Cantera/cantera pull request #383
Opened 2016-11-10 16:24 UTC by EmilAtz

Updated to importPhase to Solution to match current function usage

2016-11-10 16:33 UTC, bryanwweber commented
@speth Emil is the student who will be working on the Matlab interface. He and I worked together on this commit, I can't remember if we've discussed recommendations for `Solution` vs. `importPhase` in Matlab, but since `importPhase` calls `Solution` anyways, I figured this change would be appropriate.

2016-11-10 17:54 UTC, speth reviewed
I'm in favor of this change. It would be good to track down other uses of `importPhase` and update them as well, both in the toolbox itself and in the examples. And maybe deprecate the `importPhase` function as well.

2016-11-10 17:54 UTC, speth commented on doc/sphinx/matlab/input-tutorial.rst
> +Function ``Solution`` constructs an object representing a phase of matter by
I think the phrasing here needs to change -- `Solution` isn't a function, but the constructor for a class.

2016-11-18 21:44 UTC, bryanwweber commented on doc/sphinx/matlab/input-tutorial.rst
> +Function ``Solution`` constructs an object representing a phase of matter by
Would deleting the word "Function" from the beginning of the sentence be sufficient?

2016-11-18 23:19 UTC, speth commented on doc/sphinx/matlab/input-tutorial.rst
> +Function ``Solution`` constructs an object representing a phase of matter by
Possibly. What about ```This statement constructs a ``Solution`` object representing...```?

2016-11-19 17:43 UTC, EmilAtz commented on doc/sphinx/matlab/input-tutorial.rst
> +Function ``Solution`` constructs an object representing a phase of matter by
I will make those changes and search through the rest of the documentation for other instances of importPhase and convert them to Solution.  If there is any writing on importPhase that mentions "Function" I will modify the phrasing to something better fitting for Solution.

2016-12-10 01:21 UTC, speth requested changes
Please squash the indicated change into the preceding commit. After that, unless you have something else to add to this PR, I think it's good to go.

2016-12-10 01:21 UTC, speth commented on interfaces/matlab/toolbox/importPhase.m
> +warning('This function is deprecated and will be removed after Cantera 2.3.');
I think this warning should mention what the alternative is.

2016-12-10 01:21 UTC, speth commented on doc/sphinx/cti/phases.rst
> -    >>> gas = importPhase('example.cti', 'gasmix')
Good catch on this one, given that the Python function `importPhase` hasn't even existed since the legacy Python module went away.

2016-12-10 15:55 UTC, bryanwweber commented on interfaces/matlab/toolbox/importPhase.m
> +warning('This function is deprecated and will be removed after Cantera 2.3.');
@EmilAtz When you make this change, you'll need to use the command line rather than the GUI to squash the commit as @speth suggested. In the terminal, add the file to a commit with `git add interfaces/matlab/toolbox/importPhase.m`, then type `git commit --amend --no-edit`. This will amend the last commit with the new information. Then you'll have to force push the branch with `git push -f`. You have to force push because you're taking the latest commit here and overwriting it. If you have any questions, feel free to ask here or send me an email!

2016-12-10 19:31 UTC, EmilAtz commented on interfaces/matlab/toolbox/importPhase.m
> +warning('This function is deprecated and will be removed after Cantera 2.3.');
@speth, @bryanwweber, before I make the change would this be an appropriate modification?
 
warning('This function is deprecated and will be removed after Cantera 2.3. ...
reference function s = Solution(src, id, trans)');

2016-12-10 20:03 UTC, bryanwweber commented on interfaces/matlab/toolbox/importPhase.m
> +warning('This function is deprecated and will be removed after Cantera 2.3.');
I think it should be `warning('This function is deprecated and will be removed after Cantera 2.3. Use Solution instead.')`

2016-12-10 20:18 UTC, EmilAtz commented on doc/sphinx/cti/input-files.rst
> -
@speth Please see the Traceback on line 419 of `input-files.rst` @bryanwweber and I believe it is incorrect

2016-12-10 20:54 UTC, bryanwweber commented on doc/sphinx/cti/input-files.rst
> -
@speth This is the section @EmilAtz is referring to: https://github.com/Cantera/cantera/blob/master/doc/sphinx/cti/input-files.rst#syntax-errors I'm not sure if `importPhase` is still used in C++, and also, what language this Traceback is generated by (i.e., if calling from C++ would produce a similar looking traceback). I also think the `Cantera Error` section is out of date.

2016-12-10 23:35 UTC, speth commented on doc/sphinx/cti/input-files.rst
> -
That traceback is out of date (it appears to have been generated using the legacy Python module), but as the text following it says,
> The top part of the error message shows the chain of functions that were called before the error was encountered. For the most part, these are internal Cantera functions not of direct concern here. The relevant part of this error message is the part starting with the "Cantera Error" heading

If you want to replace it with a current traceback, that would be fine, but I would also be fine with leaving it as is.

2016-12-11 16:27 UTC, bryanwweber commented on doc/sphinx/cti/input-files.rst
> -
@EmilAtz Let us know if you want to fix it, if not, this should be good to merge.

2016-12-11 20:04 UTC, speth approved these changes

2016-12-21 20:39 UTC, merged