Modify parseTransportData to identify species that have incorrect ent…
Cantera/cantera pull request #405
Opened 2016-12-06 12:59 UTC by santoshshanbhogue

Fixes #403  .

Changes proposed in this pull request:
[ck2cti.py](https://github.com/santoshshanbhogue/cantera/blob/ck2ctiTranspo/interfaces/cython/cantera/ck2cti.py)

'ck2cti.py' will now identify which species has extra columns that generate an error

2016-12-06 15:09 UTC, bryanwweber commented
@santoshshanbhogue Can you add a test that raises this error?

2016-12-06 23:51 UTC, santoshshanbhogue commented
@bryanwweber Sure, working on it

2016-12-07 01:06 UTC, santoshshanbhogue commented
@bryanwweber @speth Does #ca36355f1dc006fd66402562c701c13ce4f700c3 suffice?

2016-12-07 02:18 UTC, speth commented
If I edit the test data file to remove the comment for the erroneous transport entry, the test fails, since the extra data field is incorrectly treated as the comment. I think we need to modify the parsing to not merge the list of coefficients and the comment in order to detect this kind of error reliably.

2016-12-07 03:47 UTC, santoshshanbhogue commented
Yup, good catch. Don't know why 'comments' were lumped with data. I've separated the two and the test catches the superfluous entries. Any scenarios where this still fails ?

2016-12-07 03:55 UTC, speth requested changes

2016-12-07 03:55 UTC, speth commented on interfaces/cython/cantera/ck2cti.py
> +                #data = line.split() + [comment]
This line should just be deleted.

2016-12-07 03:55 UTC, speth commented on interfaces/cython/cantera/ck2cti.py
>                  line, comment = line.split('!', 1)
I realize that we ultimately don't include the `comment` in the CTI file, but I think we should still pass it to the `TransportData` constructor (as a keyword argument). Will need to define `comment` in the other branch of the `if` in this case.

2016-12-07 15:14 UTC, speth requested changes
Thanks for the updates. One other minor recommendation: if you can rewrite your commit messages (using `git rebase -i`) so that the summary line is no more than 72 characters, they will be formatted better on Github.

2016-12-07 15:14 UTC, speth commented on interfaces/cython/cantera/ck2cti.py
> +                data = line.split()
This can be moved outside the `if` since it happens in both branches.

2016-12-07 15:14 UTC, speth commented on interfaces/cython/cantera/ck2cti.py
> +                comment=None
I know this is a nitpick, but there should be a space on each side of the `=`.

2016-12-07 15:24 UTC, bryanwweber commented
The `comment` variable never actually gets passed into the `TransportData` constructor: https://github.com/santoshshanbhogue/cantera/blob/041e6f6a3658b7c3484ce0275fd12d69225e84ff/interfaces/cython/cantera/ck2cti.py#L1951. Do we want it to be? If we don't, why bother defining a variable at all?

2016-12-07 15:30 UTC, speth commented
@bryanwweber Good catch. `comment` should definitely be passed into the `TransportData` constructor. That way it ends up in the `TransportData` object where there is at least an existing notation that it's not currently included in the CTI file (which can be fixed when this is being updated to generate something other than CTI).

2016-12-08 00:05 UTC, santoshshanbhogue commented
@speth and @bryanwweber - renamed the commits, and the comments var is passed to the constructor

2016-12-10 00:33 UTC, speth approved these changes

2016-12-10 00:35 UTC, speth commented
Fixed a couple of trailing whitespace issues and squashed the last few commits together. Good to go as soon as the tests pass.

2016-12-10 00:59 UTC, merged