Implementation of linear-QSSA based on GasKinetics
Cantera/cantera pull request #437
Opened 2017-02-22 18:42 UTC by haowu80s

Fixes # .

Changes proposed in this pull request:
- GasQSSKinetics derived from GasKinetics
- Takes two thermo object, one for bulk species and one for QSS species
- Linear QSSA is solved by SparseQR from Eigen. SparseLU may be faster but QR is rank revealing, which ensures correctness at singularity.
- Update ctml_writer.py to read qssa_gas from CTI files.
- About 10% more expensive than a corresponding skeletal mech.

The functionality is complete and has been tested. Development is still "in progress", in terms of tests, samples, and formatting/naming. Need some input from the community to finalize it.

2017-02-23 00:04 UTC, speth commented
Thanks for working on this; it looks very interesting. Can you please add some examples/tests? It is not entirely clear to me how one is supposed to use this class, e.g. what is the `_buff_full` argument to the constructor for?

2017-02-23 06:44 UTC, haowu80s commented
A simple example is "qss_ignition" added, which demonstrates how to use GasQSSKinetics with a constant pressure reactor.

The buffer is no longer needed to be provided by the user. The buffer is used to hold the rate of production/destruction for all species (including qss ones), while the corresponding methods only takes and outputs those for the bulk species. The usage of a user supplied buffer is now replaced by the usage of m_grt. 

I'm not very familiar with the testing part. May need some help if tests are desired.

2017-03-15 02:49 UTC, speth requested changes
Thanks for working on this. I think my one big question with this is that given that for the provided example the QSS version is slower in the sample ignition delay problem, under what circumstances would it be expected to offer a meaningful performance benefit?

It's good that you already have this working based on the CTI input file format. One thing that we still need to do is get this class set up so that a `GasQSSKinetics` object can be created via the factory functions so that they can be created in Python and Matlab as well.

In addition to addressing the specific comments made on various parts of the code, one other change that should be made is to remove the reversion of the `fmt` submodule from version 3.0.1 to 3.0.0.

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +// Created by Hao Wu (wuhao@stanford.edu), Feb. 2017
You should add yourself to the `AUTHORS` file instead of here

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    virtual ~GasQSSKinetics();
Don't need the destructor if it does nothing (only needed in the base class)

2017-03-15 02:49 UTC, speth commented on platform/posix/setup_cantera.in
> +if [ "@python_cmd@" != "which python" ]; then
What is the purpose of this change? The backticks are deliberate...

2017-03-15 02:49 UTC, speth commented on data/inputs/DME_RED30_LuoLu.cti
> +          initial_state=state(temperature=300.0, pressure =OneAtm)    )
A separate input file duplicating all the thermo data and reactions isn't really needed -- The three phase definitions can just be put into a single file.

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +class GasQSSKinetics : public GasKinetics
The comment block for the class should have at least a short description of the model, a reference to a source describing the QSSA model, and provide some idea of how to use the class (i.e. the requirements for the two `IdealGasPhase` objects this uses).

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    double m_rel_density_qss;
This variable seems to be unused?

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    // index of destruction rxn for QSS speciies in forward direction
'species' is misspelled (several other locations as well)

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    std::vector<std::vector<size_t>> m_rodf_qss;
The description of this variable is a bit confusing. Would it be more clear (assuming the following is correct) to write 'm_rodf_qss[i] contains indices of reactions having QSS species *i* as a reactant'? Likewise for the parallel structures.

Also, the comments for all of these variables should begin with `//!` so they get parsed by Doxygen.

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    std::vector<std::vector<std::vector<size_t>>> m_ropf_qss_tmp;
Can you be more explicit about what this data structure is? i.e. `m_ropf_qss_tmp[i][j][k]` is what, exactly? Same for `m_ropr_qss_tmp`.

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +}
Rather than duplicating all of these methods (e.g. this, `getDeltaGibbs`, `getDeltaEnthalpy`, etc.) for the general case (multiple thermo objects), this might be a good opportunity to move these implementations into the base `Kinetics` class, and probably remove the unnecessary "optimization" for the case of a single thermo object from `BulkKinetics`.

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +        thermo(n).getPartialMolarEnthalpies(m_grt.data() + m_start[n]);
I think it would be better to use a different temporary work array than `m_grt`, to avoid confusion.

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +    vector<size_t> qss_rts, qss_pds;
Everything in this function can just be put into `GasQSSKinetics::addReaction`, right?

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +        if (k == npos) continue;
Please avoid using the one-line / unbraced `if`, `else if`, and `for` constructs.

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +    }
Why does multiple QSS species on one side of the reaction warrant a warning? Especially given that the provided example mechanism includes several such reactions.

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +        for (const auto pd : qss_pds) {
In cases where the type is something as simple as `size_t`, I think it is more clear to use the type directly than `const auto`. `auto` is certainly preferred for more complex types, of course.

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    static const char IROPR = 1 << 1;
These can be declared as `static const` variables in the `.cpp` file, and don't need to be exposed as class members. (Also probably worth a comment explaining what they do).

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +        tripletList.push_back(Triplet<double>(k, k, 1.));
consider writing as `tripletList.emplace_back(k, k, 1.);`

2017-03-15 02:49 UTC, speth commented on include/cantera/kinetics/GasQSSKinetics.h
> +    std::vector<char> m_ifr_qss;
Need to explain what this variable does

2017-03-15 02:49 UTC, speth commented on src/kinetics/GasQSSKinetics.cpp
> +        for (SparseMatrix<double>::InnerIterator it(m_rop_qss,k); it; ++it) {
I think some more explanation of what is happening here would be useful.

2017-03-15 03:31 UTC, haowu80s commented
Hi Ray,
Thanks for the feedback.
A quick answer to the performance question. The performance gain for a QSSA mechanism comes mostly from the following three factors. 
1) The reduced number of indepedent species makes it cheaper to numerically evaluate and solve the Jacobian system for implicit ode solvers.
2) For advection-reaction-diffusion systems, the reduced species also means fewer scalar conservation equations to solve.
3) The QSS species are the stiff ones. The removal of them typically results in a less stiff mechanism and makes it possible for using explicit ode solvers in certain cases.

2017-03-15 16:54 UTC, speth commented
Right, I understand why the QSSA method *should* lead to performance improvements, my question was why, at least for the example problem given, it apparently doesn't -- I ran a loop to calculate the ignition delay 100 times using both the skeletal and QSS versions of the mechanism, and found the QSSA version to be slightly slower.

I think an ignition problem should be as good a place as any to see a performance increase, since you should see both the improvement in reducing the number of species (and the cost of the species number cubed cost of Jacobian factorization) and any reduction in stiffness via the variable timestep of the CVODES solver. However, I only saw a ~2% reduction in the number of internal timesteps needed to solve during the ignition delay period, and I guess the savings in Jacobian evaluation are wiped out by the extra work involved in the QSSA algorithm.

2017-03-15 17:22 UTC, arghdos commented
I tend to agree with @speth.  For a problem this sized (30 bulk, 9 QSS species) the majority of the simulation time is likely to be spent in FD Jacobian evaluation, hence we should expect a considerable reduction in overall simulation time from putting ~1/4 of the species as QSS.

I wonder what looking at say, the number of Jacobian evaluations in CVODE between the QSS and non-QSS baseline would reveal.  Is the QSS case causing more discontinuities or invalidating the Jacobian more often?  That might explain the difference.

2017-03-15 18:35 UTC, haowu80s commented
Ray,
I guess I miss understood your questions. 

You are perfectly right that QSSA does not give much, if any, performance boost for a 0D ignition problem of this size, at least in the way cantera solves it. A quick back-of-envelop calculation to show this and one can benchmark it to verify :

Let's say a full RHS evaluation for the 39-species mechanism is of cost 1, and the corresponding 30-species QSS version is 1.1. Within the RHS evaluation, update_T is of cost 0.6, which is the same among the two. Matrix factorizing is of cost 2 for 39x39 and 1 for 30x30. 

Jacobian evaluation for the 39-species mechanism is of cost 2 + 39x(1-0.6) (species perturbation avoids update_T). By the same token, it is 2.2 + 30x(1.1-0.6) for the 30-species QSS.

All in all, for the 39-species mech. the cost is 2 + 39x0.4 + 2 = **19.2**, while for the 39-species QSS version, it is 2.2 + 30x0.5 + 1 = **18.2**. The saving will be more significant if one uses CKWYP type of subroutines, which does not cache temperature related calculations.

In addition, CVODE only performs 1 Jacobian evaluation for as much as 50 steps. So the saving in Jacobian evaluations is really minimal for a system of this size.

Furthermore, the internal step size taken by CVODE/BDF is typically bounded by the accuracy constraints for an ignition problem, not the stability constraints. So a less stiff system does not really lead to fewer steps. 

On a more positive note, the applications where I saw meaningful gains via QSSA are large-scale 3D calculations. QSSA reduces the number of scalar transport equations to solve and also enables the usage of explicit time-stepping as the CFL limited step size is rather small to begin with.

2017-03-15 23:21 UTC, speth commented
That makes sense, and seems to fit with a bit of profiling I just did. There is definitely a reduction in the time spent on Jacobian factorization, but for this problem size, that is gain is eaten up in the QSS algorithm. So maybe it would be effective for larger mechanisms where the Jacobian factorization becomes a bigger issue, if you are able to identify enough QSS species (but that's a separate problem).

2018-11-18 17:09 UTC, closed without merging

2020-12-13 21:04 UTC, chengdi123000 commented
I tried @haowu80s 's LQSSA algorithm for a larger QSSA problem using mechanism from Prof. T.F. Lu. Small acceleration is observed. :-|

```
cd $HOME/download
wget http://spark.engr.uconn.edu/mechs/PRF3.zip
unzip PRF3.zip
cd PRF3/sk171
ck2cti --input chem.inp --output sk171.cti  --thermo therm.dat --transport tran.dat --permissive
ctml_writer sk171.cti
cd ../rd116
ck2cti --input chem.inp --output rd116.cti  --thermo therm.dat --transport tran.dat --permissive
ctml_writer rd116.cti
```
Then I manually modified the xml file to meet the need of LQSSA implementation.

test condition:
export OMP_NUM_THREADS=1 
gas.setState_TPX(1000.0, OneAtm, "IC8H18:0.012766 , NC7H16:0.012766 , O2:1 , N2:3.76"); // ER=0.3, "PRF50", it should be 50%:50% by liquid volume.
IdealGasReactor r; // const volume reactor
dt =1e-4 ;// secs
N = 1000 ;//steps

The result is:

ODE     - 14.563s
LQSSA - 11.315s