Add get refine criteria
Cantera/cantera pull request #469
Opened 2017-08-02 18:48 UTC by bryanwweber

Changes proposed in this pull request:
- Adds a function to get the refine criteria of a 1-D flow. I wasn't sure if it would be best to return as a vector or a struct (and into a dict in Python). Advice appreciated.

2017-08-02 21:11 UTC, speth requested changes
I think returning a list/vector is OK. I certainly wouldn't bother with anything more complicated in C++, but I do kind of like the idea of returning a `dict` in Python.

2017-08-02 21:11 UTC, speth commented on include/cantera/oneD/Sim1D.h
> +    }
I think the body of this function belongs in `Sim1D.cpp`.

2017-08-02 21:11 UTC, speth commented on include/cantera/oneD/refine.h
> +    }
This can be written as a one-liner in C++11:
```cxx
    return {m_ratio, m_slope, m_curve, m_prune};
```

2017-08-02 21:11 UTC, speth commented on interfaces/cython/cantera/test/test_onedim.py
> +            assert v == c
Should be `self.assertEqual(v, c)` (or even better, ditch the loop and write `self.assertEqual(vals, check)`)

2017-08-09 20:46 UTC, speth requested changes

2017-08-09 20:46 UTC, speth commented on interfaces/cython/cantera/onedim.py
> +        as defined in `~FlameBase.set_refine_criteria`.
This method returns a `dict` now, right?

2017-08-09 21:10 UTC, bryanwweber commented on interfaces/cython/cantera/onedim.py
> +        as defined in `~FlameBase.set_refine_criteria`.
D'oh, updated the example but not the text. Fixed now

2017-08-09 21:21 UTC, bryanwweber commented
I rebased this onto 572af616e7ed767d306fe439c0d7dfaad9e1225b

2017-08-09 22:46 UTC, merged