[SCons] implement 'googletest' option
Cantera/cantera pull request #535
Opened 2018-05-12 07:41 UTC by band-a-prend

Fixes #515

## Changes proposed in this pull request:

-  New scons build option introduced to replace 'system_googletest'
and allow to not use 'googletest' module while running test
(all tests that require this module could be omited)

- New option description:
'googletest',

"""Select whether to use gtest/gmock from system
   installation ('system'), from a Git submodule ('submodule'), to decide
   automatically ('default') or don't look for gtest/gmock ('none')
   and don't run tests that depend on gtest/gmock.
   Selection of 'none' will suppress the depricated 'system_googletest' option."""

- Old option is still presented and mentioned as 'depricated'.
Option 'googletest = none' supress the old 'system_googletest'.

- In other cases if they contradict to eache other - an ERROR message appears.

P.S.
See [attached file 'scons_test_results.txt'](https://github.com/Cantera/cantera/files/1997371/scons_test_results.txt) to compare results of running 'scons test' command before and after implimentation of new option.

2018-05-12 20:20 UTC, speth requested changes
I think it would help to structure this such that after the initial checks, we only look at the `googletest` variable, which should have as its value one of `system`, `submodule`, or `none`, and all later references to the `system_googletest` variable should be removed.

When it comes to running the test suite, I think there need to be some very loud and clear warnings that these tests are being skipped, printed in the test summary at the very end.

2018-05-12 20:20 UTC, speth commented on SConstruct
> +           automatically ('default'). Depricated option, please use 'googletest' instead.""",
The correct spelling is 'Deprecated'.

2018-05-12 20:20 UTC, speth commented on SConstruct
> +        config_error('Options "googletest=system" and "system_googletest=n" contradict each other.\n'
I would be fine with having the `googletest` option always override the `system_googletest` option, with no need to check for consistency.

2018-05-12 20:20 UTC, speth commented on SConstruct
>          'default', ('default', 'y', 'n')),
It might be useful to introduce a new default here, e.g. `unspecified`, treated as equivalent to `default`, and print a warning if any of the current options are explicitly given, `default` included.

2018-05-12 20:20 UTC, speth commented on SConstruct
> +            env['system_googletest'] = True
Should be setting `env['googletest'] = 'system'` here, right?

2018-05-12 20:20 UTC, speth commented on test/SConscript
> +if env['googletest'] in ('system', 'submodule', 'default'):
Once we know whether there is either a system or submodule googletest, we should no longer be looking for `default`

2018-05-12 20:20 UTC, speth commented on test/SConscript
> +    if env['googletest'] in ('system', 'submodule', 'default'):
More cleanly written as `if env['googletest'] != 'none':`

2018-05-19 00:43 UTC, band-a-prend commented on SConstruct
> +           automatically ('default'). Depricated option, please use 'googletest' instead.""",
Corrected.

2018-05-19 00:43 UTC, band-a-prend commented on SConstruct
> +        config_error('Options "googletest=system" and "system_googletest=n" contradict each other.\n'
Done.

2018-05-19 00:43 UTC, band-a-prend commented on SConstruct
>          'default', ('default', 'y', 'n')),
I still don't implement this. Could you clarify what is the warning message should be?
That "it's will be skipped if 'googletest' is set explicitly" and if not then notify that "this option is deprecated and in future user should use another"?


And about your offering about additional message
> When it comes to running the test suite, I think there need to be some very loud and clear warnings that these tests are being skipped, printed in the test summary at the very end.

It seems that I need to edit 'buildutils.py' and I currently has no idea how to implement this behaviour.
So far I added additional warning before running tests after the ending of Cantera build process.

Sorry for delaying with my answer. That's usually a problem for me to edit and rebase commits on weekdays.

2018-05-19 00:43 UTC, band-a-prend commented on SConstruct
> +            env['system_googletest'] = True
Yes, you are right. Also I add string `env['googletest'] = 'submodule'` to another block below.

2018-05-19 00:43 UTC, band-a-prend commented on test/SConscript
> +if env['googletest'] in ('system', 'submodule', 'default'):
Removed 'default' here.

2018-05-19 00:44 UTC, band-a-prend commented on test/SConscript
> +    if env['googletest'] in ('system', 'submodule', 'default'):
Done. Yes it's more clarifying condition.

2018-05-19 00:50 UTC, band-a-prend commented
I made some updates in SCounstruct and test/SConscript.

About item 3 in your "changes request":

> It might be useful to introduce a new default here, e.g. unspecified, treated as equivalent to default, and print a warning if any of the current options are explicitly given, default included.

I still don't implement this. Could you clarify what is the warning message should be?
That "it's will be skipped if 'googletest' is set explicitly" and if not then notify that "this option is deprecated and in future user should use another"?

And about your offering about additional message:

> When it comes to running the test suite, I think there need to be some very loud and clear warnings that these tests are being skipped, printed in the test summary at the very end.

It seems that I need to edit 'buildutils.py' and I currently have no idea how to implement this behaviour.
So far I added additional warning before running tests after the ending of Cantera build process.

Sorry for delaying with my answer. That's usually a problem for me to edit and rebase commits on weekdays.

2018-05-19 01:12 UTC, band-a-prend commented
@speth 

Could you check why OSX "The Travis CI build" is failed?
The Linux build was completed successfully.

2018-05-19 09:56 UTC, band-a-prend commented
I'm in a shame spiral. The build problem was due to I inserted few tabulations in two strings while editing.

2018-05-20 00:52 UTC, speth reviewed
Thanks, this is looking quite a bit cleaner now. I think there's still a bit that can be done to help with the transition from the `system_googletest` to `googletest` option. If we introduce `unspecified` as the default choice for the `system_googletest` option, taking this to mean that the user has not given any of the three existing choices, then I think logic should be something like the following:
```python
if env['system_googletest'] != 'unspecified':
    warn about deprecated option
if env['system_googletest'] == 'default':
    env['googletest'] = 'default'
elif env['system_googletset'] == 'y':
    env['googletest'] = 'system'
elif env['system_googletest'] == 'n':
    env['googletest'] = 'submodule'
```
After which point the 'system_googletest' variable should not be used at all.

I'll see about putting together a patch that gives the behavior I'd like for running the test suite when use of googletest is disabled.

2018-05-20 00:52 UTC, speth commented on test/SConscript
> +                    CCFLAGS=env['warning_flags'])
Since we append `env['warning_flags']` to `CCFLAGS` regardless, this should be done outside the if/else block.

2018-07-06 21:22 UTC, speth approved these changes

2018-07-09 19:24 UTC, merged