WIP: Non homogenous flow reactor rewrite
Cantera/cantera pull request #575
Opened 2018-11-17 23:13 UTC by arghdos

TODO:

- consolidate IDA / CVODEs into a single abstract base class
- make IDA solver use a FuncEval (rather than the un-used ResidualJacFunc)
- Implement a virtual eval w/ residuals in FuncEval

2018-11-18 19:35 UTC, arghdos commented
@cfgoldsmith -- fyi

2019-01-28 18:58 UTC, speth commented
Could you please rebase this onto the current master rather than introducing merge commits?

2019-01-28 19:05 UTC, skyreflectedinmirrors commented
@speth -- yes, definitely.  There's still a bit of work to be done (implementing a test, making sure all the IDA bindings actually work correctly, etc.), so I will make sure I rebase before we review

2019-02-10 20:50 UTC, arghdos commented
Working from this

[derivs.pdf](https://github.com/Cantera/cantera/files/2849380/derivs.pdf)

2019-03-08 16:20 UTC, arghdos commented
[Updated derivations](https://github.com/Cantera/cantera/files/2946594/derivs.pdf)

2019-03-08 16:33 UTC, arghdos commented
@speth I think this is ready for an initial review when you get a chance.  Once #610 is included in master, I'm going to bump the maxSteps of the call:

```
kin->advanceCoverages(100.0);
```

on line 60 of the `FlowReactor.cpp` to make the steady-state coverages solution more robust, but other than that I think all the major code changes are done.  

I'm working on a validation comparison for @cfgoldsmith against Chemkin, that we should be able to get a unit-test out of -- but I imagine we'll need to discuss how and when that's integrated.

2019-06-11 16:26 UTC, speth requested changes
Hooray! It's great to see this working. The implementation here looks pretty solid to me. I would like to see a few more tests -- I'm not sure what's going on with the one that's marked as an expected failure.

The other important to-do for this will be updating the "science" section of the website.

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/Integrator.h
> + * @defgroup intGroup Zero-dimensional Integrators
```suggestion
 * @defgroup intGroup Integrators for initial value problems
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +        throw CanteraError("Reactor::getState", "Not Implemented");
To differentiate from the other `getState` method:
```suggestion
        throw CanteraError("Reactor::getState(y, ydot)", "Not Implemented");
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +    virtual void getState(doublereal* y, doublereal* ydot)
```suggestion
    virtual void getState(double* y, double* ydot)
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +    //! The area of the reactor [m^2]
```suggestion
    //! The cross-sectional area of the reactor [m^2]
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +    double surfaceAreaToVolumeRatio() const {
Is it easier to think if this as surface area to volume ratio, or surface area per unit length (i.e. perimeter)?

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +                int max_ss_error_fails=10);
I'd suggest leaving out most of these constructor arguments, especially for optional parameters that don't often need to be specified. It makes implementations of derived classes easier, and we need to provide setter methods for all of these anyway.

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +                         double* ydot, double* params)
This declaration would fit on one line.

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +     */
Docstrings shouldn't be duplicated from the base class if there's nothing specific to add.

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/FuncEval.h
> +    int eval_nothrow(double t, double* y, double* ydot, double* residaul);
```suggestion
    int eval_nothrow(double t, double* y, double* ydot, double* residual);
```

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/IDAIntegrator.h
> +// at http://www.cantera.org/license.txt for license and copyright information.
```suggestion
// at https://www.cantera.org/license.txt for license and copyright information.
```

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/IDAIntegrator.h
> +    //! Applies user-specified options to the underlying CVODES solver. Called
```suggestion
    //! Applies user-specified options to the underlying IDAS solver. Called
```

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/Integrator.h
> +    }
If we don't use or provide an implementation of this method for use with IDAS, I don't think it's worth including this abstract method. Likewise for `correctInitial_YaYp_given_Yd`.

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/IDAIntegrator.h
> +    N_Vector m_constraints;
Some of these are sufficiently non-obvious to need docstrings (`m_itol`?)

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/ReactorNet.h
> +
This was already added in a #581 - does this PR just need to be rebased?

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/ReactorNet.h
> +
`doublereal` -> `double`

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    }
`FlowReactor` is only a DAE if you have surface reactions, right? Should we still treat the case without surface reactions as an ODE system?

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    {
Open bracket should be on the same line as `try`. Same for the one following `catch (exception)`.

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +        }
This seems to catch the case where a different reactor type is added to a network containing a `FlowReactor`, but not the other way around, right?

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    denom = m_integ->solution(k);
Declaration and initialization of `denom` can be left as a single statement.

2019-06-11 16:26 UTC, speth commented on interfaces/cython/cantera/examples/surface_chemistry/1D_pfr_surfchem.py
> +perim = np.pi * D  # perimeter of the tube
This variable doesn't get used?

2019-06-11 16:26 UTC, speth commented on interfaces/cython/cantera/examples/surface_chemistry/1D_pfr_surfchem.py
> +mu = 5.7e-5  # kg/(m-s) dynamic viscosity
Doesn't get used?

2019-06-11 16:26 UTC, speth commented on interfaces/cython/cantera/reactor.pyx
> +        super(FlowReactor, self).__init__(*args, **kwargs)
I would rather have these arguments listed directly in the signature, as keyword-only arguments, as we do for the other Reactor-related classes.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +            IDASpgmr(m_ida_mem, PREC_NONE, 0);
```suggestion
            IDASpgmr(m_ida_mem, 0);
```
Should fix the compilation error with Sundials 2.x seen in Travis.

2019-06-11 16:26 UTC, speth commented on include/cantera/numerics/IDAIntegrator.h
> +    //! Error message information provide by CVodes
```suggestion
    //! Error message information provide by IDAS
```

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +        auto *kin = static_cast<InterfaceKinetics*>(m_surf->kinetics());
Nitpicky, but we usually keep the `*` with the type, e.g. `auto* kin`. And in this case, the `*` is unnecessary.

Likewise `auto& m_surf`.

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +        m_ss_atol = atol;
It seems a bit confusing to have "steady-state" tolerances that apply only to the problem of finding surface coverages at the inlet to the reactor, given that the whole thing is a steady-state problem. My suggestion would be to call this `setInletCoverageAtol` or `setInletSurfaceAtol` (and similar for the other methods), unless there is a more general case that we should be considering.

2019-06-11 16:26 UTC, speth commented on interfaces/cython/cantera/test/test_reactor.py
> +    @unittest.expectedFailure
Why is this an expected failure?

2019-06-11 16:26 UTC, speth commented on src/numerics/FuncEval.cpp
> +int FuncEval::eval_nothrow(double t, double* y, double* ydot, double* r)
Given that the only difference between this and the other overload of `eval_nothrow` is in the parameters which are just passed on to `eval`, this could be a good use of variadic templates. I think the only thing that would need to change to enable this would be making the signatures for both `eval` methods have the pattern `eval(<all parameters passed to eval_nothrow>, sensitivity parameters)`.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +void IDAIntegrator::inclAlgebraicInErrorTest(bool yesno)
This method name is long enough that we may as well just call it `includeAlgebraicInErrorTest`.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +    {
open brace should be on the same line as the `if`.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +                           "Cannot use a diagonal matrix with IDA.");
This case can just be ignored and handled as "unknown option", right?

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +    // or IDAGetNumLinResEvals seem to exist
IDA documentation suggests that `IDAGetNumResEvals` exists

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +    doublereal m_dTdz = ydot[3];
`doublereal` -> `double`

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +    const size_t m_non_spec_eq = 4;
I would suggest borrowing the terminology used in the 1D model and call this `m_offset_Y`

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +    // hence are not included ehre
```suggestion
    // hence are not included here
```

2019-06-11 16:26 UTC, speth commented on interfaces/cython/cantera/examples/surface_chemistry/SiF4_NH3_mec.cti
> +units(length='cm', time='s', quantity='mol', act_energy='cal/mol')
Mechanisms files for the examples should be put in the `data/inputs` directory.

It would be good to add a header explaining the origin of this mechanism, and mentioning the example where it is used.

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +    {
Open brace should be on the preceding line.

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +        m_kin->getNetProductionRates(&m_wdot[0]); // "omega dot"
```suggestion
        m_kin->getNetProductionRates(m_wdot.data()); // "omega dot"
```

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +        m_surf->setCoverages(&cov[0]);
In general, replace `&foo[0]` with `foo.data()`.

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +    // Kee 16.48
Are these references to the first or second edition of Kee? I would give a full reference in the docstring for the `FlowReactor` class, and then write something more like "[Kee20XX] eq. YY.ZZ" here.

2019-06-11 16:26 UTC, speth commented on src/zeroD/FlowReactor.cpp
> +    // mass continutity, Kee 16.48
```suggestion
    // mass continuity, Kee 16.48
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/FlowReactor.h
> +    vector_fp m_sdot_temp;
What makes this "temporary"? It would be better to call out the difference between this and `m_sdot`, which if I understand correctly is that this is production of surface species on surfaces, while `m_sdot` is production of gas phase species on surfaces.

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +                         doublereal* residual)
`doublereal`->`double` in all new code.

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +     * @param[out] residual resisduals vector, length neq()
```suggestion
     * @param[out] residual residuals vector, length neq()
```

2019-06-11 16:26 UTC, speth commented on include/cantera/zeroD/Reactor.h
> +    virtual void getConstraints(double* constraints) {
I'm wondering whether the better terminology here is just to refer to these as "algebraic variables" rather than "constraints". In part, this would help avoid confusion with the use of the term "constraint" in Sundials, where they use it to refer to inequality constraints that are imposed in addition to the governing equations.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +        long int nu = m_mupper;
Given that we don't have any current application for anything besides the dense/direct case, I'm not sure it's worth having implementations for these other cases, since there's no way to test them.

2019-06-11 16:26 UTC, speth commented on src/numerics/IDAIntegrator.cpp
> +    m_np = func.nparams();
The sensitivity stuff is complex enough that we ought to have a test for it.

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    m_integ(),
This is the default, so can simply be omitted.

2019-06-11 16:26 UTC, speth commented on src/zeroD/ReactorNet.cpp
> +    m_time = m_integ->step(m_time + 1.0);;
```suggestion
    m_time = m_integ->step(m_time + 1.0);
```

2022-06-08 01:18 UTC, ischoegl commented
Superseded by #1319

2022-06-08 01:18 UTC, closed without merging