Implement function to list data files
Cantera/cantera pull request #589
Opened 2019-01-16 19:29 UTC by CyberDrudge

Fixes #586 

Function `cantera.data.files()` returns list of all data files. It can also be used to get files of a certain type by specifying the required extension.

2019-01-16 21:10 UTC, bryanwweber requested changes
Thanks for sending this change! A few changes to request. When you make them, please squash all of your changes into one commit and force push to this branch to update the pull request.

2019-01-16 21:10 UTC, bryanwweber commented on interfaces/cython/cantera/data/__init__.py
> +	here = Path(__file__).parent
Please use 4 spaces to indent rather than the tab character.

2019-01-16 21:10 UTC, bryanwweber commented on interfaces/cython/cantera/data/__init__.py
> +	return data_files
Please make sure the file ends with one blank line. You can set your editor to do both of these things automatically, depending on which editor you're using the instructions vary.

2019-01-16 21:22 UTC, CyberDrudge commented on interfaces/cython/cantera/data/__init__.py
> +	here = Path(__file__).parent
@bryanwweber my bad, I'll take care of these from now on.

2019-01-16 22:44 UTC, bryanwweber commented
@CyberDrudge Thank you for the quick fixes! Can you squash the three commits here into one commit and force-push to this branch? If you need help with that, just let me know 😄 Thanks!

2019-01-17 08:16 UTC, CyberDrudge commented
@bryanwweber  no worries, a bit of googling showed me the way.

2019-02-01 22:13 UTC, bryanwweber commented
@speth The function here is named `files`. I'm not totally sure that's the best name for this API, I wonder if `list_files` or `list_data_files` or `print_data_files` or something else would be better?

@CyberDrudge Can you please add documentation to this function? It would look something like

```python
def files(ext=''):
    """Overall description of what this function does.

    :param ext:
        Description of what the ext argument does
```

Thanks!

2019-02-03 14:04 UTC, CyberDrudge commented
Changed function name and added Documentation. I will edit name and squash changes if required.

2019-04-27 11:28 UTC, CyberDrudge commented
@bryanwweber does this still require any updates before it gets merged?

2019-11-02 02:18 UTC, bryanwweber approved these changes

2019-11-02 02:19 UTC, merged