Improve warning messages in C++
Cantera/cantera pull request #741
Opened 2019-11-04 02:26 UTC by ischoegl

**Please fill in the issue number this pull request is fixing**

Fixes #683

**Changes proposed in this pull request**

- introduce `warn_user` in C++ layer (in analogy to `warn_deprecated`)
- create uniform formatting for warnings
- add information on method raising the warning
- replace various occurrences of ad-hoc formatted `writelog` warnings with `warn_user`
- issue `warn_user` for Troe when T2 (i.e. T**) is zero

**Other thoughts**

Long-term, it may make sense to use a logger that allows for a meaningful differentiation of levels, e.g. [Boost.Log](https://theboostcpplibraries.com/boost.log). The introduction of `warn_user` now will facilitate a central replacement in `application.h/.cpp` in the future.

2019-11-04 05:27 UTC, ischoegl commented on src/base/global.cpp
> +#include "cantera/base/fmt.h"
Unused

2019-11-09 21:57 UTC, speth requested changes
This looks pretty good to me. I don't think it's a full fix for #683 yet, unless you also want to make the appropriate modifications to the Chemkin conversion scripts.

I would like to avoid adding Boost.Log to our dependencies -- While I generally like Boost, this is unfortunately one of parts that has a compiled library component, and my experience has been that these are very messy dependencies to deal with when you need to support multiple operating systems and a range of different Boost versions. However, a method for raising these warnings through the Python `warnings` module would be interesting as a future extension.

2019-11-09 21:57 UTC, speth commented on include/cantera/base/global.h
> +}
I think this should do something similar to `writelog` where `fmt::format` is used only if additional arguments for substitution are provided. This way, there's no need to worry about special characters being interpreted as part of a format string if there is no formatting to be done.

2019-11-09 21:57 UTC, speth commented on src/base/application.cpp
> +    writelog("DeprecationWarning: '" + method + "': " + extra);
```suggestion
    writelog("DeprecationWarning: '{}': {}", method, extra);
```

2019-11-09 21:57 UTC, speth commented on src/base/application.cpp
> +    writelog("UserWarning: '" + method + "': " + extra);
```suggestion
    writelog("UserWarning: '{}': {}", method, extra);
```

2019-11-09 21:57 UTC, speth commented on src/thermo/PDSS_HKFT.cpp
> +            warn_user("PDSS_HKFT::initThermo()",
```suggestion
            warn_user("PDSS_HKFT::initThermo",
```

2019-11-09 21:57 UTC, speth commented on src/transport/MMCollisionInt.cpp
> +            "RMS error = {:12.6g} in omega_22 fit"
```suggestion
            "RMS error = {:12.6g} in omega_22 fit "
```
(I realize that this was already missing a space)

2019-11-09 21:57 UTC, speth commented on test_problems/cxx_ex/output_blessed.txt
> +UserWarning: 'NasaPoly2::validate':
I'm wondering if it would look better to format the warning message without quotes around the method name.

2019-11-09 21:57 UTC, speth commented on include/cantera/base/global.h
> + * @param msg  C format string for the following arguments
This is not a "C format string" -- it's the Python-like style used by `fmt`.

2019-11-09 21:57 UTC, speth commented on test_problems/cxx_ex/equil_example1.cpp
> +                  << std::endl << std::endl;
It feels a little bit like cheating if you have to modify the output before a warning is issued to get it formatted as desired. One possibility to make multiline warnings more readable would be to automatically add a newline before and after a warning message if it already contains a newline.

2019-11-09 21:57 UTC, speth commented on src/kinetics/Falloff.cpp
> +        }
Given the complexity of the issue, I think this warning needs to provide some additional detail. I would suggest something along the lines of: "Unexpected parameter value T2 == 0. Omitting exp(T2/T) term from falloff expression. To suppress this warning, remove value for T2 from the input file. In the unlikely case that the exp(T2/T) term should be included with T2 effectively equal to 0, set T2 to a sufficiently small value (i.e. T2 < 1e-16)."

2019-11-09 22:58 UTC, ischoegl commented
@speth ... thanks for the review! Will make the changes which won’t take long.

> a method for raising these warnings through the Python warnings module would be interesting as a future extension.

I’ve been wondering about this also, but cannot think of an elegant solution. Definitely another PR

2019-11-09 23:58 UTC, ischoegl commented on test_problems/cxx_ex/equil_example1.cpp
> +                  << std::endl << std::endl;
I added the extra newline here to remain consistent with the existing output, so this is pretty problem specific. I really don't like adding newlines before ... it's up to the user to format things as needed *after*.

2019-11-10 00:01 UTC, ischoegl commented on test_problems/cxx_ex/output_blessed.txt
> +UserWarning: 'NasaPoly2::validate':
No problem. Also suggesting `CanteraWarning` to make things a little clearer

2019-11-10 00:11 UTC, ischoegl commented on src/base/application.cpp
> +    writelog("DeprecationWarning: '" + method + "': " + extra);
this `writelog` didn't use `fmt` ... using 
```C++
    writelog(fmt::format("CanteraWarning: {}: {}", method, extra));
```

2019-11-10 00:31 UTC, ischoegl commented
One final comment for the record: I noticed that these warnings depend on a log level. I don't want to change it without discussion as this PR should not change the overall behavior.
https://github.com/Cantera/cantera/blob/6e60f2f529381962a3af9174a75eb8b2d129b351/src/transport/MMCollisionInt.cpp#L473-L493

2019-11-10 00:37 UTC, ischoegl commented
> This looks pretty good to me. I don't think it's a full fix for #683 yet, unless you also want to make the appropriate modifications to the Chemkin conversion scripts.

This depends on the philosophy: if `ck2yaml` should produce an exact translation of the chemikin input, then this PR fixes #683. If the goal is to pre-empt the behavior, `ck2yaml` should be amended. I don't have a strong opinion here, but would leave this PR as a partial fix as is.

2019-11-11 03:38 UTC, speth commented on test_problems/cxx_ex/output_blessed.txt
> +UserWarning: 'NasaPoly2::validate':
👍 on `CanteraWarning`

2019-11-11 03:44 UTC, speth commented on src/base/application.cpp
> +    writelog("DeprecationWarning: '" + method + "': " + extra);
Oh, I see. That's a bit tricky -- this resolves to `Application::Messages::writelog`, not the global `writelog` function.

2019-11-11 03:55 UTC, speth approved these changes
With the change to `ck2yaml`, I agree that this resolves #683.

2019-11-11 03:56 UTC, merged