Reactor: ensure consistent vector lengths in C++ layer
Cantera/cantera pull request #756
Opened 2019-11-20 20:27 UTC by ischoegl

**Changes proposed in this pull request**

- Ensure consistent vector sizes, i.e. `Reactor::m_advancelimits.size()` is `Reactor::m_nv`
- Prevents hard to track segfaults when `m_advancelimits.size()` < `m_nv` in custom additions

2019-11-27 18:54 UTC, speth reviewed
I see the issue with the keeping the length of `m_advancelimits` consistent across different derived classes (including user-created ones). I wanted to propose an alternative solution, which is to simply resize it to the correct size in the few locations where it is used (all of which are within the `Reactor` base class). See bd58afa72 for the implementation of this option.

I'm :+1: on making the related methods non-virtual.

2019-11-27 20:24 UTC, ischoegl commented
@speth ... resizing at a later time is a *very* good suggestion! Not having to resize in overloaded functions is great. Along those lines, I am suggesting to not resize `m_advancelimits` at all unless it is actually being used. (which allows for some simple checks that avoids overhead).

2019-11-28 00:35 UTC, speth requested changes
This looks good to me. I only have a couple of minor suggestions. In addition to these, can you squash the third commit into the first, since it reverts a number of the changes made in the first commit?

2019-11-28 00:35 UTC, speth commented on src/zeroD/Reactor.cpp
> +    std::copy(limits, limits + m_nv, m_advancelimits.begin());
In one line:
```c++
m_advancelimits.assign(limits, limits + m_nv);
```

2019-11-28 00:35 UTC, speth commented on src/zeroD/Reactor.cpp
> +                     [](double l){return l>0;})) {
Can we have a variable name besides `l`? Looks way too much like `1` in many fonts. Applies to both instances of this.

2019-11-28 00:35 UTC, speth commented on src/zeroD/Reactor.cpp
> +    if (has_limit) {
Using `hasAdvanceLimits()` here would be self-documenting.

2019-11-28 02:41 UTC, ischoegl commented
Done (and squashed).

2019-11-28 03:04 UTC, speth approved these changes

2019-11-28 03:04 UTC, merged