Improve WaterSSTP helper class documentation.
Cantera/cantera pull request #809
Opened 2020-02-16 15:29 UTC by 24sharkS

**Checklist**

- [ ] There is a clear use-case for this code change
- [ ] The commit message has a short title & references relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] The pull request is ready for review

**If applicable, fill in the issue number this pull request is fixing**

Fixes #646 

**Changes proposed in this pull request**

- Added non-instantiability property in WaterSSTP helper class documentation.
-
-

2020-02-19 01:28 UTC, bryanwweber commented
@24sharkS Thank you for the contribution! I'm going to ask @decaluwe to take a look, since he is the creator of that issue.

2020-02-19 18:51 UTC, decaluwe commented
Hi, @24sharkS, many thanks!  I think this is definitely a good start, and may end up being sufficient.  

I think it probably answers the main question that I posed in #646.  The only remaining question on my mind is whether any additional info could give the interested user a better sense of how these files relate to one another.  For example, are each of these called directly by `WaterSSTP` methods?  Or do some of these house sub-routines that are called by one of the other helper classes?  

Reading over the documentation (both your improved documentation here, plus the original documentation in `WaterSSTP.h`, I do not really get an understanding of just how this class works.  It is possible I am just missing it, but I think that should be the overriding goal of this documentation.  If you could add a little bit to help explain how and when these files are called, and possibly some text to `WaterSSTP.h` to help explain in general how the class operates, I think this would be a great improvement.

Thanks again,
Steven

2020-02-19 18:58 UTC, 24sharkS commented
@decaluwe yes I would be happy to do so.
Thanks for the review !!

2020-02-19 20:31 UTC, speth requested changes
Rather than updating the docstrings that apply to the header and implementation files (i.e. the first Doxygen comment block occuring in each file), I would suggest that any additional documentation be added to the docstrings for the classes (occurring just before the declaration of the class). I think the documentation pages for the classes (e.g. [WaterPropsIAPWS](https://cantera.org/documentation/docs-2.4/doxygen/html/d9/d05/classCantera_1_1WaterPropsIAPWS.html)) are generally far more useful than those for the files (e.g. [WaterPropsIAPWS.h](https://cantera.org/documentation/docs-2.4/doxygen/html/d2/d86/WaterPropsIAPWS_8h.html)).

2020-05-29 19:02 UTC, bryanwweber commented
@24sharkS Are you planning to update this pull request? If not, it's fine, I'm just trying to do a bit of cleanup. Thank you!

2020-05-29 19:11 UTC, 24sharkS commented
@bryanwweber Sorry, I wasn't able to update it. If you wan't to close it, it's totally fine.

2020-05-29 19:23 UTC, closed without merging

2020-05-29 19:23 UTC, bryanwweber commented
Thanks @24sharkS !