Documentation & deprecation updates related to input files
Cantera/cantera pull request #864
Opened 2020-06-12 18:16 UTC by speth

**Changes proposed in this pull request**
- Soft deprecation (mark as deprecated but no warnings yet) of all XML and CTI related functionality
- Generalize some documentation to apply to the YAML format
- Mark some features of `AnyMap` and `UnitSystem` as experimental and subject to change
- Clean up a few other minor things in preparation for the 2.5 release

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

2020-06-12 21:49 UTC, bryanwweber requested changes
Thanks for doing this @speth. Just a few minor comments for typos and consistency.

2020-06-12 21:49 UTC, bryanwweber commented on include/cantera/base/global.h
> + * `cti2yaml.py` and `xml2yaml.py` can be used to convert legacy input files to
The script is named `ctml2yaml.py`.

2020-06-12 21:49 UTC, bryanwweber commented on include/cantera/base/global.h
> + * Chemkin-format mechanisms to the YAML and formats, respectively.
This doesn't look right.

2020-06-12 21:49 UTC, bryanwweber commented on include/cantera/thermo/IonsFromNeutralVPSSTP.h
> +     * @param id        ID of the phase in the input file
This one is different from the Margules docstring, but I think the could be the same?

2020-06-12 21:49 UTC, bryanwweber commented on include/cantera/thermo/Phase.h
> + * thermodynamic sense (i.e. it may contain multiple species), the state also
Since you're fixing the typo here, can you remove the `i.e.` too? 😃

2020-06-12 21:49 UTC, bryanwweber commented on include/cantera/thermo/ThermoPhase.h
> +     * file ame and phase name as arguments.
```suggestion
     * file name and phase name as arguments.
```

2020-06-13 18:20 UTC, speth commented on include/cantera/base/global.h
> + * Chemkin-format mechanisms to the YAML and formats, respectively.
🤦‍♂️

2020-06-13 18:28 UTC, speth commented on include/cantera/thermo/Phase.h
> + * thermodynamic sense (i.e. it may contain multiple species), the state also
👍 One down, many more to go...

2020-06-14 01:17 UTC, bryanwweber approved these changes
One more typo, then I think this is good to go :+1:

2020-06-14 01:17 UTC, bryanwweber commented on include/cantera/base/global.h
> + * %Cantera provides converter (`ck2yaml` and `ckcti`) for converting
```suggestion
 * %Cantera provides converters (`ck2yaml.py` and `ck2cti.py`) for converting
```

2020-06-15 03:01 UTC, merged