Add thermal conductivity to DustyGas in python.
Cantera/cantera pull request #988
Opened 2021-03-06 00:33 UTC by chinahg

**Changes proposed in this pull request**

- Thermal conductivity can now be calculated using the DustyGas class in python
-
-

**If applicable, fill in the issue number this pull request is fixing**

Fixes #

**Checklist**

- [ ] There is a clear use-case for this code change
- [ ] The commit message has a short title & references relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] The pull request is ready for review

2021-03-12 21:22 UTC, decaluwe requested changes
Thanks, @chinahg. This looks great.  Coding looks straightforward, and I pulled the code to my machine and verified that it works in Python.

Two questions, both regarding to demonstration:
1. Can we add some code demonstrating that this is functional in the [dusty_gas.py example](https://github.com/Cantera/cantera/blob/main/interfaces/cython/cantera/examples/transport/dusty_gas.py)?
2. It looks like test coverage increases as a result of this change, but unless I'm mistaken, it doesn't look like this specific capability is tested.  Can you add something to the [dustyGasTransport test problem](https://github.com/Cantera/cantera/tree/main/test_problems/dustyGasTransport) to test that this function works? 

Great job!

2021-03-31 12:01 UTC, decaluwe commented
Thanks, @chinahg -- change to the example file looks simple but effective (both of those are good things, for the record 😉).

Now if we can get something testing this in the associated test problem, this will be all ready to merge. 🎉

2021-03-31 12:34 UTC, speth requested changes
@decaluwe, there are no code changes to the C++ implementation here, so I don't think there's anything to test in the C++ test. I think the coverage changes are all spurious, and just an indication that this should be rebased onto the current `main` branch.

@chinahg, can you add a test to the Python test suite? You can add it to the `TestDustyGas` class in `interfaces/cython/cantera/test/test_transport.py`.

2021-03-31 12:34 UTC, speth commented on include/cantera/transport/DustyGasTransport.h
> + * is calculated as the conductivity of the gas phase.
There were no changes here to the `thermalConductivity` method of the C++ `DustyGasTransport` class. That still raises a `NotImplementedError`, which I think is correct In that case, this comment was more correct as it originally was.

2021-03-31 12:34 UTC, speth commented on interfaces/cython/cantera/transport.pyx
> +            return (<CxxDustyGasTransport*>self.transport).gasTransport().thermalConductivity()
Here I think we need to document that this is returning the thermal conductivity of the embedded gas object, as opposed to a value specific to the dusty gas model.

2021-03-31 13:18 UTC, decaluwe commented
Good point, @speth -- thanks.

2021-04-18 23:28 UTC, speth approved these changes

2021-04-19 03:38 UTC, decaluwe approved these changes

2021-04-19 03:38 UTC, decaluwe commented
Many thanks and excellent work, @chinahg!

2021-04-19 03:39 UTC, merged